### ISSUE TITLE
Running scancode installed with sudo pip should not require sudo to run

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1009]
```
jono@ubuntu-16-04:~$ scancode -h
Traceback (most recent call last):
  File "/usr/local/bin/scancode", line 7, in <module>
    from scancode.cli import scancode
  File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 203, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/usr/local/lib/python2.7/dist-packages/plugincode/__init__.py", line 175, in load_plugins
    mgr_setup = manager.setup()
  File "/usr/local/lib/python2.7/dist-packages/plugincode/__init__.py", line 199, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/scancode/plugin_license.py", line 40, in <module>
    from scancode.api import DEJACODE_LICENSE_URL
  File "/usr/local/lib/python2.7/dist-packages/scancode/api.py", line 36, in <module>
    from typecode.contenttype import get_type
  File "/usr/local/lib/python2.7/dist-packages/typecode/__init__.py", line 27, in <module>
    from typecode.contenttype import get_type
  File "/usr/local/lib/python2.7/dist-packages/typecode/contenttype.py", line 49, in <module>
    from extractcode import archive
  File "/usr/local/lib/python2.7/dist-packages/extractcode/archive.py", line 50, in <module>
    from extractcode import libarchive2
  File "/usr/local/lib/python2.7/dist-packages/extractcode/libarchive2.py", line 124, in <module>
    libarchive = load_lib()
  File "/usr/local/lib/python2.7/dist-packages/extractcode/libarchive2.py", line 101, in load_lib
    _bin_dir, lib_dir = command.get_bin_lib_dirs(root_dir)
  File "/usr/local/lib/python2.7/dist-packages/commoncode/command.py", line 223, in get_bin_lib_dirs
    chmod(bin_dir, RX, recurse=True)
  File "/usr/local/lib/python2.7/dist-packages/commoncode/fileutils.py", line 630, in chmod
    os.chmod(parent, current_stat | RWX)
OSError: [Errno 1] Operation not permitted: '/usr/local/lib/python2.7/dist-packages/extractcode/bin/linux-64'
```

**Comment by pombredanne** [comment]
Ok the issue if that we are trying to fix permissions of bundled binaries at runtime.  For a system-wide installation done with sudo, this would force using sudo also at run time and this does not make sense.
It could be that this is permission change may NOT be need after all.

But a quick tests shows that disabling this `chmod` on bundled exes gives an error `OSError: [Errno 13] Permission denied` when trying to use them. I am not sure it is possible to carry permission bits in zip (and therefore in a wheel), but if possible the correct way would likely to commit the proper permission bits and ensure during packaging that these are carried on after a pip install of a wheel. And also for a regualr full archive installation on POSIX.

**Comment by pombredanne** [comment]
@JonoYang this should likely be fixed now when using the develop branch. Could you retest?

**Comment by pombredanne** [comment]
@JonoYang ping :) ^

**Comment by JonoYang** [comment]
@pombredanne This issue has been fixed. I've tested it out on a clean install of Ubuntu 16.04. Closing.
