### ISSUE TITLE
Info + package scanning crashing when multiprocessing (n > 1)

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#1055]
When running a package + file info scan with `-n 2` option specified, the following error occurs:
```
(scancode-toolkit) [sesser@nexb-lt ~/Code/nexB] scancode -ip -n 2 aboutcode-manager/node_modules/ --json-pp ~/abcm-npms-ip-n2.json 
Setup plugins...
Collect file inventory...
Scan files for: info, packages with 2 process(es)...
[####################] 26445                                                                        
Traceback (most recent call last):
  File "/Users/sesser/Code/nexB/scancode-toolkit/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/utils.py", line 79, in main
    standalone_mode=standalone_mode, **extra)
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/cli.py", line 707, in scancode
    stage='scan', kwargs=kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/cli.py", line 855, in run_scanners
    scanned_fc, scanned_dc, scanned_sc = codebase.compute_counts()
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 655, in compute_counts
    self.update_counts(skip_filtered=skip_filtered)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 683, in update_counts
    for resource in self.walk(topdown=False):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 628, in walk
    for res in root.walk(self, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 884, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 884, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 884, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 884, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 884, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 881, in walk
    for child in self.children(codebase):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 904, in children
    return sorted((get_resource(rid) for rid in self.children_rids), key=_sorter)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 904, in <genexpr>
    return sorted((get_resource(rid) for rid in self.children_rids), key=_sorter)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 485, in get_resource
    res = self._load_resource(rid)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 556, in _load_resource
    data = json.load(cached, object_pairs_hook=OrderedDict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 935 - line 1 column 1501 (char 934 - 1500)
```

This happens only when specifying `-ip` and `-n 2`. All other combinations of flags and `n` values do not encounter this error (including full `-clipeu` scans with all combos of `n` values)

This can be replicated by running a `-ip` scan on the `node_modules` directory of https://github.com/nexB/aboutcode-manager

**Comment by pombredanne** [comment]
@majurg I could not reproduce on Linux. Could this be macOS specific? Was this from the develop branch?

**Comment by majurg** [comment]
It may be a macOS specific, and yes it was with the develop branch. I will try again on develop with the newest updates applied.

**Comment by pombredanne** [comment]
@majurg instead you you try the 1055-resource-crash branch ? I have added some extra diagnostics that should be printed on failure (may be too many)

**Comment by majurg** [comment]
Will try that now.

**Comment by majurg** [comment]
@pombredanne When re-running on `1055-resource-crash`, the following error occurs:
```
(scancode-toolkit) [sesser@nexb-lt ~/Code/nexB] scancode -ip -n 4 aboutcode-manager/node_modules/ --json-pp ~/resource-crash-branch.json
Setup plugins...
Collect file inventory...
Scan files for: info, packages with 4 process(es)...
[####################] 26445                                                                        
Traceback (most recent call last):
  File "/Users/sesser/Code/nexB/scancode-toolkit/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/utils.py", line 79, in main
    standalone_mode=standalone_mode, **extra)
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/cli.py", line 708, in scancode
    stage='scan', kwargs=kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/cli.py", line 863, in run_scanners
    codebase.summary[stage + ':files_count'] = scanned_fc
UnboundLocalError: local variable 'scanned_fc' referenced before assignment
```

**Comment by pombredanne** [comment]
@majurg would you mind to make a test again with the latest of #1094 ?

**Comment by pombredanne** [comment]
@majurg now this can be tested!

**Comment by majurg** [comment]
@pombredanne Looks like your fixes worked: I am not longer getting this error and the scans are completing as expected :+1:

**Comment by pombredanne** [comment]
@majurg thanks. I would need to know exactly which errors you have in this scan though as there is still some underlying error looming. Since this is likely a big scan, you can share the full JSON with me privately ( OR share only the scan headers and any file entry that has errors)

**Comment by majurg** [comment]
@pombredanne Its seems like I am getting an error now when I try to run on this branch (1055-resource-crash):
```
(scancode-toolkit) [sesser@nexb-lt ~/Code/nexB] scancode -ip -n 3 aboutcode-manager/node_modules/ --json-pp ~/1055-results.json
Setup plugins...
Collect file inventory...
 Scan files for: info, packages with 3 process(es)...
[####################] 26445                                                                        
ERROR: failed to run post-scan plugin: package-root:
Traceback (most recent call last):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/cli.py", line 802, in run_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/plugin_package.py", line 87, in process_codebase
    for resource in codebase.walk(topdown=False):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 640, in walk
    for res in root.walk(self, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 904, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 904, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 904, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 904, in walk
    for subchild in child.walk(codebase, topdown):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 901, in walk
    for child in self.children(codebase):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 924, in children
    return sorted((get_resource(rid) for rid in self.children_rids), key=_sorter)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 924, in <genexpr>
    return sorted((get_resource(rid) for rid in self.children_rids), key=_sorter)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 488, in get_resource
    res = self._load_resource(rid)
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 569, in _load_resource
    raise Exception(msg)
Exception: ERROR: failed to load resource from cached location: /Users/sesser/Code/nexB/scancode-toolkit/tmp/scancode-scans-2018-06-05T191454.686869-n8DNE7/00/00005100 with content
u'{"name": "collection.js", "location": "/Users/sesser/Code/nexB/aboutcode-manager/node_modules/sequelize/node_modules/lodash/fp/collection.js", "path": "node_modules/sequelize/node_modules/lodash/fp/collection.js", "rid": 20736, "pid": 20696, "cache_location": "/Users/sesser/Code/nexB/scancode-toolkit/tmp/scancode-scans-2018-06-05T191454.686869-n8DNE7/00/00005100", "is_file": true, "is_filtered": false, "children_rids": [], "size": 88, "size_count": 0, "files_count": 0, "dirs_count": 0, "scan_errors": [], "scan_time": 0, "scan_timings": {}, "date": "2016-05-08", "sha1": "75a23149e229dc1435bbddc870542ac1ff298f91", "md5": "631f3bf9a16d8217e94c9cf03d87cbdc", "mime_type": "text/plain", "file_type": "ASCII text", "programming_language": "JavaScript", "is_binary": false, "is_text": true, "is_archive": false, "is_media": false, "is_source": true, "is_script": false, "package_manifest": null, "packages": []}{"name": "collection.js", "location": "/Users/sesser/Code/nexB/aboutcode-manager/node_modules/sequelize/node_modules/lodash/fp/collection.js", "path": "node_modules/sequelize/node_modules/lodash/fp/collection.js", "rid": 20736, "pid": 20696, "cache_location": "/Users/sesser/Code/nexB/scancode-toolkit/tmp/scancode-scans-2018-06-05T191454.686869-n8DNE7/00/00005100", "is_file": true, "is_filtered": false, "children_rids": [], "size": 88, "size_count": 0, "files_count": 0, "dirs_count": 0, "scan_errors": [], "scan_time": 0, "scan_timings": {}, "date": "2016-05-08", "sha1": "75a23149e229dc1435bbddc870542ac1ff298f91", "md5": "631f3bf9a16d8217e94c9cf03d87cbdc", "mime_type": "text/plain", "file_type": "ASCII text", "programming_language": "JavaScript", "is_binary": false, "is_text": true, '
Traceback (most recent call last):
  File "/Users/sesser/Code/nexB/scancode-toolkit/src/scancode/resource.py", line 560, in _load_resource
    data = json.load(cached, object_pairs_hook=OrderedDict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 913 - line 1 column 1705 (char 912 - 1704)


(scancode-toolkit) [sesser@nexb-lt ~/Code/nexB]
```

**Comment by pombredanne** [comment]
@majurg thanks! I was hoping you would get an error, because for now I did not fix anything but only did add ways to diagnose things :P

**Comment by pombredanne** [comment]
Is there a way to get this file? "/Users/sesser/Code/nexB/scancode-toolkit/tmp/scancode-scans-2018-06-05T191454.686869-n8DNE7/00/00005100" ?
Hopefully it is still there. If not I will find a way otherwise to keep it.

**Comment by majurg** [comment]
@pombredanne It looks like the cache is cleared pretty quickly; I could not find that file, even immediately after a scan, the `tmp/` dir appears to be empty.

**Comment by majurg** [comment]
running with `--max-in-memory 0` allows the scan to complete successfully. There no scan errors either when running the scan with this max in memory value.

**Comment by majurg** [comment]
@pombredanne Yes it looks like the latest commits have fixed this. You can close whenever you like.

**Comment by pombredanne** [comment]
Thanks!
