### ISSUE TITLE
Failed to get URL from js in pdf.js

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1125]
This file https://github.com/mozilla/pdf.js/blob/42922c9ae5bc76fdf1c8c123c4762b7441f8b89f/extensions/chromium/extension-router.js fails with this scan:
```
$ scancode -u --json-pp - --verbose extension-router.js 
 Setup plugin: output:json-pp...
 Setup plugin: scan:urls...
Collect file inventory...
Scan files for: urls with 1 process(es)...
Scanned: /tmp/scancode-toolkit/tmp/js/extension-router.js
Save scan results...
 Save scan results as: json-pp...
{
  "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
  "scancode_version": "2.9.2.post109.d2ab73b59",
  "scancode_options": {
    "input": "extension-router.js",
    "--json-pp": "<stdout>",
    "--url": true,
    "--verbose": true
  },
  "scan_start": "2018-07-04T140224.615476",
  "files_count": 1,
  "files": [
    {
      "path": "extension-router.js",
      "type": "file",
      "urls": [],
      "scan_errors": [
        "ERROR: for scanner: urls:\nERROR: Unknown error:\nTraceback (most recent call last):\n  File \"/tmp/scancode-toolkit/src/scancode/interrupt.py\", line 91, in interruptible\n    return NO_ERROR, func(*(args or ()), **(kwargs or {}))\n  File \"/tmp/scancode-toolkit/src/scancode/api.py\", line 102, in get_urls\n    for urls, line_num in found_urls:\n  File \"/tmp/scancode-toolkit/src/scancode/api.py\", line 98, in <genexpr>\n    found_urls = ((u, ln) for (u, ln) in find_urls(location) if u)\n  File \"/tmp/scancode-toolkit/src/cluecode/finder.py\", line 230, in find_urls\n    for _key, url, _line, lineno in matches:\n  File \"/tmp/scancode-toolkit/src/cluecode/finder.py\", line 91, in unique_filter\n    for key, match, line, lineno in matches:\n  File \"/tmp/scancode-toolkit/src/cluecode/finder.py\", line 510, in junk_urls_filter\n    for key, match, line, lineno in matches:\n  File \"/tmp/scancode-toolkit/src/cluecode/finder.py\", line 487, in junk_url_hosts_filter\n    for key, match, line, lineno in matches:\n  File \"/tmp/scancode-toolkit/src/cluecode/finder.py\", line 368, in canonical_url_cleaner\n    match = canonical_url(match)\n  File \"/tmp/scancode-toolkit/src/cluecode/finder.py\", line 355, in canonical_url\n    normalized = urlpy.parse(uri).sanitize().punycode()\n  File \"/tmp/scancode-toolkit/local/lib/python2.7/site-packages/url.py\", line 310, in punycode\n    self._host = IDNA.encode(self._host.decode('utf-8'))[0]\n  File \"/tmp/scancode-toolkit/lib/python2.7/encodings/idna.py\", line 164, in encode\n    result.append(ToASCII(label))\n  File \"/tmp/scancode-toolkit/lib/python2.7/encodings/idna.py\", line 73, in ToASCII\n    raise UnicodeError(\"label empty or too long\")\nUnicodeError: label empty or too long\n"
      ]
    }
  ]
}
Scanning done.
Some files failed to scan properly:
Path: extension-router.js
  ERROR: for scanner: urls:
  ERROR: Unknown error:
  Traceback (most recent call last):
    File "/tmp/scancode-toolkit/src/scancode/interrupt.py", line 91, in interruptible
      return NO_ERROR, func(*(args or ()), **(kwargs or {}))
    File "/tmp/scancode-toolkit/src/scancode/api.py", line 102, in get_urls
      for urls, line_num in found_urls:
    File "/tmp/scancode-toolkit/src/scancode/api.py", line 98, in <genexpr>
      found_urls = ((u, ln) for (u, ln) in find_urls(location) if u)
    File "/tmp/scancode-toolkit/src/cluecode/finder.py", line 230, in find_urls
      for _key, url, _line, lineno in matches:
    File "/tmp/scancode-toolkit/src/cluecode/finder.py", line 91, in unique_filter
      for key, match, line, lineno in matches:
    File "/tmp/scancode-toolkit/src/cluecode/finder.py", line 510, in junk_urls_filter
      for key, match, line, lineno in matches:
    File "/tmp/scancode-toolkit/src/cluecode/finder.py", line 487, in junk_url_hosts_filter
      for key, match, line, lineno in matches:
    File "/tmp/scancode-toolkit/src/cluecode/finder.py", line 368, in canonical_url_cleaner
      match = canonical_url(match)
    File "/tmp/scancode-toolkit/src/cluecode/finder.py", line 355, in canonical_url
      normalized = urlpy.parse(uri).sanitize().punycode()
    File "/tmp/scancode-toolkit/local/lib/python2.7/site-packages/url.py", line 310, in punycode
      self._host = IDNA.encode(self._host.decode('utf-8'))[0]
    File "/tmp/scancode-toolkit/lib/python2.7/encodings/idna.py", line 164, in encode
      result.append(ToASCII(label))
    File "/tmp/scancode-toolkit/lib/python2.7/encodings/idna.py", line 73, in ToASCII
      raise UnicodeError("label empty or too long")
  UnicodeError: label empty or too long
Summary:        urls with 1 process(es)
Errors count:   1
Scan Speed:     9.47 files/sec. 
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s) 
Final counts:   1 resource(s): 1 file(s) and 0 directorie(s) 
Timings:
  scan_start: 2018-07-04T140224.615476
  scan: 0.11s
  total: 0.11s
```

**Comment by pombredanne** [comment]
Fixed in develop
