### ISSUE TITLE
ERROR: failed to run post-scan plugin: summary

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode-toolkit#1141]
Running a Scan on https://github.com/tytso/e2fsprogs/archive/v1.44.2.zip 
Using https://github.com/nexB/scancode-toolkit/archive/fd8e0750d5c293d29a540d20496c66e9fcd7aee9.tar.gz
```
Extracting archives...
Extracting done.
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights, packages with 3 process(es)...
ERROR: failed to run post-scan plugin: summary:
Traceback (most recent call last):
  File "/opt/scancode-toolkit/src/scancode/cli.py", line 821, in run_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/opt/scancode-toolkit/src/summarycode/summarizer.py", line 129, in process_codebase
    summarize_codebase(codebase, keep_details=False, **kwargs)
  File "/opt/scancode-toolkit/src/summarycode/summarizer.py", line 185, in summarize_codebase
    _summary_data = summarizer(resource, children, keep_details=keep_details)
  File "/opt/scancode-toolkit/src/summarycode/summarizer.py", line 220, in license_summarizer
    for child_summary in child_summaries:
TypeError: 'NoneType' object is not iterable

Scanning done.
Some files failed to scan properly:
ERROR: failed to run post-scan plugin: summary:
Traceback (most recent call last):
  File "/opt/scancode-toolkit/src/scancode/cli.py", line 821, in run_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/opt/scancode-toolkit/src/summarycode/summarizer.py", line 129, in process_codebase
    summarize_codebase(codebase, keep_details=False, **kwargs)
  File "/opt/scancode-toolkit/src/summarycode/summarizer.py", line 185, in summarize_codebase
    _summary_data = summarizer(resource, children, keep_details=keep_details)
  File "/opt/scancode-toolkit/src/summarycode/summarizer.py", line 220, in license_summarizer
    for child_summary in child_summaries:
TypeError: 'NoneType' object is not iterable

Path: tmp5rzkvu1q/e2fsprogs-1.44.2.zip-extract/e2fsprogs-1.44.2/tests/i_qcow/image1024.orig.bz2-extract/image1024.orig.bz2-extract
Path: tmp5rzkvu1q/e2fsprogs-1.44.2.zip-extract/e2fsprogs-1.44.2/tests/i_qcow/image2048.orig.bz2-extract/image2048.orig.bz2-extract
Path: tmp5rzkvu1q/e2fsprogs-1.44.2.zip-extract/e2fsprogs-1.44.2/tests/i_qcow/image4096.orig.bz2-extract/image4096.orig.bz2-extract
Summary:        info, licenses, copyrights, packages with 3 process(es)
Errors count:   4
Scan Speed:     2.29 files/sec. 1.43 MB/sec.
Initial counts: 2996 resource(s): 2322 file(s) and 674 directorie(s)
Final counts:   2996 resource(s): 2322 file(s) and 674 directorie(s) for 1.42 GB
Timings:
  scan_start: 2018-07-23T162450.785444
  scan_end: 2018-07-23T164152.210321
  setup_scan:licenses: 3.55s
  setup: 3.55s
  inventory: 1.02s
  pre-scan:classify: 0.14s
  pre-scan: 0.14s
  scan: 1013.51s
  post-scan:summary: 2.14s
  post-scan:package-root: 0.78s
  post-scan: 2.97s
  output:json: 1.95s
  output: 1.95s
  total: 1023.38s
```

**Comment by pombredanne** [comment]
@tdruez thank you for kicking in the tires of this new feature!
In terms of scancode options, I assume you might have been using something like `--license --info --copyright --package --classify --summary --summary-key-files` ?

**Comment by tdruez** [comment]
I'm using the following arguments:

```
--info 
--copyright
--license
--package
--classify
--summary
--summary-key-files
--json
```

**Comment by pombredanne** [comment]
As a side note it is funny to see the actual size of the extracted files for e2fsprogs to be over 1GB++ since there are sparse test files that are disk images in the bunch ... And these test files may be the bug cause.

**Comment by pombredanne** [comment]
This has been merged in develop.
