### ISSUE TITLE
First run fails when using a wheel installation

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1388]
Using the latest 3.0.2 I install in a  fresh virtualenv with
`pip install scancode-toolkit==3.0.2`

Then this fails
```
$ scancode --license --copyright --package --html=scancode-2019-02-21.html --verbose tmp/lib/python2.7/site-packages/scancode/
 Setup plugin: scan:packages...
 Setup plugin: output:html...
 Setup plugin: scan:copyrights...
 Setup plugin: scan:licenses...
Collect file inventory...
Scan files for: licenses, copyrights, packages with 1 process(es)...
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/__init__.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/__init__.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/apache-2.0.LICENSE
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/api.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/api.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/cli.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/cli.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/cli_test_utils.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/cli_test_utils.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/extract_cli.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/extract_cli.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/help.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/help.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/interrupt-robotframework.ABOUT
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/interrupt-robotframework.NOTICE
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/interrupt-thread2.ABOUT
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/interrupt-thread2.README
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/interrupt.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/interrupt.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/NOTICE
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/plugin_ignore.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/plugin_ignore.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/plugin_info.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/plugin_info.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/plugin_mark_source.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/plugin_mark_source.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/plugin_only_findings.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/plugin_only_findings.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/pool.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/pool.py.ABOUT
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/pool.py.LICENSE
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/pool.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/resource.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/resource.pyc
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/utils.py
Scanned: /home/pombreda/tmp/sc/tmp/lib/python2.7/site-packages/scancode/utils.pyc
Filter scans...
 Filter scan: licenses...
 Filter scan: copyrights...
 Filter scan: packages...
Save scan results...
 Save scan results as: html...
Scanning done.
Some files failed to scan properly:
Path: scancode/__init__.py
  ERROR: for scanner: licenses:
  ERROR: Unknown error:
  Traceback (most recent call last):
    File "/home/pombreda/tmp/sc/tmp/local/lib/python2.7/site-packages/scancode/interrupt.py", line 91, in interruptible
      return NO_ERROR, func(*(args or ()), **(kwargs or {}))
    File "/home/pombreda/tmp/sc/tmp/local/lib/python2.7/site-packages/scancode/api.py", line 172, in get_licenses
      for match in idx.match(location=location, min_score=min_score, **kwargs):
    File "/home/pombreda/tmp/sc/tmp/local/lib/python2.7/site-packages/licensedcode/index.py", line 589, in match
      negative_matches = self.negative_match(whole_query_run)
    File "/home/pombreda/tmp/sc/tmp/local/lib/python2.7/site-packages/licensedcode/index.py", line 637, in negative_match
      return match_aho.exact_match(self, query_run, self.negative_automaton)
    File "/home/pombreda/tmp/sc/tmp/local/lib/python2.7/site-packages/licensedcode/match_aho.py", line 108, in exact_match
      for qend, matched_rule_segments in automaton.iter(qtokens_as_str):
  AttributeError: Not an Aho-Corasick automaton yet: call add_word to add some keys and call make_automaton to convert the trie to an automaton.
Path: scancode/__init__.pyc
  ERROR: for scanner: licenses:
.....

```

then this works after:
```
$ scancode --reindex-licenses
```

**Comment by ritiek** [comment]
Hi there! For some reason I can't reproduce this:
```
$ virtualenv -p python ~/Env/scancode
$ source ~/Env/scancode/bin/activate
$ pip install scancode-toolkit==3.0.2
```
```
$ scancode --license --copyright --package --html=scancode-today.html --verbose ~/Env/scancode/lib/python2.7/site-packages/scancode
 Setup plugin: scan:packages...
 Setup plugin: output:html...
 Setup plugin: scan:copyrights...
 Setup plugin: scan:licenses...
Collect file inventory...
Scan files for: licenses, copyrights, packages with 1 process(es)...
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/__init__.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/__init__.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/apache-2.0.LICENSE
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/api.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/api.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/cli.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/cli.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/cli_test_utils.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/cli_test_utils.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/extract_cli.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/extract_cli.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/help.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/help.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/interrupt-robotframework.ABOUT
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/interrupt-robotframework.NOTICE
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/interrupt-thread2.ABOUT
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/interrupt-thread2.README
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/interrupt.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/interrupt.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/NOTICE
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/plugin_ignore.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/plugin_ignore.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/plugin_info.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/plugin_info.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/plugin_mark_source.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/plugin_mark_source.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/plugin_only_findings.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/plugin_only_findings.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/pool.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/pool.py.ABOUT
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/pool.py.LICENSE
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/pool.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/resource.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/resource.pyc
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/utils.py
Scanned: /home/ritiek/Env/scancode/lib/python2.7/site-packages/scancode/utils.pyc
Filter scans...
 Filter scan: licenses...
 Filter scan: copyrights...
 Filter scan: packages...
Save scan results...
 Save scan results as: html...
Scanning done.
Summary:        licenses, copyrights, packages with 1 process(es)
Errors count:   0
Scan Speed:     2.12 files/sec.
Initial counts: 37 resource(s): 36 file(s) and 1 directorie(s)
Final counts:   37 resource(s): 36 file(s) and 1 directorie(s)
Timings:
  scan_start: 2019-03-06T142508.882063
  scan_end:   2019-03-06T142530.929098
  setup_scan:licenses: 5.00s
  setup: 5.00s
  scan: 17.00s
  output:html: 3.60s
  output: 3.60s
  total: 25.65s
```

I also tried creating a wheel and installing it from develop branch but that works absolutely fine as well.

**Comment by pombredanne** [comment]
@ritiek Thank you ++ for trying this. Do you mind telling me which OS and python version you use?

**Comment by ritiek** [comment]
I'm using  Linux Mint 19.

```
$ python -V
Python 2.7.15rc1

$ uname -a
Linux coolpc 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pombredanne** [comment]
@ritiek thank you. That's useful to know!

**Comment by pombredanne** [comment]
@dankegel could your reports at #1463 #1464 be related to this?

**Comment by dankegel** [comment]
I don't see a clear connection.

@ritiek Can you reproduce the problem inside an lxc container?  If so, that'd make it a lot easier for us to test.

**Comment by ritiek** [comment]
@dankegel Nope. I created a simple Dockerfile but still couldn't reproduce the error.

In case anybody wants to try:

```
$ mkdir scancode-docker
$ cd scancode-docker
```
Create a `Dockerfile` with these contents:
```dockerfile
FROM python:2.7.15
RUN pip install scancode-toolkit==3.0.2
ENTRYPOINT ["scancode", "--license", "--copyright", "--package", "--html=scancode-today.html", "--verbose", "/usr/local/lib/python2.7/site-packages/scancode/"]
```
```
$ docker build -t scancode-test .
$ docker run --rm -it scancode-test
```

----------

My experience with Docker/containerization is limited so I'm all ears if anybody senses anything wrong with the above approach.

**Comment by dankegel** [comment]
That approach doesn't mimic your situation very well.

What I'm proposing is to use a Linux Mint 19 (or is it 19.1?) base container, not a purified python base container.

**Comment by pombredanne** [comment]
With #2265 there is now a contributed Dockerfile and we can now also install correctly the latest versions from PyPI
Closing this then!
