### ISSUE TITLE
`--from-json` throws error when trying to covert to CSV from a package id's json file

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1398]
```
(scancode-toolkit) C:\Users\CYL\git\scancode-toolkit>scancode --from-json C:\Users\Projects\all-jar-info_identified.json --csv C:\Users\Projects\all-jar-info_identified.csv
Setup plugins...
Collect file inventory...
ERROR: failed to run output plugin: csv:
Traceback (most recent call last):
  File "c:\users\cyl\git\scancode-toolkit\src\scancode\cli.py", line 870, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "c:\users\cyl\git\scancode-toolkit\src\formattedcode\output_csv.py", line 58, in process_codebase
    write_csv(results, csv)
  File "c:\users\cyl\git\scancode-toolkit\src\formattedcode\output_csv.py", line 76, in write_csv
    rows = list(flatten_scan(results, headers))
  File "c:\users\cyl\git\scancode-toolkit\src\formattedcode\output_csv.py", line 197, in flatten_scan
    flat = flatten_package(package, path)
  File "c:\users\cyl\git\scancode-toolkit\src\formattedcode\output_csv.py", line 299, in flatten_package
    pack[compo_nk] = ' \n'.join(existing + [compo_val])
TypeError: coercing to Unicode: need string or buffer, list found
```

**Comment by mriiinal** [comment]
Please add the steps to recreate the issue and the source json file that you're using.

**Comment by chinyeungli** [comment]
From @pombredanne 
```
the bug comes from the fact that the CSV code of ScanCode excludes certain fields  from the JSON returned from a DejaCode package ID when converting to CSV
https://github.com/nexB/scancode-toolkit/blob/develop/src/formattedcode/output_csv.py#L227
BUT it should instead only consider fields it knows about
```

**Comment by mriiinal** [comment]
I think I understood the problem. @chinyeungli Please link the DejaCode package that you were using for this.

**Comment by pombredanne** [comment]
@mriiinal thank you for your help!  But I have already a fix working that I will push shortly.
