### ISSUE TITLE
Error when there's sub-directory under rcs & sccs directory

### ISSUE THREAD

**Issue by lekhoa88** [nexB/scancode-toolkit#1422]
### Description
When I scan a directory sccs(or rcs) with sub-directory(such as rcs/a), the scan scan fails with keyerror. 
Note 1: I've scanned a git directory with .git & it works without error. 
Note 2: when I comment out '*/rcs' and '*/sccs' in src/commoncode/ignore.py, there's no error.

```
[khoale:~/workspace/test]> mkdir sccs
[khoale:~/workspace/test]> mkdir sccs/a
[khoale:~/workspace/test]> /usr2/khoale/scancode-toolkit-3.0.2/scancode -clp --verbose --json-pp - /usr2/khoale/workspace/test
 Setup plugin: output:json-pp...
 Setup plugin: scan:packages...
 Setup plugin: scan:copyrights...
 Setup plugin: scan:licenses...
Collect file inventory...
ERROR: failed to collect codebase at: '/usr2/khoale/workspace/test'
Traceback (most recent call last):
  File "/usr2/khoale/scancode-toolkit-3.0.2/src/scancode/cli.py", line 707, in scancode
    max_in_memory=max_in_memory
  File "/khoale/scancode-toolkit-3.0.2/src/scancode/resource.py", line 280, in __init__
    self._populate()
  File "/usr2/khoale/scancode-toolkit-3.0.2/src/scancode/resource.py", line 439, in _populate
    parent = parent_by_loc.pop(top)
KeyError: '/usr2/khoale/workspace/test/sccs/a'
```

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? Linux / Ubuntu 16.04 LTS ; python 2.7.3
* What version of scancode-toolkit was used to generate the scan file? scancode-toolkit-3.0.2/
* What installation method was used to install/run scancode? (pip/source download/other)
Download from release git release page &  unzip

**Comment by pombredanne** [comment]
@lekhoa88 thank you ++ for this bug report! that's a nasty one alright :|

**Comment by pombredanne** [comment]
Would you care to submit a PR? I think the fix is not to remove the ignore entries, but rather to remove the `*/` prefix and just  keep `SCCS` and `RCS` here https://github.com/nexB/scancode-toolkit/blob/887ae131c3809a6a002267eebf8f2d5e817499f9/src/commoncode/ignore.py#L198

**Comment by pombredanne** [comment]
@lekhoa88 This was fixed (a long while agao) by @JonoYang  in https://github.com/nexB/commoncode/commit/641150b1a93eae7d2a4c9245b945b22f6f73e44d
Closing now. Thanks again.

**Comment by pombredanne** [comment]
Actually I also pushed some extra fixes in https://github.com/nexB/commoncode/pull/24
