### ISSUE TITLE
Installation in Linux

### ISSUE THREAD

**Issue by ChinnuJose** [nexB/scancode-toolkit#1450]
### Description
I have already installed  2.2.1, now i am trying to install 3.0.2. But getting below error, do i have to remove old installation before proceeding with new installation?

### System configuration

* Linux 7.3
* 3.0.2

[root@esbdslv51 scancode-toolkit-3.0.2]# ./scancode --help
* Configuring ScanCode for first use...
Traceback (most recent call last):
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/scancode/cli.py", line 206, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/plugincode/__init__.py", line 190, in load_plugins
    mgr_setup = manager.setup()
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/plugincode/__init__.py", line 217, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/lib/python2.7/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/packagedcode/__init__.py", line 37, in <module>
    from packagedcode import rubygems
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/packagedcode/rubygems.py", line 40, in <module>
    from extractcode import archive
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/extractcode/archive.py", line 51, in <module>
    from extractcode import libarchive2
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/extractcode/libarchive2.py", line 114, in <module>
    libarchive = load_lib()
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/extractcode/libarchive2.py", line 104, in load_lib
    return command.load_shared_library(dll, libdir)
  File "/test/Talko-Scan/scancode-toolkit-3.0.2/src/commoncode/command.py", line 222, in load_shared_library
    lib = ctypes.CDLL(dll_path)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbz2.so.1.0: cannot open shared object file: No such file or directory

**Comment by ritiek** [comment]
Seems like you're missing some libraries. Did you install the apt packages as mentioned in the [installation section](https://github.com/nexB/scancode-toolkit#installation) in README? That should most likely fix this.

**Comment by pombredanne** [comment]
Or this could be a sign of #443  ?
@ChinnuJose which OS do you run when you state 7.3? Red Hat Enterprise Linux ?

**Comment by ChinnuJose** [comment]
yes Red Hat Enterprise Linux

**Comment by pombredanne** [comment]
@ChinnuJose so the way to solve this short term is to run this once:

`sudo ln -s /usr/lib64/libbz2.so.1 /usr/lib64/libbz2.so.1.0`

That was reported here https://github.com/nexB/scancode-toolkit/issues/443#issue-199831650 by @akaihola and this still needs to be fixed.
