### ISSUE TITLE
Failure to collect a URL

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1578]
### Description
With this file https://raw.githubusercontent.com/hyperledger/fabric-ca/27fbd69ab2d0f07212b382eb04aa85c904d2c300/vendor/github.com/google/certificate-transparency-go/x509/verify.go and this scan:
`scancode --url --json-pp - verify.go` I get this error:

```
  Traceback (most recent call last):
    File "/opt/scancode-toolkit/src/scancode/interrupt.py", line 91, in interruptible
      return NO_ERROR, func(*(args or ()), **(kwargs or {}))
    File "/opt/scancode-toolkit/src/scancode/api.py", line 142, in get_urls
      for urls, line_num in found_urls:
    File "/opt/scancode-toolkit/src/scancode/api.py", line 138, in <genexpr>
      found_urls = ((u, ln) for (u, ln) in find_urls(location) if u)
    File "/opt/scancode-toolkit/src/cluecode/finder.py", line 236, in find_urls
      yield unicode(url), lineno
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)
```

Reported by @dabutvin

**Comment by pombredanne** [comment]
This has been fixed an merged in develop @dabutvin thank you ++
