### ISSUE TITLE
"./configure" doesn't work on Python 3

### ISSUE THREAD

**Issue by Abhishek-Dev09** [nexB/scancode-toolkit#1632]
After creating virtual env for python 3.6 When i run `./configure` it fails. 
OS- Ubuntu 18.04 , MacOS Mojave
Python version - 3.6.8
virtual name - abhi
```
ubuntu@abhi:~/scancode-toolkit$ source abhi/bin/activate
(abhi) ubuntu@abhi:~/scancode-toolkit$ ./configure --clean
* Cleaning ...
(abhi) ubuntu@abhi:~/scancode-toolkit$ ./configure
* Configuring Python ...
* Installing components ...
/bin/sh: 1: /home/ubuntu/scancode-toolkit/bin/pip: not found
Traceback (most recent call last):
  File "/home/ubuntu/scancode-toolkit/etc/configure.py", line 577, in <module>
    create_virtualenv(standard_python, root_dir, thirdparty_dirs, quiet=quiet)
  File "/home/ubuntu/scancode-toolkit/etc/configure.py", line 269, in create_virtualenv_py3
    run_pip(['pip', 'setuptools', 'virtualenv', 'wheel'], root_dir, tpp_dirs, quiet)
  File "/home/ubuntu/scancode-toolkit/etc/configure.py", line 306, in run_pip
    call(pcmd, root_dir)
  File "/home/ubuntu/scancode-toolkit/etc/configure.py", line 133, in call
    subprocess.check_call(cmd, shell=True, env=dict(os.environ), cwd=root_dir)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"/home/ubuntu/scancode-toolkit/bin/pip" install --upgrade --no-index --no-cache-dir --no-warn-script-location --find-links="/home/ubuntu/scancode-toolkit/thirdparty" pip setuptools virtualenv wheel' returned non-zero exit status 127.
(abhi) ubuntu@abhi:~/scancode-toolkit$ 
```

**Comment by pombredanne** [comment]
@Abhishek-Dev09 you should not create a virtual env your self. Configure does this for you

Instead do this:
1. start from a clean checkout and cd to that directory
2. run `./configure`
3. `source bin/activate`

**Comment by Abhishek-Dev09** [comment]
@pombredanne : Please refer to #1631

**Comment by pombredanne** [comment]
This is now working. Closing.
