### ISSUE TITLE
Scanning package for keyword

### ISSUE THREAD

**Issue by ummer9987** [nexB/scancode-toolkit#1751]
### Description
Is it possible to trigger the scancode for searching a keyword in the packages. If user gives an input keyword is it possible to search that particular keyword in the packages.

Current version 3.0.2

**Comment by ummer9987** [comment]
@pombredanne could you please help me on this

**Comment by pombredanne** [comment]
@ummer9987 Thank you for this 
@ChinnuJose has also a ticket in #1755

I suggest we have a chat online on Gitter on the details together to hammer a design.
The chat room is at https://gitter.im/aboutcode-org/discuss

**Comment by ummer9987** [comment]
@pombredanne We are from same team. How will we able to implement this keyword search?

**Comment by pombredanne** [comment]
@ummer9987 @ChinnuJose  if you are from the same team, let's keep only one ticket.

Please work together to close one of the two tickets.

The best place to implement this is IMHO to model after code in the cluecode module. The email and url scans are essentially regex string searches.

That said, there are many design questions pending. 

What can be searched?:
- plain strings?
- globs?
- regex?
- would upper/lower case matter?

And then what could be the user experience:

- do we allow to search in binaries or only in plain text files?
- what is the data structure returned and does it include the line numbers?
- is there a configurable limit to the number of returned values (this is something done for email urls)?
- what is the name of new command option(s)?
- can multiple strings be searched at once?

Also this new "scan" could be implemented as an external plugin, but I think it makes ore sense to have it part of the core scancode.

**Comment by ChinnuJose** [comment]
What can be searched?:

plain strings? - Yes
globs? - Not Mandatory
regex? - Could be
would upper/lower case matter? - No . 

And then what could be the user experience: IPR & Legal team can evaluate the package more efficiently and check in detail if specific keyword exist.


do we allow to search in binaries or only in plain text files? - Both
what is the data structure returned and does it include the line numbers? - Yes/No (1/0) . It will be good if we can also get the Line numbers ,no of occurrence ,file
is there a configurable limit to the number of returned values (this is something done for email urls)? : No
what is the name of new command option(s)? : Keyword-search ?
can multiple strings be searched at once? : Yes
Also this new "scan" could be implemented as an external plugin, but I think it makes ore sense to have it part of the core scancode.
It will be good if it is inbuilt, as i think it will be useful for others, without much need to plugin configuration.  But how much time will it take to create such an Plugin and then to make the release.

Also, if we can do it externally then how we can integrate this with Scancode?

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra  ping ... see the details above

**Comment by ummer9987** [comment]
@pombr We were trying to add the sample plugin in https://github.com/nexB/scancode-toolkit/wiki/How-To:-Add-a-post-scan-plugin. We followed all the steps mentioned in the page, but we are getting the below error.
Could not find a version that satisfies the requirement scancode-toolkit-3.0.2 (from scancode-hello==1.0.0) (from versions: )
No matching distribution found for scancode-toolkit-3.0.2 (from scancode-hello==1.0.0)

Could you please help us on this
![scancode](https://user-images.githubusercontent.com/56027123/66836789-9ae38d80-ef7f-11e9-8e34-82955959aba7.JPG)

**Comment by ummer9987** [comment]
@pombredanne We have managed to install the sample plugin successfully. But after installation we triggered the scan but it is showing Error: no such option: --hello.

Could you please help us on this

**Comment by majurg** [comment]
@ummer9987 Make sure you are in the scancode-toolkit virtualenv before installing the `hello` sample plugins.

**Comment by ummer9987** [comment]
@majurg @pombredanne The sample plugin works with one change. 
 Could you please let me know whether you were able to develop the plugin with the requirements provided above.

**Comment by pombredanne** [comment]
@ummer9987  @AyanSinhaMahapatra will be working on this at the same time as he writes a tutorial to write plugins. So this will take some time, unless you want to give it a go before that separately?

**Comment by ummer9987** [comment]
@pombredanne @AyanSinhaMahapatra We are also working on that, will share the updates.

**Comment by ummer9987** [comment]
@pombredanne We have created keyword plugin using the email plugin code. But when we try to trigger a scan using the --keyword option it is showing no such keyword error. If we avoid that option am getting another error
ERROR: failed to load plugin: scan:search:

Could you please help me on this

**Comment by JonoYang** [comment]
@ummer9987 Do you have the code available for us to look at? Its hard to see the possible problems without all the files available.

**Comment by ummer9987** [comment]
[plugin_changes.zip](https://github.com/nexB/scancode-toolkit/files/3755954/plugin_changes.zip)
@JonoYang please find the attached plugin code.

**Comment by ummer9987** [comment]
Sorry closed the issue by accident

**Comment by JonoYang** [comment]
@ummer9987 I've looked at your files.

In `plugin_changes.zip/plugin_changes/scancode-keyword-search/src/keyword_search/keyword_search.py` on line 50

```
    options = [
        CommandLineOption(('-k', '--keyword'),
            is_flag=True, default=False,
            help='Scan <input> to search for keywords.',
            help_group=OTHER_SCAN_GROUP)
    ]
```
The option is named `keyword` whereas in `plugin_changes.zip/plugin_changes/scancode-keyword-search/setup.py` on line 49, the entry point is named `search`

```
    entry_points={
        'scancode_scan': [
            'search = keyword_search.keyword_search:SearchKeyword',
        ],
    },
```

The name in the entry points and the option names should be the same.
[plugin_changes.zip](https://github.com/nexB/scancode-toolkit/files/3757618/plugin_changes.zip)

I've renamed the option `search` to `kwsearch` in both the plugin and setup.py.

Let me know if the option is enabled for you.

**Comment by ummer9987** [comment]
@JonoYang I am still getting the same error with the changes you told.

**Comment by JonoYang** [comment]
@ummer9987 

After you make the changes to your plugin, you need to reinstall the plugin.

Make sure you are in the `scancode-toolkit` virtual environment

Make the changes to your code

Install the plugin using `pip install -e <path to plugin folder>` 

I forgot to mention this in my previous post, my apologies.

**Comment by ummer9987** [comment]
@JonoYang 
We were doing the same after the code change. am still getting the error.
below is the command and error we are getting

/opt/scancode-toolkit-3.0.2/bin/scancode -c -p -l test/2205/18984 --kwsearch --json-pp test.json
ERROR: failed to load plugin: scan:kwsearch:
Traceback (most recent call last):
  File "/opt/scancode-toolkit-3.0.2/src/scancode/cli.py", line 509, in scancode
    if plugin.is_enabled(**kwargs):
  File "/opt/scancode-toolkit-3.0.2/src/plugincode/__init__.py", line 113, in is_enabled
    raise NotImplementedError
NotImplementedError

Removing temporary files...done.

/bin/scancode -i -n 2 test/2205/18984 --kwsearch --json test.json          ERROR: failed to load plugin: pre_scan:ignore-binaries-search:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scancode/cli.py", line 509, in scancode
    if plugin.is_enabled(**kwargs):
TypeError: is_enabled() takes exactly 2 arguments (1 given)

Removing temporary files...done.

**Comment by JonoYang** [comment]
@ummer9987 

The method names were not correct in the plugin. I've named them properly, The plugin should be able to be enabled.
[scancode-keyword-search.zip](https://github.com/nexB/scancode-toolkit/files/3765995/scancode-keyword-search.zip)

**Comment by ummer9987** [comment]
@JonoYang It works now. Thank you
Now I am facing issue in the get_keys function in api.py we are trying to resolve that. At the same time could you also please trace out the function? I am new to python development. We need to deliver the plugin by this week
@pombredanne  @AyanSinhaMahapatra Is there any update on the plugin.

**Comment by ummer9987** [comment]
@JonoYang @pombredanne 
When we are trying to scan a package with new options we are getting the below error. Could you please help me on this

Setup plugins...
Collect file inventory...
Scan files for: kwsearch, licenses, copyrights, packages with 1 process(es)...
[------------------#-] 2 Scanned: Configuration.java
Removing temporary files...done.
Traceback (most recent call last):
  File "bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/opt/scancode-toolkit-3.0.2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/scancode-toolkit-3.0.2/src/scancode/utils.py", line 79, in main
    standalone_mode=standalone_mode, **extra)
  File "/opt/scancode-toolkit-3.0.2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/scancode-toolkit-3.0.2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/scancode-toolkit-3.0.2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/scancode-toolkit-3.0.2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/scancode-toolkit-3.0.2/src/scancode/cli.py", line 752, in scancode
    quiet=quiet, verbose=verbose, kwargs=kwargs,
  File "/opt/scancode-toolkit-3.0.2/src/scancode/cli.py", line 929, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "/opt/scancode-toolkit-3.0.2/src/scancode/cli.py", line 1059, in scan_codebase
    setattr(resource, key, value)
AttributeError: 'ScannedResource' object has no attribute 'keys'

**Comment by JonoYang** [comment]
@ummer9987 Can you upload the code you have right now and tell me about some of the changes you have made on top of scancode, e.g. where you added new code and what you are trying to do with it?

**Comment by ummer9987** [comment]
@pombredanne @JonoYang We were able to develop the plugin it is working in our environment. Currently we have hard coded the set of keywords in plugin itself since we only have a limited number of keywords to be searched. It is possible to add set of keywords along with the command line options. Is it possible to add the plugin in the next release.
[scancode_keyword_plugin_code.zip](https://github.com/nexB/scancode-toolkit/files/3895376/scancode_keyword_plugin_code.zip)

**Comment by pombredanne** [comment]
@ummer9987 Thank you! this is great! It is a tad uncommon to have a zip but it can be worked out if you are not familiar with git.

I would still need a formal sign-off per https://developercertificate.org/ (e.g. like `Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>` but with your name and email) ... can you paste that in a message here?

**Comment by pombredanne** [comment]
What I will do is craft a PR from this so we can review it there.

**Comment by pombredanne** [comment]
@ummer9987 I look at the code and there seems to be two different searches (legal and keys)?
also the things being searched cannot be provided at the command line so it may be hard to use in practice. Is that your intent? Can you comment a bit?

**Comment by ChinnuJose** [comment]
We have 2 type of search Legal & IPR, which could be defined through command line. And currently we have hard coded the keywords to be searched. But we also have to modify this in a way that the keywords to be given through command line. is it possible for you to make such changes in the code & include in next release? or do we have to modify the code to give the keywords through command line

**Comment by balakrishna-mukundaraj** [comment]
Hello all Good day
:)
we have a query regarding the kwsearch plugin we came across while reading about it in below issue link
https://github.com/nexB/scancode-toolkit/files/3897149/scancode_keyword_plugin_code.zip
Is this plugin made available publicly in current releases?
if so we would like to use basic features of those
could you kindly help?
