### ISSUE TITLE
Dwarf dump has the error when running on Windows 64bit.

### ISSUE THREAD

**Issue by linexb** [nexB/scancode-toolkit#1761]
### Description
Chin-Yeung has reported an issue when running dwarfdump on windows 64bit, please refer to the logs:
```
(scancode-toolkit) C:\Users\thoma\git\scancode-toolkit\plugins\scancode-dwarfdump-win_amd64>pip install .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing c:\users\thoma\git\scancode-toolkit\plugins\scancode-dwarfdump-win_amd64
Building wheels for collected packages: scancode-dwarfdump
  Building wheel for scancode-dwarfdump (setup.py) ... done
  Created wheel for scancode-dwarfdump: filename=scancode_dwarfdump-1.0.0-cp27-none-any.whl size=3164064 sha256=568ec283d7e06bd86d32567e3be0d8b9817212bad26637e1b9813b9c5ef24a21
  Stored in directory: C:\Users\thoma\AppData\Local\pip\Cache\wheels\2a\c4\29\ae812b5c81533d183680c01b491e3128c03fe5b9f7d73db149
Successfully built scancode-dwarfdump
Installing collected packages: scancode-dwarfdump
Successfully installed scancode-dwarfdump-1.0.0
WARNING: You are using pip version 19.2.3, however version 19.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(scancode-toolkit) C:\Users\thoma\git\scancode-toolkit\plugins\scancode-dwarfdump-win_amd64>cd ../..

(scancode-toolkit) C:\Users\thoma\git\scancode-toolkit>scancode --help
========================================================================
ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
The following plugin(s) are referenced and cannot be loaded/imported:
No module named scancode_dwarfdump
========================================================================
Traceback (most recent call last):
  File "C:\Users\thoma\git\scancode-toolkit\Scripts\scancode-script.py", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "C:\Users\thoma\git\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\thoma\git\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\thoma\git\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\thoma\git\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\thoma\git\scancode-toolkit\src\scancode\cli.py", line 228, in <module>
    raise e
ImportError: No module named scancode_dwarfdump

(scancode-toolkit) C:\Users\thoma\git\scancode-toolkit>
```

**Comment by chinyeungli** [comment]
I tried with the "1752-dwarf-test-failure" and still get the same error:
```
(scancode-toolkit) C:\Users\thoma\git\scancode-toolkit\plugins\scancode-dwarfdump-win_amd64>pip install  .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing c:\users\thoma\git\scancode-toolkit\plugins\scancode-dwarfdump-win_amd64
Building wheels for collected packages: scancode-dwarfdump
  Building wheel for scancode-dwarfdump (setup.py) ... done
  Created wheel for scancode-dwarfdump: filename=scancode_dwarfdump-1.0.0-cp27-none-any.whl size=3164097 sha256=084cb82d53718371f91719d6405435baae9a9b6cb040f81f8416cb8480a79cf3
  Stored in directory: C:\Users\thoma\AppData\Local\pip\Cache\wheels\2a\c4\29\ae812b5c81533d183680c01b491e3128c03fe5b9f7d73db149
Successfully built scancode-dwarfdump
Installing collected packages: scancode-dwarfdump
Successfully installed scancode-dwarfdump-1.0.0
WARNING: You are using pip version 19.2.3, however version 19.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(scancode-toolkit) C:\Users\thoma\git\scancode-toolkit\plugins\scancode-dwarfdump-win_amd64>cd ../..

(scancode-toolkit) C:\Users\thoma\git\scancode-toolkit>scancode --help
========================================================================
ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
The following plugin(s) are referenced and cannot be loaded/imported:
No module named scancode_dwarfdump
========================================================================
Traceback (most recent call last):
  File "C:\Users\thoma\git\scancode-toolkit\Scripts\scancode-script.py", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "C:\Users\thoma\git\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\thoma\git\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Users\thoma\git\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Users\thoma\git\scancode-toolkit\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\thoma\git\scancode-toolkit\src\scancode\cli.py", line 228, in <module>
    raise e
ImportError: No module named scancode_dwarfdump

(scancode-toolkit) C:\Users\thoma\git\scancode-toolkit>
```

**Comment by linexb** [comment]
Fixed and verified by Chin-Yeung.

**Comment by linexb** [comment]
The fix is verified and merged into develop branch now. I will close the ticket now. Please reopen if needed.
