### ISSUE TITLE
Errors scanning log4j 

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#1773]
Using the latest develop branch, as of 2019-10-18, on Mac OS 10.14.5, I ran a scan of `apache-log4j-2.12.1-src` and received the messages shown below.   Scan results attached. 
[apache-log4j-2.12.1-src-scan.json.zip](https://github.com/nexB/scancode-toolkit/files/3745657/apache-log4j-2.12.1-src-scan.json.zip)

```
./scancode -clip --consolidate -n 4 --max-in-memory 0 {{path}}/apache-log4j-2.12.1-src/ --json-pp {{path}}/apache-log4j-2.12.1-src-scan.json
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights, packages with 4 process(es)...
[####################] 2960                                                                              
ERROR: failed to run post-scan plugin: consolidate:
Traceback (most recent call last):
  File "/Users/dclark1330/scancode-toolkit-develop/src/scancode/cli.py", line 1040, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/dclark1330/scancode-toolkit-develop/src/scancode/plugin_consolidate.py", line 207, in process_codebase
    consolidated_packages.append(c.to_dict())
  File "/Users/dclark1330/scancode-toolkit-develop/src/scancode/plugin_consolidate.py", line 125, in to_dict
    package = self.package.to_dict()
  File "/Users/dclark1330/scancode-toolkit-develop/src/packagedcode/models.py", line 302, in to_dict
    mapping['repository_download_url'] = self.repository_download_url()
  File "/Users/dclark1330/scancode-toolkit-develop/src/packagedcode/maven.py", line 121, in repository_download_url
    extension=qualifiers.get('type') or 'jar',
AttributeError: 'unicode' object has no attribute 'get'

Scanning done.
Some files failed to scan properly:
ERROR: failed to run post-scan plugin: consolidate:
Traceback (most recent call last):
  File "/Users/dclark1330/scancode-toolkit-develop/src/scancode/cli.py", line 1040, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/dclark1330/scancode-toolkit-develop/src/scancode/plugin_consolidate.py", line 207, in process_codebase
    consolidated_packages.append(c.to_dict())
  File "/Users/dclark1330/scancode-toolkit-develop/src/scancode/plugin_consolidate.py", line 125, in to_dict
    package = self.package.to_dict()
  File "/Users/dclark1330/scancode-toolkit-develop/src/packagedcode/models.py", line 302, in to_dict
    mapping['repository_download_url'] = self.repository_download_url()
  File "/Users/dclark1330/scancode-toolkit-develop/src/packagedcode/maven.py", line 121, in repository_download_url
    extension=qualifiers.get('type') or 'jar',
AttributeError: 'unicode' object has no attribute 'get'
Summary:        info, licenses, copyrights, packages with 4 process(es)
Errors count:   1
Scan Speed:     7.71 files/sec. 52.50 KB/sec.
Initial counts: 4004 resource(s): 2960 file(s) and 1044 directorie(s) 
Final counts:   4004 resource(s): 2960 file(s) and 1044 directorie(s) for 19.68 MB
Timings:
  scan_start: 2019-10-18T205120.154837
  scan_end:   2019-10-18T205753.938271
  setup_scan:licenses: 3.99s
  setup: 3.99s
  inventory: 1.19s
  scan:packages: 0.64s
  scan: 383.94s
  post-scan:consolidate: 1.83s
  post-scan: 1.83s
  output:json-pp: 3.01s
  output: 3.01s
  total: 397.43s
Removing temporary files...done.
```

**Comment by JonoYang** [comment]
@DennisClark Thanks for the ticket. I've narrowed down the problem to https://github.com/nexB/scancode-toolkit/commit/0bf0c7082d5ee6c99c7cd8c197e213ea5ff5080f#diff-9feddae6239d49e50571ae6742c91612L296, where we jump the gun and modify the POM qualifiers before the other attributes that we generate from the POM can use the qualifier data

**Comment by JonoYang** [comment]
This has been fixed in develop.
