### ISSUE TITLE
MemoryError even trying to scan a empty txt file - ubuntu

### ISSUE THREAD

**Issue by nilihz** [nexB/scancode-toolkit#1809]
Hi i hit MemoryError even scanning a empty .txt file. 

OS: ubuntu linux
scancode version 2.2.1
>wget https://github.com/nexB/scancode-toolkit/releases/download/v2.2.1/scancode-toolkit-2.2.1.zip
>unzip

 ubuntu@ip-172-xx-xx-xx:~/scancode-toolkit-2.2.1$ ./scancode -f json ./empty.txt > result.json
Scanning files for: licenses, copyrights, packages with 1 process(es)...
Building license detection index...Traceback (most recent call last):
  File "/home/ubuntu/scancode-toolkit-2.2.1/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/home/ubuntu/scancode-toolkit-2.2.1/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/scancode-toolkit-2.2.1/src/scancode/utils.py", line 74, in main
    standalone_mode=standalone_mode, **extra)
  File "/home/ubuntu/scancode-toolkit-2.2.1/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/scancode-toolkit-2.2.1/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/scancode-toolkit-2.2.1/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/scancode-toolkit-2.2.1/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/scancode-toolkit-2.2.1/src/scancode/cli.py", line 490, in scancode
    pre_scan_plugins=pre_scan_plugins)
  File "/home/ubuntu/scancode-toolkit-2.2.1/src/scancode/cli.py", line 572, in scan
    get_index(False)
  File "/home/ubuntu/scancode-toolkit-2.2.1/src/licensedcode/cache.py", line 188, in get_index
    _LICENSES_INDEX = get_or_build_index_through_cache()
  File "/home/ubuntu/scancode-toolkit-2.2.1/src/licensedcode/cache.py", line 148, in get_or_build_index_through_cache
    ifc.write(idx.dumps())
  File "/home/ubuntu/scancode-toolkit-2.2.1/src/licensedcode/index.py", line 653, in dumps
    return pickle.dumps(self, protocol=cPickle.HIGHEST_PROTOCOL)
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/usr/lib/python2.7/pickle.py", line 639, in _batch_appends
    save(x)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
MemoryError

**Comment by pombredanne** [comment]
@nilihz sorry for that! 
How much memory do you have on this machine? We have  some minimum requirements and the first run creates the license detection index which likely uses  a tad more memory too.
Also ScanCode 2.2.1 is a very old version.... could you try instead the latest 3.1.1 https://github.com/nexB/scancode-toolkit/releases/tag/v3.1.1 ?

**Comment by nilihz** [comment]
> @nilihz sorry for that!
> How much memory do you have on this machine? We have some minimum requirements and the first run creates the license detection index which likely uses a tad more memory too.
> Also ScanCode 2.2.1 is a very old version.... could you try instead the latest 3.1.1 https://github.com/nexB/scancode-toolkit/releases/tag/v3.1.1 ?

v3.1.1 works! Thanks!
I was running AWS EC2 with free tier 1GB ram. Ubuntu v18 might be the problem. But anyway, v3.1.1 works.
