### ISSUE TITLE
Consolidation plugin crashes

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1891]
I was scanning a codebase using the consolidation plugin and the following error occured:

```
ERROR: failed to run post-scan plugin: consolidate:
Traceback (most recent call last):
  File "/home/jyang/tools/scancode-toolkit/src/scancode/cli.py", line 1044, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/home/jyang/tools/scancode-toolkit/src/summarycode/plugin_consolidate.py", line 183, in process_codebase
    consolidations.extend(get_holders_consolidated_components(codebase))
  File "/home/jyang/tools/scancode-toolkit/src/summarycode/plugin_consolidate.py", line 400, in get_holders_consolidated_components
    for c in create_consolidated_components(ancestor, codebase, holder_key):
  File "/home/jyang/tools/scancode-toolkit/src/summarycode/plugin_consolidate.py", line 414, in create_consolidated_components
    if not (normalized_holder.key == holder_key):
AttributeError: 'collections.OrderedDict' object has no attribute 'key'
```

**Comment by JonoYang** [comment]
This is happening under Python 3

**Comment by JonoYang** [comment]
And I can't seem to reproduce this locally

**Comment by pombredanne** [comment]
>      if not (normalized_holder.key == holder_key):
> AttributeError: 'collections.OrderedDict' object has no attribute 'key'

See https://github.com/nexB/scancode-toolkit/blob/16377111febfaef2fd0806200a43cd9f239f7d0a/src/summarycode/plugin_consolidate.py#L413 does not look right for sure:

Eventually the original holder was a Text object with a key attribute BEFORE it was serialized to JSON https://github.com/nexB/scancode-toolkit/blob/16377111febfaef2fd0806200a43cd9f239f7d0a/src/summarycode/copyright_summary.py#L145

When you process this here, I think this is no longer an object but a mapping instead.
For sanity you should IMHO ensure that you always serialize to JSON the Text object otherwise it may be an object if you codebase is all in memory or may be serialized if the extra_data and resource data are no longer cached but end up on disk.
