### ISSUE TITLE
TypeError when attempting to run an installed plugin in python3

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1940]
I am creating a plugin that runs fine under Python 2, but when I try to run it in Python 3, I get this error:

```
$ scancode --fingerprint hailstorm --fingerprint binstring README.rst --json-pp -
Removing temporary files...done.
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try 'scancode --help' for help on options and arguments.

Error: Invalid value: Failed to load plugin: post_scan:directory-fingerprint:
Traceback (most recent call last):
  File "/home/jono/nexb/src/scancode-toolkit/src/scancode/cli.py", line 680, in run_scan
    raise te
  File "/home/jono/nexb/src/scancode-toolkit/src/scancode/cli.py", line 677, in run_scan
    is_enabled = plugin.is_enabled(**requested_options)
TypeError: is_enabled() missing 1 required positional argument: 'directory_fingerprint'
```

Looking at https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode/cli.py#L679, there is a Try/Except that checks the error messages:
```
                        if not 'takes exactly' in str(te):
                            raise te
```
I have a hunch the TypeError error message was changed between Python 2 and 3. A fix would be to add `'required positional argument'` or `'missing'` to the check.

**Comment by JonoYang** [comment]
The problem is related to my plugin, where I forgot to set the `option` attribute, so ScanCode did not register the plugin.
