### ISSUE TITLE
VirtualCodebase is showing error results when files are having the "fingerprint" attribute in it

### ISSUE THREAD

**Issue by Pratikrocks** [nexB/scancode-toolkit#1990]
### Description

Hello all,
When I was scanning a json file using the scancode ,I was receiving few errors.
This is the [json file](https://drive.google.com/open?id=1lY0wctipt5YUxE10lJxq7pHnE5h78LTp) which I was testing 
The following is the errors I received
```
Setup plugins...
Collect file inventory...
Removing temporary files...done.
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try 'scancode --help' for help on options and arguments.

Error: Invalid value: ERROR: failed to collect codebase at: 'scan_1_file_moved_new.json'
Traceback (most recent call last):
  File "/home/pratik/scancode-toolkit/src/scancode/cli.py", line 871, in run_scan
    max_in_memory=max_in_memory
  File "/home/pratik/scancode-toolkit/src/scancode/resource.py", line 1409, in __init__
    self._populate(scan_data)
  File "/home/pratik/scancode-toolkit/src/scancode/resource.py", line 1620, in _populate
    resource = self._create_resource(name, parent, is_file, path, resource_data)
  File "/home/pratik/scancode-toolkit/src/scancode/resource.py", line 528, in _create_resource
    **resource_data
TypeError: __init__() got an unexpected keyword argument 'fingerprint'


```
This error is because of the presence of the "fingerprint" attribute in the files.

### System configuration
Ubuntu 18.04 ,Python3.6.9 64 bit

* What OS are you running on? (Windows/MacOS/Linux) Linux
* What version of scancode-toolkit was used to generate the scan file?3.1.2
* What installation method was used to install/run scancode? (pip/source download/other)source download

**Comment by Pratikrocks** [comment]
@pombredanne @majurg if this is a valid issue, can I go for it?
