### ISSUE TITLE
Copyright 

### ISSUE THREAD

**Issue by nelullc** [nexB/scancode-toolkit#2033]
Running Linux

I have tried with both ScanCode v3.0.2 and V3.0.0. Tried install via pip and downloading / running directly. 

Even the 'sample' directory used in the examples, throws this error 'if' copyright scan is enabled.

Error occurs for every file it scans

` SyntaxError: invalid syntax
  Path: rollo-backend-api-dev/api-admin/src/main/java/com/rollo/backend/admin/job/usps/UspsAdjustmentProcessor.java
  ERROR: for scanner: copyrights:
  ERROR: Unknown error:
  Traceback (most recent call last):
    File "/home/kf982s/Downloads/venv-scancode-py2/lib/python2.7/site-packages/scancode/interrupt.py", line 91, in interruptible
      return NO_ERROR, func(*(args or ()), **(kwargs or {}))
    File "/home/kf982s/Downloads/venv-scancode-py2/lib/python2.7/site-packages/scancode/api.py", line 59, in get_copyrights
      for dtype, value, start, end in detect_copyrights(location):
    File "/home/kf982s/Downloads/venv-scancode-py2/lib/python2.7/site-packages/cluecode/copyrights.py", line 87, in detect_copyrights
      detector = CopyrightDetector()
    File "/home/kf982s/Downloads/venv-scancode-py2/lib/python2.7/site-packages/cluecode/copyrights.py", line 1646, in __init__
      from nltk import RegexpTagger
    File "/home/kf982s/Downloads/venv-scancode-py2/lib/python2.7/site-packages/nltk/__init__.py", line 128, in <module>
      from nltk.collocations import *
    File "/home/kf982s/Downloads/venv-scancode-py2/lib/python2.7/site-packages/nltk/collocations.py", line 35, in <module>
      from nltk.probability import FreqDist
    File "/home/kf982s/Downloads/venv-scancode-py2/lib/python2.7/site-packages/nltk/probability.py", line 333
      print("%*s" % (width, samples[i]), end=" ")`

No issues with license scan, email scan, or anything else.

**Comment by pombredanne** [comment]
@nelullc Do not close this if this is still an issue! Or did you figure out what the issue was?

**Comment by nelullc** [comment]
@pombredanne was not able to resolve the issue.

**Comment by pombredanne** [comment]
Do you mind trying the latest of the develop branch at https://github.com/nexB/scancode-toolkit/archive/develop.zip ?
Thanks!

**Comment by pombredanne** [comment]
@nelullc I am closing this for now, as we cannot do anything about this short of having more details. Feel free to reopen as needed.
