### ISSUE TITLE
Error in version 3.0, everything is normal in version 2.9.9

### ISSUE THREAD

**Issue by 00032118** [nexB/scancode-toolkit#2049]
[root@localhost scancode-toolkit-3.0.0]# ./scancode --help
Traceback (most recent call last):
  File "/home/hf/scancode-toolkit-3.0.0/bin/scancode", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "/home/hf/scancode-toolkit-3.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/hf/scancode-toolkit-3.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/home/hf/scancode-toolkit-3.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/hf/scancode-toolkit-3.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/hf/scancode-toolkit-3.0.0/src/scancode/cli.py", line 206, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/home/hf/scancode-toolkit-3.0.0/src/plugincode/__init__.py", line 190, in load_plugins
    mgr_setup = manager.setup()
  File "/home/hf/scancode-toolkit-3.0.0/src/plugincode/__init__.py", line 217, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/home/hf/scancode-toolkit-3.0.0/lib/python2.7/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/hf/scancode-toolkit-3.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/hf/scancode-toolkit-3.0.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/hf/scancode-toolkit-3.0.0/src/packagedcode/__init__.py", line 37, in <module>
    from packagedcode import rubygems
  File "/home/hf/scancode-toolkit-3.0.0/src/packagedcode/rubygems.py", line 40, in <module>
    from extractcode import archive
  File "/home/hf/scancode-toolkit-3.0.0/src/extractcode/archive.py", line 51, in <module>
    from extractcode import libarchive2
  File "/home/hf/scancode-toolkit-3.0.0/src/extractcode/libarchive2.py", line 114, in <module>
    libarchive = load_lib()
  File "/home/hf/scancode-toolkit-3.0.0/src/extractcode/libarchive2.py", line 104, in load_lib
    return command.load_shared_library(dll, libdir)
  File "/home/hf/scancode-toolkit-3.0.0/src/commoncode/command.py", line 222, in load_shared_library
    lib = ctypes.CDLL(dll_path)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbz2.so.1.0: cannot open shared object file: No such file or directory

**Comment by 00032118** [comment]
[root@localhost scancode-toolkit-3.0.0]# sudo yum install python3.6-devel zlib bzip2-libs xz-libs libxml2-devel libxslt-devel
Loaded plugins: fastestmirror, langpacks
Repository base is listed more than once in the configuration
Repository epel is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * centos-sclo-rh: mirrors.aliyun.com
 * centos-sclo-sclo: mirrors.163.com
 * epel: mirrors.bfsu.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.163.com
No package python3.6-devel available.
Package zlib-1.2.7-18.el7.x86_64 already installed and latest version
Package bzip2-libs-1.0.6-13.el7.x86_64 already installed and latest version
Package xz-libs-5.2.2-1.el7.x86_64 already installed and latest version
Package libxml2-devel-2.9.1-6.el7.4.x86_64 already installed and latest version
Package libxslt-devel-1.1.28-5.el7.x86_64 already installed and latest version
Nothing to do

**Comment by 00032118** [comment]
bzip2-libs  has Already installed, libbz2.so.1.0  Does not exist, what is it

**Comment by pombredanne** [comment]
@00032118 this is a known bug on Fedora and RPM-based distros for which there is a workaround (and should go away in the next version): #443 

The solution thanks to @akaihola is to: 
`sudo ln -s /usr/lib64/libbz2.so.1 /usr/lib64/libbz2.so.1.0`
