### ISSUE TITLE
Pop from an empty deque, 100 processes option

### ISSUE THREAD

**Issue by sebassdc** [nexB/scancode-toolkit#2106]
### Description

I'm getting this error, the execution stops and nothing else.

```
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 720, in next
  item = self._items.popleft()
IndexError: pop from an empty deque
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 726, in next
  item = self._items.popleft()
IndexError: pop from an empty deque
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/app/scancode-toolkit/bin/scancode", line 11, in <module>
  load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
 File "/app/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  return self.main(*args, **kwargs)
 File "/app/scancode-toolkit/src/scancode/utils.py", line 70, in main
  standalone_mode=standalone_mode, **extra)
 File "/app/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 697, in main
  rv = self.invoke(ctx)
 File "/app/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  return ctx.invoke(self.callback, **ctx.params)
 File "/app/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  return callback(*args, **kwargs)
 File "/app/scancode-toolkit/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
  return f(get_current_context(), *args, **kwargs)
 File "/app/scancode-toolkit/src/scancode/cli.py", line 519, in scancode
  *args, **kwargs)
 File "/app/scancode-toolkit/src/scancode/cli.py", line 914, in run_scan
  quiet=quiet, verbose=verbose, kwargs=requested_options, echo_func=echo_func,
 File "/app/scancode-toolkit/src/scancode/cli.py", line 1105, in run_scanners
  with_timing=timing, progress_manager=progress_manager)
 File "/app/scancode-toolkit/src/scancode/cli.py", line 1199, in scan_codebase
  location, rid, scan_errors, scan_time, scan_result, scan_timings = next(scans)
 File "/app/scancode-toolkit/lib/python3.6/site-packages/click/_termui_impl.py", line 259, in next
  rv = next(self.iter)
 File "/app/scancode-toolkit/src/scancode/pool.py", line 48, in wrap
  return func(self, timeout=timeout or 3600)
 File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 730, in next
  raise TimeoutError
multiprocessing.context.TimeoutError
/app/scancode-toolkit/scancode -clpi -n 100 --json-pp /app/output.json /app/workdir: b''
Error: None
````

### How To Reproduce

```
scancode -clpi -n 100 --json-pp /app/output.json /app/source_code
```

### System configuration

* Running on a python:3.6 docker image on an ec2 instance with 16 CPUs 150 GB SSD y 200 EBS volume, 16GB of ram.
* We build from the source from the develop branch on every run.

**Comment by pombredanne** [comment]
@sebassdc running a 100-processes scancode  scan with (only) 16 CPUs and 16GB is likely to be a problem.
The rule of thumb would be:
1. run at most that many processes (number of CPU threads -1) as in general more will not yield better perf as this will already saturate the CPUs nicely
2. provision roughly 1GB or RAM per process

So looking at AWS candy store, that would mean likely something like:
- c6g.16xlarge	64 vcpu	128GB ~ $2.176 per Hour ~ $17K/year :]
- c5.24xlarge	96 vcpu	192GB ~ $4.08 per Hour ~ $35K/year :]
which are rather pricey machines!

Can you explain what you are trying to achieve?

**Comment by pombredanne** [comment]
@sebassdc  can you tell which Python version you run exactly?
It could be a bug https://bugs.python.org/issue35629
Also open a python and run:
```
import multiprocessing
tuple(multiprocessing.Pool(4).imap(print, (1, 2, 3)))

```
Does this hangs?

**Comment by sebassdc** [comment]
@pombredanne Sorry for not following up this.
Yes the issue could be related to python!. We were using python 3.6 on a docker image on an EC2 Instance type: m5n.8xlarge.

Right now we are using scancode on 2.7 without issues on the same machine with the same parameters and it works perfectly!
