### ISSUE TITLE
AttributeError raised for some projects

### ISSUE THREAD

**Issue by fb33** [nexB/scancode-toolkit#2205]
### Description

Hello

I run ScanCode (3.0.2) through ORT in docker.
I've got that king of error :

```
20:34:09  18:31:10.539 [main] ERROR org.ossreviewtoolkit.scanner.LocalScanner - Could not scan 'Maven:org.jetbrains.kotlin:kotlin-reflect:1.4.0' (68/1712): ScanException: Running '/usr/local/bin/scancode --copyright --license --info --strip-root --timeout 300 --ignore *.ort.yml --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --ignore **/test/** --ignore **/tests/** --ignore **/__tests__/** --ignore **/qunit/** --ignore spring-boot-tests/** --ignore doc/** --ignore docs/** --ignore documentation/** --ignore documentations/** --ignore demo/** --ignore **/example/** --ignore **/examples/** --ignore **/sample/** --ignore **/samples/** --ignore changelog.txt --processes 3 /project/reports/scanner/downloads/Maven/org.jetbrains.kotlin/kotlin-reflect/1.4.0 --json-pp /project/reports/scanner/native-scan-results/Maven/org.jetbrains.kotlin/kotlin-reflect/1.4.0/scan-results_ScanCode.json' in '/' failed with exit code 1:
20:34:09  Setup plugins...
20:34:09  Collect file inventory...
20:34:09  ERROR: failed to run pre-scan plugin: ignore:
20:34:09  Traceback (most recent call last):
20:34:09    File "/usr/local/scancode-toolkit-3.0.2/src/scancode/cli.py", line 870, in run_codebase_plugins
20:34:09      plugin.process_codebase(codebase, **kwargs)
20:34:09    File "/usr/local/scancode-toolkit-3.0.2/src/scancode/plugin_ignore.py", line 85, in process_codebase
20:34:09      remove_resource(resource)
20:34:09    File "/usr/local/scancode-toolkit-3.0.2/src/scancode/resource.py", line 753, in remove_resource
20:34:09      for descendant in resource.walk(self, topdown=False):
20:34:09    File "/usr/local/scancode-toolkit-3.0.2/src/scancode/resource.py", line 1117, in walk
20:34:09      for child in self.children(codebase):
20:34:09    File "/usr/local/scancode-toolkit-3.0.2/src/scancode/resource.py", line 1141, in children
20:34:09      return sorted((get_resource(rid) for rid in self.children_rids), key=_sorter)
20:34:09    File "/usr/local/scancode-toolkit-3.0.2/src/scancode/resource.py", line 1139, in <lambda>
20:34:09      _sorter = lambda r: (r.has_children(), r.name.lower(), r.name)
20:34:09  AttributeError: 'NoneType' object has no attribute 'has_children'
```

it occurs on several projects.

Is it a configuration problem from my part or a scancode issue ?

### How To Reproduce

Take a maven project with that dependency
```
    <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-reflect</artifactId>
        <version>1.4.0</version>
    </dependency>
```

Here the scanCode command line options :
`--copyright --license --info --strip-root --timeout 300 --ignore *.ort.yml --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --ignore **/test/** --ignore **/tests/** --ignore **/__tests__/** --ignore **/qunit/** --ignore spring-boot-tests/** --ignore doc/** --ignore docs/** --ignore documentation/** --ignore documentations/** --ignore demo/** --ignore **/example/** --ignore **/examples/** --ignore **/sample/** --ignore **/samples/** --ignore changelog.txt --processes 3`

### System configuration

* What OS are you running on? Linux (docker)
* What version of scancode-toolkit was used to generate the scan file? 3.0.2
* What installation method was used to install/run scancode? install by ORT

**Comment by pombredanne** [comment]
Thank you for the report!
Can you try to run the same commend using a check of the `develop` branch of scancode-toolkit?
This bug has likely been fixed there already per https://github.com/nexB/scancode-toolkit/issues/1362


It worked for me:
```
$ mkdir kot
$ wget https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.4.0/kotlin-reflect-1.4.0-sources.jar
$ wget https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.4.0/kotlin-reflect-1.4.0.jar
$ mv *.jar kot
$ ./extractcode --verbose --shallow kot/
Extracting archives...
Extracting: kotlin-reflect-1.4.0-sources.jar
Extracting: kotlin-reflect-1.4.0.jar
Extracting done.
$ ./scancode --copyright --license --info --strip-root --timeout 300 \
  --ignore "*.ort.yml" --ignore HERE_NOTICE \
  --ignore META-INF/DEPENDENCIES --ignore "**/test/**" --ignore "**/tests/**" --ignore "**/__tests__/**" \
  --ignore "**/qunit/**" --ignore "spring-boot-tests/**" --ignore "doc/**" --ignore "docs/**" --ignore "documentation/**" \
  --ignore "documentations/**" --ignore "demo/**" --ignore "**/example/**" --ignore "**/examples/**" --ignore "**/sample/**" \
  --ignore "**/samples/**" --ignore changelog.txt \
  --processes 8 --json-pp kot.json kot/
```

**Comment by fb33** [comment]
Hello, 
I installed Scancode from branch develop
But when I ran scancode, I ve got a memory error:
```
λ \workspace\temp\scancode-toolkit\scancode.bat --copyright --license --info --strip-root --timeout 300 --ignore "*.ort.yml" --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --ignore "**/test
/**" --ignore "**/tests/**" --ignore "**/__tests__/**" --ignore "**/qunit/**" --ignore "spring-boot-tests/**" --ignore "doc/**" --ignore "docs/**" --ignore "documentation/**" --ignore "documenta
tions/**" --ignore "demo/**" --ignore "**/example/**" --ignore "**/examples/**" --ignore "**/sample/**" --ignore "**/samples/**" --ignore changelog.txt --processes 8 --json-pp kot.json kotlin-re
flect\                                                                                                                                                                                            
Setup plugins...                                                                                                                                                                                  
Removing temporary files...done.                                                                                                                                                                  
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...                                                                                                                                    
Try 'scancode --help' for help on options and arguments.                                                                                                                                          
                                                                                                                                                                                                  
Error: Invalid value: ERROR: failed to setup plugin: scan:licenses:                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                
  File "c:\workspace\temp\scancode-toolkit\src\scancode\cli.py", line 774, in run_scan                                                                                                            
    plugin.setup(**requested_options)                                                                                                                                                             
  File "c:\workspace\temp\scancode-toolkit\src\licensedcode\plugin_license.py", line 129, in setup                                                                                                
    get_index(return_value=False)                                                                                                                                                                 
  File "c:\workspace\temp\scancode-toolkit\src\licensedcode\cache.py", line 68, in get_index                                                                                                      
    _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency)                                                                                                                       
  File "c:\workspace\temp\scancode-toolkit\src\licensedcode\cache.py", line 253, in get_cached_index                                                                                              
    ifc.write(idx.dumps())                                                                                                                                                                        
  File "c:\workspace\temp\scancode-toolkit\src\licensedcode\index.py", line 995, in dumps                                                                                                         
    pickled = pickletools.optimize(pickled)                                                                                                                                                       
  File "D:\Python36-32\lib\pickletools.py", line 2333, in optimize                                                                                                                                
    pickler.framer.commit_frame()                                                                                                                                                                 
  File "D:\Python36-32\lib\pickle.py", line 209, in commit_frame                                                                                                                                  
    write(data)                                                                                                                                                                                   
MemoryError           
```

**Comment by pombredanne** [comment]
Thank you for the report. Do you have the download URL of the code you were scanning? 
Also is this consistently happening? And what are the CPU/RAM specs of your machine, which Windows version do you run and which exact Python version 3.6 do you run (and 32 or 64 bits?)?

**Comment by fb33** [comment]
Hello, 
Here are some details :
- OS : Windows10 Pro 64b 
- CPU : Intel Core i7 9850H 
- RAM : 32 Go 
- Python : 3.6.8 32b

**Comment by pombredanne** [comment]
> Should I switch to Python in 64b ?

The latest develop support Windows 64bits, so this is worth a try

**Comment by fb33** [comment]
With the 64b version, it works.
I still have some errors in stdout, but ScanCode ends its scan and generates the report.
Maybe the errors are due to windows and 256 max path file ?...
example of error :
```
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\workspace\\temp\\reports\\component-management\\scanner\\downloads\\Maven\\org.jetbrains.kotlin\\kotlin-reflect\\1.4.0\\libraries\\tools\\new-project-wizard\\resources\\org\\jetbrains\\kotlin\\tools\\projectWizard\\templates\\ios\\singleplatformProject\\appName\\Assets.xcassets'
ERROR: cannot populate codebase: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\workspace\\temp\\reports\\component-management\\scanner\\downloads\\Maven\\org.jetbrains.kotlin\\kotlin-reflect\\1.4.0\\libraries\\tools\\new-project-wizard\\resources\\org\\jetbrains\\kotlin\\tools\\projectWizard\\templates\\ios\\singleplatformProject\\appName\\Preview_Content'
Traceback (most recent call last):
  File "D:\Python36\lib\os.py", line 348, in walk
    scandir_it = scandir(top)
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\workspace\\temp\\reports\\component-management\\scanner\\downloads\\Maven\\org.jetbrains.kotlin\\kotlin-reflect\\1.4.0\\libraries\\tools\\new-project-wizard\\resources\\org\\jetbrains\\kotlin\\tools\\projectWizard\\templates\\ios\\singleplatformProject\\appName\\Preview_Content'
```
But my target is to have a scan in docker with ORT, so this is not a blocking issue.
Thanks for your help, now I ll wait an upgrade of ScanCode in ORT :-)

**Comment by pombredanne** [comment]
> With the 64b version, it works.

Excellent! the limitations on 32bits are around 2GB which are fast used.

>I still have some errors in stdout, but ScanCode ends its scan and generates the report.
> Maybe the errors are due to windows and 256 max path file ?...

Yes this error looks like some Windows maxpath issue, which should have been fixed in https://github.com/nexB/scancode-toolkit/issues/749

```
>>> a='C:\\workspace\\temp\\reports\\component-management\\scanner\\downloads\\Maven\\org.jetbrains.kotlin\\kotlin-reflect\\1.4.0\\libraries\\tools\\new-project-wizard\\resources\\org\\jetbrains\\kotlin\\tools\\projectWizard\\templates\\ios\\singleplatformProject\\appName\\Preview_Content'
>>> len(a)
258
```

The max was  260 but should no longer be an issue with the latest code... hum :|

Did you try with the latest of the develop branch?

**Comment by fb33** [comment]
Hello,
Yes, I took the latest commit (138abda96) on develop branch.
But windows execution is not in my target, I use scancode through ORT via Docker.
Thanks
