### ISSUE TITLE
Windows first run fails with Unsupported OS/platform 'win64'

### ISSUE THREAD

**Issue by dbrennan** [nexB/scancode-toolkit#2223]
### Description

Installed Python 3.6 and put on my path. Ran scancode the first time and it errors out.

### How To Reproduce

Unzip and run scancode:

```
* Configuring ScanCode for first use...
Python 3.6.8
C:\Users\daveb\AppData\Local\Programs\Python\Python36-32\python.exe
Junction created for C:\Users\daveb\Downloads\scancode-toolkit-3.1.1\bin <<===>> C:\Users\daveb\Downloads\scancode-toolkit-3.1.1\Scripts
Unsupported OS/platform 'win64'.
See https://github.com/nexB/scancode-toolkit/ for supported OS/platforms.
Enter a ticket https://github.com/nexB/scancode-toolkit/issues asking for support of your OS/platform combo.
Traceback (most recent call last):
  File "C:\Users\daveb\Downloads\scancode-toolkit-3.1.1\etc\configure.py", line 574, in <module>
    run_scripts(configs, root_dir, configured_python, quiet=quiet)
  File "C:\Users\daveb\Downloads\scancode-toolkit-3.1.1\etc\configure.py", line 322, in run_scripts
    call(cmd, root_dir)
  File "C:\Users\daveb\Downloads\scancode-toolkit-3.1.1\etc\configure.py", line 137, in call
    subprocess.check_call(cmd, shell=True, env=dict(os.environ), cwd=root_dir)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Users\daveb\Downloads\scancode-toolkit-3.1.1\bin\python.exe" "C:\Users\daveb\Downloads\scancode-toolkit-3.1.1\etc\conf\base.py"' returned non-zero exit status 1
```

### System configuration

Windows version 10 19042.421
Scancode 3.1.1
Installed with unzip & running scancode from cmd.exe

**Comment by pombredanne** [comment]
@dbrennan Thank you for the report.
Do you mind to try instead the newest release candidate? That's the first one that officially support Windows 64 and Python 3.6 64 

See https://github.com/nexB/scancode-toolkit/releases/tag/v3.2.0rc1

**Comment by soimsoim** [comment]
Dear @pombredanne ,
I installed scancode by using pip install scancode-toolkit==3.2.0.
And it works well on ubuntu or mac.
However if I try to run scancode on windows, it return below message.

`File "d:\dev_src\git\.venv\lib\site-packages\typecode\magic2.py", line 106, in load_lib
return command.load_shared_library(dll, libdir)
File "d:\dev_src\git\.venv\lib\site-packages\commoncode\command.py", line 263, in load_shared_library
lib = ctypes.CDLL(dll_path)
File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 is not a valid Win32 application`

**Comment by pombredanne** [comment]
@soimsoim thank you ++ for the report. This needs to be fixed ASAP!
Did the installation work correctly, no special message?
Can you confirm you ran the pip install inside a virtualenv?
Also do you mind trying `pip install scancode-toolkit==3.2.1rc2` too? (this is a new release candidate, though it should be the same.

**Comment by soimsoim** [comment]
@pombredanne 
Yes I have also installed 3.2.1rc2, but the result is the same.
This error occurs when loading .venv\lib\site-packages\typecode_libmagic\lib\libmagic.dll file.

**Comment by pombredanne** [comment]
The latest version 21.xx now fully support Window 64 (and really only support 64 with 32 bits support dropped).... Could you check? Thanks!

**Comment by soimsoim** [comment]
**Scancode 21.2.9 can be run on Windows too!**

- Test result : 
I need to install typecode-libmagic additionally, but Scancode is installed in Windows and the execution result file is also generated.
- Test environment: Windows 10, 64bits / Python 3.8.6 / scancode-toolkit 21.2.9
- Test output:

1. pip install scancode-toolkit
2. The following error message occurs when executing Scancode.
`Exception: CRITICAL: libmagic DLL and is magic database are not installed. Unable to continue: you need to install a valid typecode-libmagic plugin with a valid and proper libmagic and magic DB available.`
3. pip install typecode-libmagic
4. When Scancode is executed again, it operates without an error message and a result file is created.

**Comment by pombredanne** [comment]
@soimsoim Thank you ++ for the tests!
can you tests too:
`pip install scancode-toolkit[full]` rather than the plain `pip install scancode-toolkit` ?

**Comment by soimkim** [comment]
@pombredanne 
Even if I install with **pip install scancode-toolkit[full]**, typecode-libmagic is not installed and the same error occurs.

**Comment by pombredanne** [comment]
@soimkim thank you. I need to make more tests :|
