### ISSUE TITLE
NPM dist_mapper fails to decode integrity value properly

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#2256]
While the `dist` value is not usually present in NPM packages in the wild, it does show up in some situations. Unfortunately (probably since we moved to python3), this code does not work properly when the `integrity` value is a string. 

To reproduce (using the docstring example from https://github.com/nexB/scancode-toolkit/blob/c3c92ff121632ea5db835f1c460c7d483a91a5d6/src/packagedcode/npm.py#L567):
```
(scancode-toolkit) [sesser@nexb-workstation ~/Code/nexB/scancode-toolkit] python
Python 3.6.11 (default, Jul 17 2020, 15:21:46)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> dist = {"integrity": "sha512-VmqXvL6aSOb+rmswek7prvdFKsFbfMshcRRi07SdFyDqgG6uXsP276NkPTcrD0DiwVQ8rfnCUP8S90x0OD+2gQ==", "shasum": "a124386bce4a90506f28ad4b1d1a804a17baaf32", "dnl_url": "http://registry.npmjs.org/npm/-/npm-2.13.5.tgz"}
>>> from packagedcode.npm import dist_mapper                                                                                               
>>> dist_mapper(dist, None)                                                                                                                
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sesser/Code/nexB/scancode-toolkit/src/packagedcode/npm.py", line 580, in dist_mapper
    sha512 = b64value.decode('base64').encode('hex')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by majurg** [comment]
This is fixed by #2261, closing.
