### ISSUE TITLE
Scan failure for a bare SPDX license identifier without license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2289]
A file with only `SPDX-License-Identifier ` will fail to scan:
```
ERROR: for scanner: licenses:
ERROR: Unknown error:
Traceback (most recent call last):
  File "/tmp/scancode-toolkit/src/scancode/interrupt.py", line 92, in interruptible
    return NO_ERROR, func(*(args or ()), **(kwargs or {}))
  File "/tmp/scancode-toolkit/src/scancode/api.py", line 199, in get_licenses
    location=location, min_score=min_score, deadline=deadline, **kwargs)
  File "/tmp/scancode-toolkit/src/licensedcode/index.py", line 855, in match
    existing_matches=matches, deadline=deadline)
  File "/tmp/scancode-toolkit/src/licensedcode/index.py", line 587, in get_spdx_id_matches
    self, query_run, detectable_text)
  File "/tmp/scancode-toolkit/src/licensedcode/match_spdx_lid.py", line 100, in spdx_id_match
    expression_str = expression.render()
AttributeError: 'NoneType' object has no attribute 'render'
```

**Comment by AyanSinhaMahapatra** [comment]
This is fixed now, closing!
