### ISSUE TITLE
Python error(s) when scanning large numbers of artifacts in parallel

### ISSUE THREAD

**Issue by gsebast** [nexB/scancode-toolkit#2293]
### Description

Scanning a very large number of artifacts in parallel leads to the following Python error(s):
```
Setup plugins...
Collect file inventory...
Scan files for: licenses with 4 process(es)...
Removing temporary files...done.
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 720, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 726, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/venv-scancode/bin/scancode", line 8, in <module>
    sys.exit(scancode())
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/scancode/utils.py", line 70, in main
    standalone_mode=standalone_mode, **extra)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 530, in scancode
    *args, **kwargs)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 927, in run_scan
    quiet=quiet, verbose=verbose, kwargs=requested_options, echo_func=echo_func,
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 1118, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 1212, in scan_codebase
    location, rid, scan_errors, scan_time, scan_result, scan_timings = next(scans)
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/click/_termui_impl.py", line 127, in __next__
    return next(iter(self))
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/click/_termui_impl.py", line 315, in generator
    for rv in self.iter:
  File "/home/jenkins/venv-scancode/lib/python3.6/site-packages/scancode/pool.py", line 48, in wrap
    return func(self, timeout=timeout or 3600)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 730, in next
    raise TimeoutError
multiprocessing.context.TimeoutError
```

### How To Reproduce

The following command is used to execute a scan on a set of about 2500 JAR artifacts (~6GB):
```
scancode -l --timeout 21600 -n 4 --ignore '*.java' --ignore '*.scala' --ignore '*.class' \
  --ignore '*.js' --ignore '*.css' --ignore '*.gif' --ignore '*.jpg' --ignore '*.svg' \
  --ignore '*.R' --ignore '*.Rnw' --ignore '*.Rd' --ignore '*.Rmd' --ignore '*.sas' \
  --ignore '*.afm' --ignore '*.dat' --ignore '*.dll' --ignore '*.exe' --ignore '*.mo' \
  --ignore '*.pl' --ignore '*.pm' --ignore '*.res' --ignore '*.rds' --ignore '*.save' \
  --ignore '*.xls' --ignore '*.xsb' --csv us-oss-licenses.csv us.zip-extract
```

There is no other magic 

### System configuration

* Docker or AWS EC2 instance, 4 CPUs, 16GB Ram (even tried 32GB Ram on an EC2 instance)
* OS is always Ubuntu 18.04 with latest updates
* ScanCode Toolkit versions tried were **3.1.1** and **3.2.1rc2**
* Installation methods tried were **source download** and **pip**

### Additional info
* The exact same setups and command work fine with smaller JAR sets, e.g. less than 100 JARs and < 1GB
* No attempts were made to gauge at what number of JAR artifacts and/or data size the described behavior starts to occur as runs with larger sets take several hours to complete.

**Comment by pombredanne** [comment]
@gsebast Thank you for the detailed report.
Is there a way to get a sample of files that could help reproduce this?

**Comment by pombredanne** [comment]
> ### How To Reproduce
> 
> The following command is used to execute a scan on a set of about 2500 JAR artifacts (~6GB):
> 
> ```
> scancode -l --timeout 21600 -n 4 --ignore '*.java' --ignore '*.scala' --ignore '*.class' \
>   --ignore '*.js' --ignore '*.css' --ignore '*.gif' --ignore '*.jpg' --ignore '*.svg' \
>   --ignore '*.R' --ignore '*.Rnw' --ignore '*.Rd' --ignore '*.Rmd' --ignore '*.sas' \
>   --ignore '*.afm' --ignore '*.dat' --ignore '*.dll' --ignore '*.exe' --ignore '*.mo' \
>   --ignore '*.pl' --ignore '*.pm' --ignore '*.res' --ignore '*.rds' --ignore '*.save' \
>   --ignore '*.xls' --ignore '*.xsb' --csv us-oss-licenses.csv us.zip-extract
> ```

Just curious: you are scanning JARs but ignoring .java and .class files ... what do you expect to be scanned there then?
Also did you extract the JARs first?

**Comment by gsebast** [comment]
@pombredanne Thanks for your replies.

You can download representative sample via the following link:
https://update.knime.org/analytics-platform/4.2/org.knime.update.analytics-platform_4.2.2.zip

The only we thing we want to scan are what's in the _plugins_ folder of the archive. Everything else we delete before extraction and scanning.

Regarding your other questions. All the artifacts being scanned are essentially Eclipse plug-ins. They are unpacked using ```extractcode --shallow```. The ```--shallow``` option is used to keep the scan area manageable. Some plug-ins come packed with JARs and some even with JARs within JARs and so on. Extracting without the ```--shallow``` option produces millions of files and alone takes a couple of hours to complete (disk IO becomes a bottleneck I guess).
Ideally, plug-ins should explicitly state the license they are released under either via some sort of LICENSE file or within their MANIFEST.MF. And ScanCode does find all that information (and lots more). Of course their does not seem to be a standard and we have found license information in all sorts of files: _pom.xml_, _.properties_, _.html_, _.java_, _.scala_, _.class_, etc. If you then get contradicting license information for the same plug-in (sometime 10 or more licenses) then it gets really tricky trying to sort things out. But we are aware that we may not catch everything relevant right now. Just want to keep things simple to get started and gain experience.

**Comment by pombredanne** [comment]
@gsebast that's great as this give me enough to reproduce!
Have you tried using the `--package` option  instead? It tries to look for only things that are package manifests. Not sure it would cover all your bases but that's worth trying and would be easy to update as needed.

**Comment by gsebast** [comment]
@pombredanne No, I haven't tried the ```--package``` option. I'll do that to see what comes out of it. Thank you for the heads-up.

**Comment by pombredanne** [comment]
@gsebast can you tell which Python version you run exactly?
It could be a bug https://bugs.python.org/issue35629
Also open a python and run:
```
import multiprocessing
tuple(multiprocessing.Pool(4).imap(print, (1, 2, 3)))

```
Does this hangs?

**Comment by gsebast** [comment]
The Python version used is 3.6.9.

Running the given commands in a Python CLI does not cause any hang-ups.
