### ISSUE TITLE
Failure to run scan

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2309]
Originally reported at https://github.com/nexB/scancode-toolkit/issues/2286#issuecomment-719013200 by @66Ton99
----------------------
Have similar problem
```shell
scancode-toolkit git:(master) virtualenv -p /usr/bin/python3.6 venv-scancode
created virtual environment CPython3.6.10.final.0-64 in 203ms
  creator CPython3Posix(dest=/srv/src/scancode-toolkit/venv-scancode, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ton/.local/share/virtualenv)
    added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
➜  scancode-toolkit git:(master) source venv-scancode/bin/activate
(venv-scancode) ➜  scancode-toolkit git:(master) ./scancode --html opencv.html --copyright --package /srv/src/ofsc/opencv
Setup plugins...
Removing temporary files...done.
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try the 'scancode --help' option for help on options and arguments.

Error: Invalid value: ERROR: failed to setup plugin: scan:licenses:
Traceback (most recent call last):
  File "/srv/src/scancode-toolkit/src/scancode/cli.py", line 702, in run_scan
    plugin.setup(**requested_options)
  File "/srv/src/scancode-toolkit/src/licensedcode/plugin_license.py", line 130, in setup
    get_index(return_value=False)
  File "/srv/src/scancode-toolkit/src/licensedcode/cache.py", line 68, in get_index
    _LICENSES_BY_KEY_INDEX = get_cached_index(cache_dir, check_consistency)
  File "/srv/src/scancode-toolkit/src/licensedcode/cache.py", line 249, in get_cached_index
    idx = LicenseIndex(rules, _spdx_tokens=spdx_tokens)
  File "/srv/src/scancode-toolkit/src/licensedcode/index.py", line 245, in __init__
    rules, _legalese=_legalese, _spdx_tokens=_spdx_tokens)
  File "/srv/src/scancode-toolkit/src/licensedcode/index.py", line 533, in _add_rules
    raise AssertionError(msg)
AssertionError: Duplicate rules: 
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/rpsl-1.0_2.RULE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/rpsl-1.0_7.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/licenses/mpl-1.1.LICENSE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/mpl-1.1_28.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/licenses/liberation-font-exception.LICENSE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/liberation-font-exception_1.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/licenses/nosl-3.0.LICENSE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/nosl-3.0.SPDX.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/licenses/afl-2.1.LICENSE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/afl-2.1_2.RULE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/afl-2.1_6.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/lgpl-3.0.SPDX.RULE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/lgpl-3.0_23.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/cddl-1.0.SPDX.RULE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/cddl-1.0_9.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/licenses/cecill-1.1.LICENSE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/cecill-1.1.SPDX.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/afl-3.0.SPDX.RULE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/afl-3.0_6.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/licenses/cpal-1.0.LICENSE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/cpal-1.0.SPDX.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/rpsl-1.0.SPDX.RULE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/rpsl-1.0_1.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/licenses/npl-1.1.LICENSE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/npl-1.1_7.RULE

file:///srv/src/scancode-toolkit/src/licensedcode/data/licenses/osl-3.0.LICENSE
file:///srv/src/scancode-toolkit/src/licensedcode/data/rules/osl-3.0.SPDX.RULE

(venv-scancode) ➜  scancode-toolkit git:(master)
```

**Comment by pombredanne** [comment]
@66Ton99 
How did you install scancode? did you run a pip install? a configure?

And can you try this instead: Try to not create your own virtualenv and instead use the `./configure` script:

- make sure you have the latest from the `develop` git branch and that you are "clean" git status-wise.
- run `./configure --clean`
- run `./configure`

This creates a virtualenv in te current directory
You can activate with `source bin/activate` but the `scancode` root scripts handles this alright otherwise.

Then run your scancode command

**Comment by pombredanne** [comment]
I was not able to reproduce this. Closing for now.
