### ISSUE TITLE
Missing libmagic dependency

### ISSUE THREAD

**Issue by nishakm** [nexB/scancode-toolkit#2312]
### Description

When running scancode on Ubuntu 20.04 I get this error:
```
CRITICAL: libmagic DLL and is magic database are not installed. Unable to continue: you need to install a valid typecode-libmagic plugin with a valid and proper libmagic and magic DB available.
```
I've installed libmagic-dev but that doesn't seem to solve the problem. Typecode is also installed.

### How To Reproduce

```
$ scancode -ilpcu --quiet --timeout 300 --json - /home/nisha/.tern/temp/aa8da8ff8b09366138d1308ff9750dd995973e0526d54384fa05154b6f1cf5cd/contents
Traceback (most recent call last):
  File "/home/nisha/scancodeenv/bin/scancode", line 5, in <module>
    from scancode.cli import scancode
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/scancode/cli.py", line 144, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/plugincode/__init__.py", line 217, in load_plugins
    mgr_setup = manager.setup()
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/plugincode/__init__.py", line 241, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/summarycode/generated.py", line 40, in <module>
    import typecode.contenttype
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/typecode/__init__.py", line 27, in <module>
    from typecode.contenttype import get_type
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/typecode/contenttype.py", line 56, in <module>
    from typecode import magic2
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/typecode/magic2.py", line 226, in <module>
    libmagic = load_lib()
  File "/home/nisha/scancodeenv/lib/python3.8/site-packages/typecode/magic2.py", line 107, in load_lib
    raise Exception(
Exception: CRITICAL: libmagic DLL and is magic database are not installed. Unable to continue: you need to install a valid typecode-libmagic plugin with a valid and proper libmagic and magic DB available.
```

### System configuration

* Ubuntu 20.04 VM
* scancode-toolkit==3.2.3
* via pip install

**Comment by JonoYang** [comment]
Hi, @nishakm. The missing binary plugins are provided in `extras_require` (https://github.com/nexB/scancode-toolkit/blob/develop/setup.py#L217). Please specify the `full` extra_require option when installing scancode from pip: `pip install scancode-toolkit[full]`

**Comment by pombredanne** [comment]
@JonoYang good catch. Can you update the README and install docs?

**Comment by pombredanne** [comment]
@JonoYang actually a suggestion would be to use a typed Exception subclass and to capture it in ScanCode such that "Exception: CRITICAL: libmagic DLL and is magic database are not installed. Unable to continue: you need to install a valid typecode-libmagic plugin with a valid and proper libmagic and magic DB available." is enhanced with a message telling to install instead with `pip install scancode[full]`

**Comment by nishakm** [comment]
It works! Thanks!

**Comment by kaiivoschneider** [comment]
It doesn't work: "ERROR: Cannot install scancode-toolkit[full]==3.1.1, scancode-toolkit[full]==3.2.0 and scancode-toolkit[full]==3.2.3 because these package versions have conflicting dependencies."
