### ISSUE TITLE
missing typecode-libmagic dependency

### ISSUE THREAD

**Issue by alpianon** [nexB/scancode-toolkit#2324]
### Description

> Please leave a brief description of the bug or feature request:

missing dependency during installation (typecode-libmagic)

### How To Reproduce

> Tell us how to reproduce the issue. 

1. install scancode-toolkit with `pip` following the instructions in the docs
2. launch `scancode -h`
3. you get the following error:

```Traceback (most recent call last):
  File "/home/user/venv-scancode/bin/scancode", line 5, in <module>
    from scancode.cli import scancode
  File "/home/user/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 144, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/home/user/venv-scancode/lib/python3.6/site-packages/plugincode/__init__.py", line 217, in load_plugins
    mgr_setup = manager.setup()
  File "/home/user/venv-scancode/lib/python3.6/site-packages/plugincode/__init__.py", line 241, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/home/user/venv-scancode/lib/python3.6/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/user/venv-scancode/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/venv-scancode/lib/python3.6/site-packages/summarycode/generated.py", line 40, in <module>
    import typecode.contenttype
  File "/home/user/venv-scancode/lib/python3.6/site-packages/typecode/__init__.py", line 27, in <module>
    from typecode.contenttype import get_type
  File "/home/user/venv-scancode/lib/python3.6/site-packages/typecode/contenttype.py", line 56, in <module>
    from typecode import magic2
  File "/home/user/venv-scancode/lib/python3.6/site-packages/typecode/magic2.py", line 226, in <module>
    libmagic = load_lib()
  File "/home/user/venv-scancode/lib/python3.6/site-packages/typecode/magic2.py", line 108, in load_lib
    'CRITICAL: libmagic DLL and is magic database are not installed. '
Exception: CRITICAL: libmagic DLL and is magic database are not installed. Unable to continue: you need to install a valid typecode-libmagic plugin with a valid and proper libmagic and magic DB available.
```
4. to solve the issue, you have to run `pip install typecode-libmagic`

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 3.2.3
* What installation method was used to install/run scancode? pip

**Comment by pombredanne** [comment]
@alpianon Thank you for the report and sorry for this annoyance!
The doc should highlight that the correct installation is now `pip install scancode-toolkit[full]`

**Comment by JessieWu2020** [comment]
pip install typecode-libmagic
ERROR: Could not find a version that satisfies the requirement typecode-libmagic (from versions: none)
ERROR: No matching distribution found for typecode-libmagic

**Comment by AyanSinhaMahapatra** [comment]
@JessieWu2020 could you open a new issue with details of your installation and environment, what version of scancode you're using etc? I could run successfully `pip install typecode-libmagic` on ubuntu20.04, in an activated virtualenv after pip install, app archive install or source code checkout.

**Comment by robtaylor** [comment]
Ah, `typecode-libmagic` is not built for ARM MacOS.. If it had CI, i'd submit a patch...
