### ISSUE TITLE
Logic error in is_empty in src/cluecode/plugin_filter_clues.py 

### ISSUE THREAD

**Issue by VanL** [nexB/scancode-toolkit#2339]
### Description

The logic in is_empty is reversed - the function tests for *emptiness*, so a falsey "clues" object should actually return True (it *is* empty). 

This prevents an error that manifests at line 241, where attributes of the ignorables object are used, but the object is None. The reversed logic test actually fails at 238, where the function should return (there are no ignorables), but the default None prevents the "and" operator from returning True, so the function continues.

The result is that when "ignorables" is interrogated for the email attribute, it fails with an AttributeError:

ERROR: failed to run post-scan plugin: filter-clues:
Traceback (most recent call last):
  File "/home/vanl/.local/pipx/venvs/scancode-toolkit/lib/python3.8/site-packages/scancode/cli.py", line 986, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/home/vanl/.local/pipx/venvs/scancode-toolkit/lib/python3.8/site-packages/cluecode/plugin_filter_clues.py", line 90, in process_codebase
    filtered = filter_ignorable_resource_clues(resource, rules_by_id)
  File "/home/vanl/.local/pipx/venvs/scancode-toolkit/lib/python3.8/site-packages/cluecode/plugin_filter_clues.py", line 103, in filter_ignorable_resource_clues
    filtered = filter_ignorable_clues(detections, rules_by_id)
  File "/home/vanl/.local/pipx/venvs/scancode-toolkit/lib/python3.8/site-packages/cluecode/plugin_filter_clues.py", line 240, in filter_ignorable_clues
    ignorables=ignorables.emails.union(
AttributeError: 'NoneType' object has no attribute 'emails'

### How To Reproduce

Run ScanCode version 3.2.3 with -u or -e

scancode -clpieu -n 4 --json-pp project.json project --consolidate --filter-clues --classify --summary --summary-key-files --summary-with-details

### System configuration

* What OS are you running on? (Windows/MacOS/Linux)
  WSL2 Linux, but also manifests on Windows.

* What version of scancode-toolkit was used to generate the scan file?
  $>  scancode --version
  ScanCode version 3.2.3

* What installation method was used to install/run scancode? (pip/source download/other)
  pipx install full

**Comment by VanL** [comment]
Closed in error.

**Comment by pombredanne** [comment]
Thank you++
