### ISSUE TITLE
Not usable with commoncode 21.1.14

### ISSUE THREAD

**Issue by danielthieleog** [nexB/scancode-toolkit#2368]
### Description

When using new commoncode release 21.1.14 calling scancode fails.
This was not the case with commoncode release 20.10.20.

Error message from scancode

> Traceback (most recent call last):
>   File "/app/venv-scancode/bin/scancode", line 5, in <module>
>     from scancode.cli import scancode
>   File "/app/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 73, in <module>
>     from commoncode.fileutils import PATH_TYPE
> ImportError: cannot import name 'PATH_TYPE'

### How To Reproduce

```
# Workdir is /app
pip install virtualenv \
    && virtualenv -p /usr/local/bin/python3.6 venv-scancode \
    && . venv-scancode/bin/activate \
    && pip install scancode-toolkit pyicu

virtualenv -p /usr/local/bin/python3.6 venv-scancode
. venv-scancode/bin/activate
    
/app/venv-scancode/bin/scancode

```

Error also occurs with python 3.9.1.

### System configuration

Running on Linux in python:3.6 docker container.
Release 3.2.3 of scancode-toolkit.
Installed with pip.

**Comment by priv-kweihmann** [comment]
https://github.com/nexB/commoncode/commit/0c646b79169bcd5179902010ef4d4d7aea1cfacd removed that code, although that doesn't look perfectly right to me - The block starting from https://github.com/nexB/commoncode/commit/0c646b79169bcd5179902010ef4d4d7aea1cfacd#diff-95c7b154fe632f7ace737d26910c5bc5b7d0a5947d09ffcd905fae446e58d588L96 shouldn't have been removed IMO

But to me that is rather a bug in commoncode

**Comment by JeroenKnoops** [comment]
Also happens in commoncode-21.1.21
PATH_TYPE can not be imported anymore.

**Comment by priv-kweihmann** [comment]
I hope https://github.com/nexB/commoncode/pull/10 will fix the issue

**Comment by danielthieleog** [comment]
Not fixed yet. nexB/commoncode#10 is still open.

**Comment by Angi2412** [comment]
> Not fixed yet. [nexB/commoncode#10](https://github.com/nexB/commoncode/pull/10) is still open.

Did you find a workaround while the issue is not fixed?
Or should I just use an earlier release of scancode?

**Comment by JeroenKnoops** [comment]
I'm not sure how to use an earlier release...

**Comment by priv-kweihmann** [comment]
you can enforce earlier versions of commoncode (https://pypi.org/project/commoncode/20.10.20/ should work fine)

**Comment by Angi2412** [comment]
> you can enforce earlier versions of commoncode (https://pypi.org/project/commoncode/20.10.20/ should work fine)

Thank you! That works for now 👍

**Comment by JeroenKnoops** [comment]
Sorry to bother again, but I don't seem to get that working.. How did you do this @Angi2412 ?

New vitualenv:
```
pip install commoncode==20.10.20
pip install scancode-toolkit[full]
```
Still uses 21.1.21

**Comment by priv-kweihmann** [comment]
```
pip install scancode-toolkit[full]
pip install --force commoncode==20.10.20
```
should do the trick

**Comment by JeroenKnoops** [comment]
Unfortunately this will result in:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
typecode 21.1.21 requires commoncode>=21.1.21, but you have commoncode 20.10.20 which is incompatible.
scancode-toolkit 3.2.3 requires chardet<4.0.0,>=3.0.0, but you have chardet 4.0.0 which is incompatible.
plugincode 21.1.21 requires commoncode>=21.1.21, but you have commoncode 20.10.20 which is incompatible.
extractcode 21.1.21 requires commoncode>=21.1.21, but you have commoncode 20.10.20 which is incompatible.
debut 0.9.8 requires chardet<4.0.0,>=3.0.0, but you have chardet 4.0.0 which is incompatible.
```

I will wait till the release... No worries.

**Comment by danielthieleog** [comment]
As workaround try to install old commoncode 20.10.20  together with the other packages, e.g.

```
pip install virtualenv \
    && virtualenv -p /usr/local/bin/python3.6 venv-scancode \
    && . venv-scancode/bin/activate \
    && pip install commoncode==20.10.20 scancode-toolkit extractcode pyicu
```

**Comment by Angi2412** [comment]
> Sorry to bother again, but I don't seem to get that working.. How did you do this @Angi2412 ?
> 
> New vitualenv:
> 
> ```
> pip install commoncode==20.10.20
> pip install scancode-toolkit[full]
> ```
> 
> Still uses 21.1.21

I use it in a requirements.txt file and install it in a Dockerfile.
Content of requirements.txt:
```
[...]
commoncode==20.10.20
scancode-toolkit[full]
[...]
```

Content of Dockerfile:
```
[...]
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt
[...]
```

**Comment by danielthieleog** [comment]
Installing the current version with pip using scancode-toolkit[full] no longer showed the errors. It installed scancode_toolkit==21.2.9 with commoncode==21.1.21

**Comment by pombredanne** [comment]
I am still struggling with some installation quirks, but I would be grateful if you can try the latest release in a clean install directory.

**Comment by danielthieleog** [comment]
@pombredanne , successfully installed tonight in a fresh python:3.6 docker container.

```
Step 2/12 : RUN apt-get update  && apt-get install -y bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev  && rm -rf /var/lib/apt/lists/*
...
bzip2 is already the newest version (1.0.6-9.2~deb10u1).
libxml2-dev is already the newest version (2.9.4+dfsg1-7+deb10u1).
libxslt1-dev is already the newest version (1.1.32-2.2~deb10u1).
xz-utils is already the newest version (5.2.4-1).
zlib1g is already the newest version (1:1.2.11.dfsg-1).
zlib1g set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
...
Step 3/12 : RUN mkdir /app
 ---> Running in bdba18c738e4
...
Step 5/12 : WORKDIR /app
 ---> Running in d829984f4c56
...
Step 6/12 : RUN pip install virtualenv     && virtualenv -p /usr/local/bin/python3.6 venv-scancode     && . venv-scancode/bin/activate     && pip install scancode-toolkit[full] extractcode[full] pyicu     && /app/venv-scancode/bin/scancode --reindex-licenses
 ---> Running in 4cafc7c7e084
Collecting...
Installing collected packages: zipp, typing-extensions, six, importlib-resources, importlib-metadata, filelock, distlib, appdirs, virtualenv
Successfully installed appdirs-1.4.4 distlib-0.3.1 filelock-3.0.12 importlib-metadata-3.4.0 importlib-resources-5.1.0 six-1.15.0 typing-extensions-3.7.4.3 virtualenv-20.4.2 zipp-3.4.0
created virtual environment CPython3.6.12.final.0-64 in 878ms
  creator CPython3Posix(dest=/app/venv-scancode, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Collecting...
Building wheels for collected packages: intbitset, patch, pyicu, bitarray, ftfy, nltk, pefile, pyahocorasick, future
  Building wheel for intbitset (setup.py): started
  Building wheel for intbitset (setup.py): finished with status 'done'
  Created wheel for intbitset: filename=intbitset-2.4.1-cp36-cp36m-linux_x86_64.whl size=319585 sha256=e83d55d3d6bc6af5f30040b575aa69748a5bf84bdf82da6efecf22a7e7d6c5f2
  Stored in directory: /root/.cache/pip/wheels/b1/86/a9/0bc7b11838472538ad899680c8ba6068dcb285b4efbb81976b
  Building wheel for patch (setup.py): started
  Building wheel for patch (setup.py): finished with status 'done'
  Created wheel for patch: filename=patch-1.16-py3-none-any.whl size=12407 sha256=e8a51698b2703611d7ba7447d0e608f3b65170fda742cc94c9053d3fc764904e
  Stored in directory: /root/.cache/pip/wheels/e9/24/77/5193fd8755d4ac05f0851b771cea58c94ca018ad521a23332c
  Building wheel for pyicu (setup.py): started
  Building wheel for pyicu (setup.py): finished with status 'done'
  Created wheel for pyicu: filename=PyICU-2.6-cp36-cp36m-linux_x86_64.whl size=1671105 sha256=b7b6ed8a5c1924dfcb09aff55059543fd22e42efd29c4cf5e45313e18c4fb136
  Stored in directory: /root/.cache/pip/wheels/7d/18/ed/a482e04adc05fa9e9354ac5d126b7e864b875ba8915b9b8a30
  Building wheel for bitarray (setup.py): started
  Building wheel for bitarray (setup.py): finished with status 'done'
  Created wheel for bitarray: filename=bitarray-0.9.3-cp36-cp36m-linux_x86_64.whl size=128911 sha256=e1b002b6cf282cf4b8f12af12f557e7e7013737b50b8340ad6687c28a0953a58
  Stored in directory: /root/.cache/pip/wheels/c0/b6/de/19d6fd7250ececf1ec811c1f4f797b4442f8bd78c48b21df59
  Building wheel for ftfy (setup.py): started
  Building wheel for ftfy (setup.py): finished with status 'done'
  Created wheel for ftfy: filename=ftfy-4.4.3-py3-none-any.whl size=41068 sha256=feadd8815246b037f079712f7abce9640a93b9a4f65433b2be4cd81bd51ad7a9
  Stored in directory: /root/.cache/pip/wheels/f1/47/dc/48b860b321b7dda1073ced6eaea164a6b94f25936b10eba32f
  Building wheel for nltk (setup.py): started
  Building wheel for nltk (setup.py): finished with status 'done'
  Created wheel for nltk: filename=nltk-3.5-py3-none-any.whl size=1434676 sha256=61b0f694bdbbcfd1cc8b8afe3be9568f215394eb9d38ae4e5b3c5505ebe67274
  Stored in directory: /root/.cache/pip/wheels/de/5e/42/64abaeca668161c3e2cecc24f864a8fc421e3d07a104fc8a51
  Building wheel for pefile (setup.py): started
  Building wheel for pefile (setup.py): finished with status 'done'
  Created wheel for pefile: filename=pefile-2019.4.18-py3-none-any.whl size=60822 sha256=be2920344f345f5fc58f30d2cd583641ed923d19cc49b19d0e8113fa3e4147f9
  Stored in directory: /root/.cache/pip/wheels/2c/19/61/c79689ef799ed5062f1376a5628fd8427cad5df1e7e15fd095
  Building wheel for pyahocorasick (setup.py): started
  Building wheel for pyahocorasick (setup.py): finished with status 'done'
  Created wheel for pyahocorasick: filename=pyahocorasick-1.4.1-cp36-cp36m-linux_x86_64.whl size=102850 sha256=096af0bb31638e54f994594ac0e61cd793cf836bdedcbdf3076bd7e0e750d46e
  Stored in directory: /root/.cache/pip/wheels/a5/cf/c2/c79ce865644045e393f55296c0a2e7127dc06d620bc139c15c
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=f5bb2925a6b3f54c0998a7683ef4fe1ec51f032d272535993e0d5e6ffda9abf3
  Stored in directory: /root/.cache/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94
Successfully built intbitset patch pyicu bitarray ftfy nltk pefile pyahocorasick future
Installing collected packages: zipp, urllib3, typing-extensions, soupsieve, six, PyYAML, pycparser, idna, chardet, certifi, typing, text-unidecode, saneyaml, requests, intbitset, importlib-metadata, click, cffi, Beautifulsoup4, attrs, sortedcontainers, pluggy, cryptography, commoncode, webencodings, pyparsing, plugincode, pdfminer.six, isodate, binaryornot, banal, xmltodict, wcwidth, typecode-libmagic, typecode, tqdm, toml, regex, rdflib, publicsuffix2, ply, patch, packaging, normality, more-itertools, MarkupSafe, lxml, joblib, html5lib, future, boolean.py, urlpy, spdx-tools, pymaven-patch, pygments, pycryptodome, pyahocorasick, pkginfo, pefile, packageurl-python, nltk, license-expression, jsonstreams, jinja2, javaproperties, jaraco.functools, gemfileparser, ftfy, fingerprints, fasteners, extractcode-libarchive, extractcode-7z, extractcode, dparse2, debut, colorama, bitarray, scancode-toolkit, pyicu
Successfully installed Beautifulsoup4-4.9.3 MarkupSafe-1.1.1 PyYAML-5.4.1 attrs-20.3.0 banal-1.0.4 binaryornot-0.4.4 bitarray-0.9.3 boolean.py-3.8 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 click-7.1.2 colorama-0.4.4 commoncode-21.1.21 cryptography-3.4.5 debut-0.9.9 dparse2-0.5.0.4 extractcode-21.1.21 extractcode-7z-16.5.210122 extractcode-libarchive-3.5.1.210122 fasteners-0.16 fingerprints-1.0.1 ftfy-4.4.3 future-0.18.2 gemfileparser-0.8.0 html5lib-1.1 idna-2.10 importlib-metadata-3.4.0 intbitset-2.4.1 isodate-0.6.0 jaraco.functools-3.2.0 javaproperties-0.8.0 jinja2-2.11.3 joblib-1.0.1 jsonstreams-0.5.0 license-expression-1.2 lxml-4.6.2 more-itertools-8.7.0 nltk-3.5 normality-2.1.1 packageurl-python-0.9.4 packaging-20.9 patch-1.16 pdfminer.six-20201018 pefile-2019.4.18 pkginfo-1.7.0 pluggy-0.13.1 plugincode-21.1.21 ply-3.11 publicsuffix2-2.20191221 pyahocorasick-1.4.1 pycparser-2.20 pycryptodome-3.10.1 pygments-2.8.0 pyicu-2.6 pymaven-patch-0.3.0 pyparsing-2.4.7 rdflib-5.0.0 regex-2020.11.13 requests-2.25.1 saneyaml-0.4 scancode-toolkit-21.2.9 six-1.15.0 sortedcontainers-2.3.0 soupsieve-2.2 spdx-tools-0.6.1 text-unidecode-1.3 toml-0.10.2 tqdm-4.56.2 typecode-21.1.21 typecode-libmagic-5.39.210122 typing-3.6.6 typing-extensions-3.7.4.3 urllib3-1.26.3 urlpy-0.5 wcwidth-0.2.5 webencodings-0.5.1 xmltodict-0.12.0 zipp-3.4.0
Checking and rebuilding the license index...
Done.
```

**Comment by JeroenKnoops** [comment]
If you need an environment f.e. python 3.9.1, you can also look here: https://github.com/nexB/scancode-toolkit/issues/2398

**Comment by pombredanne** [comment]
@danielthieleog @JeroenKnoops thank you ++ ... we are getting there slowly but surely!
