### ISSUE TITLE
Docker build fails with "/scancode-toolkit"' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by mensfeld** [nexB/scancode-toolkit#2429]
### Description

When trying to build `v21.2.25` within docker using `docker build -t scancode-toolkit .` I get following error:

```
Step 6/8 : RUN ./scancode --reindex-licenses
 ---> Running in 15a3d30fdb6e
* Configuring ScanCode for first use...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/__main__.py", line 168, in <module>
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/__main__.py", line 164, in run
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/virtualenv/__main__.py", line 18, in run
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/virtualenv/run/__init__.py", line 32, in cli_run
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/virtualenv/run/session.py", line 46, in run
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/virtualenv/run/session.py", line 53, in _create
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/virtualenv/create/creator.py", line 171, in run
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 97, in create
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/virtualenv/create/via_global_ref/builtin/ref.py", line 157, in run
  File "/scancode-toolkit/etc/thirdparty/virtualenv.pyz/virtualenv/util/path/_sync.py", line 45, in symlink
  File "/usr/local/lib/python3.6/pathlib.py", line 1327, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/usr/local/lib/python3.6/pathlib.py", line 434, in symlink
    return os.symlink(str(a), str(b))
FileExistsError: [Errno 17] File exists: '/usr/local/bin/python3' -> '/scancode-toolkit/bin/python'
Traceback (most recent call last):
  File "/scancode-toolkit/etc/configure.py", line 81, in call
    stderr=subprocess.STDOUT,
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/python3 "/scancode-toolkit/etc/thirdparty/virtualenv.pyz" --wheel embed --pip embed --setuptools embed --seeder pip --never-download --no-periodic-update -qq "/scancode-toolkit"' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scancode-toolkit/etc/configure.py", line 322, in <module>
    create_virtualenv(root_dir=ROOT_DIR, venv_pyz=VIRTUALENV_PYZ_APP_LOC, quiet=quiet)
  File "/scancode-toolkit/etc/configure.py", line 179, in create_virtualenv
    call(vcmd)
  File "/scancode-toolkit/etc/configure.py", line 84, in call
    raise Exception('Failed to run {}\n{}'.format(cmd, str(e)))
Exception: Failed to run /usr/local/bin/python3 "/scancode-toolkit/etc/thirdparty/virtualenv.pyz" --wheel embed --pip embed --setuptools embed --seeder pip --never-download --no-periodic-update -qq "/scancode-toolkit"
Command '/usr/local/bin/python3 "/scancode-toolkit/etc/thirdparty/virtualenv.pyz" --wheel embed --pip embed --setuptools embed --seeder pip --never-download --no-periodic-update -qq "/scancode-toolkit"' returned non-zero exit status 1.
The command '/bin/sh -c ./scancode --reindex-licenses' returned a non-zero code: 1
```

### How To Reproduce

```
git clone https://github.com/nexB/scancode-toolkit.git
cd scancode-toolkit
git checkout v21.2.25
docker build -t scancode-toolkit .
```
### System configuration

> For bug reports, it really helps us to know:

* Ubuntu 20.04.2 LTS
* v21/2/25
* Docker container - docker: `Docker version 19.03.8, build afacb8b7f0`

**Comment by mensfeld** [comment]
Closing. I was using a clone that I used to debug, thus it had the `bin/` directory. Removing that fixed everything. Sorry for the noise :pray:
