### ISSUE TITLE
Version 21.2.25 does not work with Python 3.9

### ISSUE THREAD

**Issue by FrankHeimes** [nexB/scancode-toolkit#2437]
### Description
ScanCode 21.2.25 fails to complete its initial configuration if started using Python 3.9

### How To Reproduce

1. Download and unzip ScanCode 21.2.25 into C:\My\scancode-toolkit-21.2.25
2. Install Python 3.9 for all users into C:\Python39.
   Note: Do not install Python in "C:\Program Files\Python39", because the configure.py script will fail if the path to python contains spaces.
2. Open a CMD in that directory
3. `set PATH=C:\Python39\Scripts;C:\Python39;%PATH%`
4. `set CONFIGURE_SUPPORTED_PYTHON=3.9`
5. `.\scancode.bat -h`

_Output:_
```
C:\My\scancode-toolkit-21.2.25>
C:\My\scancode-toolkit-21.2.25>.\scancode.bat -h
* Configuring ScanCode for first use...
* WARNING: Native Windows will be deprecated in the future in favor of Windows Subsystem for Linux
* WARNING: Please visit https://github.com/nexB/scancode-toolkit/issues/2366 for details and to provide feedback
ERROR: Could not find a version that satisfies the requirement bitarray<1.0.0,>=0.8.1 (from scancode-toolkit)
ERROR: No matching distribution found for bitarray<1.0.0,>=0.8.1
Traceback (most recent call last):
  File "C:\My\scancode-toolkit-21.2.25\etc\configure.py", line 76, in call
    subprocess.check_call(
  File "C:\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\My\scancode-toolkit-21.2.25\Scripts\python.exe -m pip install --upgrade --no-build-isolation --no-index --find-links C:\My\scancode-toolkit-21.2.25\thirdparty -qq --editable . --constraint requirements.txt' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\My\scancode-toolkit-21.2.25\etc\configure.py", line 331, in <module>
    pip_install(requirement_args, quiet=quiet)
  File "C:\My\scancode-toolkit-21.2.25\etc\configure.py", line 216, in pip_install
    call(cmd)
  File "C:\My\scancode-toolkit-21.2.25\etc\configure.py", line 84, in call
    raise Exception('Failed to run {}\n{}'.format(cmd, str(e)))
Exception: Failed to run C:\My\scancode-toolkit-21.2.25\Scripts\python.exe -m pip install --upgrade --no-build-isolation --no-index --find-links C:\My\scancode-toolkit-21.2.25\thirdparty -qq --editable . --constraint requirements.txt
Command 'C:\My\scancode-toolkit-21.2.25\Scripts\python.exe -m pip install --upgrade --no-build-isolation --no-index --find-links C:\My\scancode-toolkit-21.2.25\thirdparty -qq --editable . --constraint requirements.txt' returned non-zero exit status 1.
```

### System configuration
Windows 10 Enterprise LTSC 1809, 64 Bit

**Comment by s4-2** [comment]
Hello @FrankHeimes , I think scancode-toolkit version 21.2.25 is supported by Python36 only. Please check the [latest version](https://github.com/nexB/scancode-toolkit/releases/tag/v21.2.25) of scancode-toolkit.

**Comment by FrankHeimes** [comment]
> Hello @FrankHeimes , I think scancode-toolkit version 21.2.25 is supported by Python36 only. Please check the [latest version](https://github.com/nexB/scancode-toolkit/releases/tag/v21.2.25) of scancode-toolkit.

But version 21.2.25 is a successor of version 21.2.19 and the release notes for that version state:
  _Add support for Python 3.6, 37, 3.8 and 3.9 on Linux, Windows and macOS_
which is quite unambiguous, IMHO.
See [Releases](https://github.com/nexB/scancode-toolkit/releases).

**Comment by s4-2** [comment]
Thank you @FrankHeimes , I was not knowing that. I have clicked the latest version link but I couldn't saw this information about os.

**Comment by mapelpapel** [comment]
I can confirm the bug. Also does not work for Python 3.7 and 3.8

I'm using the original Dockerfile and only changed the base image (Python 3.7, 3.8 and 3.9). Works fine with 3.6

Python 3.9:

```
[+] Building 10.3s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.86kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim-buster                                          1.2s
 => [internal] load build context                                                                                  2.4s
 => => transferring context: 3.07MB                                                                                2.3s
 => [1/6] FROM docker.io/library/python:3.9-slim-buster@sha256:42c8f29231de3ac4b6bee92ed1313ad7650bc5a2a4cd56fdd8  0.0s
 => CACHED [2/6] RUN apt-get update  && apt-get install -y bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev libgomp  0.0s
 => CACHED [3/6] RUN mkdir scancode-toolkit                                                                        0.0s
 => [4/6] COPY . scancode-toolkit                                                                                  2.3s
 => [5/6] WORKDIR scancode-toolkit                                                                                 0.0s
 => ERROR [6/6] RUN ./scancode --reindex-licenses                                                                  4.3s
------
 > [6/6] RUN ./scancode --reindex-licenses:
#10 0.272 * Configuring ScanCode for first use...
#10 4.238 ERROR: Could not find a version that satisfies the requirement intbitset<3.0,>=2.3.0 (from scancode-toolkit)
#10 4.238 ERROR: No matching distribution found for intbitset<3.0,>=2.3.0
#10 4.266 Traceback (most recent call last):
#10 4.266   File "/scancode-toolkit/etc/configure.py", line 76, in call
#10 4.266     subprocess.check_call(
#10 4.266   File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
#10 4.266     raise CalledProcessError(retcode, cmd)
#10 4.266 subprocess.CalledProcessError: Command '"/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt' returned non-zero exit status 1.
#10 4.266
#10 4.266 During handling of the above exception, another exception occurred:
#10 4.266
#10 4.266 Traceback (most recent call last):
#10 4.266   File "/scancode-toolkit/etc/configure.py", line 331, in <module>
#10 4.266     pip_install(requirement_args, quiet=quiet)
#10 4.266   File "/scancode-toolkit/etc/configure.py", line 216, in pip_install
#10 4.266     call(cmd)
#10 4.266   File "/scancode-toolkit/etc/configure.py", line 84, in call
#10 4.266     raise Exception('Failed to run {}\n{}'.format(cmd, str(e)))
#10 4.266 Exception: Failed to run "/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt
#10 4.266 Command '"/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt' returned non-zero exit status 1.
------
executor failed running [/bin/sh -c ./scancode --reindex-licenses]: exit code: 1
```

Python 3.8:
```
[+] Building 50.1s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.86kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim-buster                                          2.1s
 => [1/6] FROM docker.io/library/python:3.8-slim-buster@sha256:9c135cab3c5bf54d31965aeb1023555d80c026926b469895ad  1.4s
 => => resolve docker.io/library/python:3.8-slim-buster@sha256:9c135cab3c5bf54d31965aeb1023555d80c026926b469895ad  0.0s
 => => sha256:9c135cab3c5bf54d31965aeb1023555d80c026926b469895adbc769f91b1bc33 1.86kB / 1.86kB                     0.0s
 => => sha256:a97dab3043b39294d207eba02b0d848561d6a0ff40eb465aa2e6c662d3e48ed7 1.37kB / 1.37kB                     0.0s
 => => sha256:78418fd7e5270118bf3f947f5a4b6f5a990b557c9e021bcaba9f40e10647f771 7.65kB / 7.65kB                     0.0s
 => => sha256:0e6f0a09ecb9f387f39124eb9d983ccb20d35b09ad539777260528c55a94b2b0 10.68MB / 10.68MB                   0.5s
 => => sha256:cb3ef6c5b062533a9376b5f8c57ac3b2efe48a61d67546995a5d4f42ea63b672 233B / 233B                         0.3s
 => => sha256:10b895c4ca736ae94bf460697cff4cbd4d9d7470f368629eb2e462623b821fd2 2.45MB / 2.45MB                     0.5s
 => => extracting sha256:0e6f0a09ecb9f387f39124eb9d983ccb20d35b09ad539777260528c55a94b2b0                          0.4s
 => => extracting sha256:cb3ef6c5b062533a9376b5f8c57ac3b2efe48a61d67546995a5d4f42ea63b672                          0.0s
 => => extracting sha256:10b895c4ca736ae94bf460697cff4cbd4d9d7470f368629eb2e462623b821fd2                          0.2s
 => [internal] load build context                                                                                  2.4s
 => => transferring context: 3.07MB                                                                                2.3s
 => [2/6] RUN apt-get update  && apt-get install -y bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev libgomp1       39.8s
 => [3/6] RUN mkdir scancode-toolkit                                                                               0.3s
 => [4/6] COPY . scancode-toolkit                                                                                  2.2s
 => [5/6] WORKDIR scancode-toolkit                                                                                 0.0s
 => ERROR [6/6] RUN ./scancode --reindex-licenses                                                                  4.1s
------
 > [6/6] RUN ./scancode --reindex-licenses:
#10 0.234 * Configuring ScanCode for first use...
#10 4.045 ERROR: Could not find a version that satisfies the requirement bitarray<1.0.0,>=0.8.1 (from scancode-toolkit)
#10 4.045 ERROR: No matching distribution found for bitarray<1.0.0,>=0.8.1
#10 4.074 Traceback (most recent call last):
#10 4.074   File "/scancode-toolkit/etc/configure.py", line 76, in call
#10 4.074     subprocess.check_call(
#10 4.074   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#10 4.074     raise CalledProcessError(retcode, cmd)
#10 4.074 subprocess.CalledProcessError: Command '"/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt' returned non-zero exit status 1.
#10 4.074
#10 4.074 During handling of the above exception, another exception occurred:
#10 4.074
#10 4.074 Traceback (most recent call last):
#10 4.074   File "/scancode-toolkit/etc/configure.py", line 331, in <module>
#10 4.074     pip_install(requirement_args, quiet=quiet)
#10 4.074   File "/scancode-toolkit/etc/configure.py", line 216, in pip_install
#10 4.074     call(cmd)
#10 4.074   File "/scancode-toolkit/etc/configure.py", line 84, in call
#10 4.074     raise Exception('Failed to run {}\n{}'.format(cmd, str(e)))
#10 4.074 Exception: Failed to run "/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt
#10 4.074 Command '"/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt' returned non-zero exit status 1.
------
executor failed running [/bin/sh -c ./scancode --reindex-licenses]: exit code: 1
```

Python 3.7
```
[+] Building 49.0s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.86kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:3.7-slim-buster                                          1.3s
 => [1/6] FROM docker.io/library/python:3.7-slim-buster@sha256:c39453c07da6b6584574f8c80e87449d89103aed37dd1d7c72  1.5s
 => => resolve docker.io/library/python:3.7-slim-buster@sha256:c39453c07da6b6584574f8c80e87449d89103aed37dd1d7c72  0.0s
 => => sha256:37399a82762838ba8a93fa3c4d48ebfa751769743f87ae71f947b6d47b7bf788 10.06MB / 10.06MB                   0.6s
 => => sha256:5811c9b102ff06eb1cd2543f6ccf064ca0056961788c7e15feb5f83a9ff78f29 233B / 233B                         0.5s
 => => sha256:9efa2dee27390175bf9a04e80c7c76c24aadd61ef66fd0a52dfde60dca3772f2 2.45MB / 2.45MB                     0.3s
 => => sha256:c39453c07da6b6584574f8c80e87449d89103aed37dd1d7c72490e704ee20b22 1.86kB / 1.86kB                     0.0s
 => => sha256:52327179ebea430b32e0dc062410fad894a45d3389aee3bfe06ddb1777da0479 1.37kB / 1.37kB                     0.0s
 => => sha256:26de45a7328be2a778027d2fc3f416675d973802342b5920afa9ad28bbf089c0 8.29kB / 8.29kB                     0.0s
 => => extracting sha256:37399a82762838ba8a93fa3c4d48ebfa751769743f87ae71f947b6d47b7bf788                          0.4s
 => => extracting sha256:5811c9b102ff06eb1cd2543f6ccf064ca0056961788c7e15feb5f83a9ff78f29                          0.0s
 => => extracting sha256:9efa2dee27390175bf9a04e80c7c76c24aadd61ef66fd0a52dfde60dca3772f2                          0.2s
 => [internal] load build context                                                                                  2.4s
 => => transferring context: 3.07MB                                                                                2.3s
 => [2/6] RUN apt-get update  && apt-get install -y bzip2 xz-utils zlib1g libxml2-dev libxslt1-dev libgomp1       39.4s
 => [3/6] RUN mkdir scancode-toolkit                                                                               0.4s
 => [4/6] COPY . scancode-toolkit                                                                                  2.3s
 => [5/6] WORKDIR scancode-toolkit                                                                                 0.0s
 => ERROR [6/6] RUN ./scancode --reindex-licenses                                                                  4.0s
------
 > [6/6] RUN ./scancode --reindex-licenses:
#8 0.244 * Configuring ScanCode for first use...
#8 3.890 ERROR: Could not find a version that satisfies the requirement pyahocorasick<1.5,>=1.4 (from scancode-toolkit)
#8 3.890 ERROR: No matching distribution found for pyahocorasick<1.5,>=1.4
#8 3.916 Traceback (most recent call last):
#8 3.916   File "/scancode-toolkit/etc/configure.py", line 81, in call
#8 3.916     stderr=subprocess.STDOUT,
#8 3.916   File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
#8 3.916     raise CalledProcessError(retcode, cmd)
#8 3.916 subprocess.CalledProcessError: Command '"/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt' returned non-zero exit status 1.
#8 3.916
#8 3.916 During handling of the above exception, another exception occurred:
#8 3.916
#8 3.916 Traceback (most recent call last):
#8 3.916   File "/scancode-toolkit/etc/configure.py", line 331, in <module>
#8 3.916     pip_install(requirement_args, quiet=quiet)
#8 3.916   File "/scancode-toolkit/etc/configure.py", line 216, in pip_install
#8 3.916     call(cmd)
#8 3.916   File "/scancode-toolkit/etc/configure.py", line 84, in call
#8 3.916     raise Exception('Failed to run {}\n{}'.format(cmd, str(e)))
#8 3.916 Exception: Failed to run "/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt
#8 3.916 Command '"/scancode-toolkit/bin/pip" install --upgrade --no-build-isolation --no-index --find-links /scancode-toolkit/thirdparty -qq --editable . --constraint requirements.txt' returned non-zero exit status 1.
------
executor failed running [/bin/sh -c ./scancode --reindex-licenses]: exit code: 1
```

**Comment by pombredanne** [comment]
@FrankHeimes at this stage the latest  version 21.8.x support fully and is fully tested with Python 3.9 .
I am closing. Thank you for the report!
