### ISSUE TITLE
`TimeoutError` with `-p` parameter

### ISSUE THREAD

**Issue by ethanics** [nexB/scancode-toolkit#2522]
### Description

When executing scancode with `-p` parameter, the following error message occurs.

with '-p', it failed
```

$ scancode -p --json CocoaPods_fail.json CocoaPods/spec/fixtures/pineapple-lib/PineappleLib.podspec

Setup plugins...
Collect file inventory...
Scan files for: packages with 1 process(es)... 

Removing temporary files...done.
Traceback (most recent call last):
File "/home/user/venv/bin/scancode", line 8, in <module>
sys.exit(scancode())
File "/home/user/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/user/venv/lib/python3.8/site-packages/commoncode/cliutils.py", line 81, in main
return click.Command.main(
File "/home/user/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/user/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/user/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/home/user/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File "/home/user/venv/lib/python3.8/site-packages/scancode/cli.py", line 406, in scancode
success, _results = run_scan(
File "/home/user/venv/lib/python3.8/site-packages/scancode/cli.py", line 812, in run_scan
scan_success = run_scanners(
File "/home/user/venv/lib/python3.8/site-packages/scancode/cli.py", line 1004, in run_scanners
scan_success = scan_codebase(
File "/home/user/venv/lib/python3.8/site-packages/scancode/cli.py", line 1097, in scan_codebase
location, rid, scan_errors, scan_time, scan_result, scan_timings = next(scans)
File "/home/user/venv/lib/python3.8/site-packages/click/_termui_impl.py", line 127, in __next__
return next(iter(self))
File "/home/user/venv/lib/python3.8/site-packages/click/_termui_impl.py", line 318, in generator
for rv in self.iter:
File "/home/user/venv/lib/python3.8/site-packages/scancode/pool.py", line 52, in wrap
return func(self, timeout=timeout or 3600)
File "/usr/lib/python3.8/multiprocessing/pool.py", line 863, in next
raise TimeoutError from None
multiprocessing.context.TimeoutError
```

with '-l', it passed
```
$ scancode -l --json CocoaPods_pass.json CocoaPods/spec/fixtures/pineapple-lib/PineappleLib.podspec
Setup plugins...
Collect file inventory...
Scan files for: licenses with 1 process(es)...
Scanning done.
Summary: licenses with 1 process(es)
Errors count: 0
Scan Speed: 2.31 files/sec.
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s)
Final counts: 1 resource(s): 1 file(s) and 0 directorie(s)
Timings:
scan_start: 2021-05-14T021419.972359
scan_end: 2021-05-14T021421.774985
setup_scan:licenses: 1.37s
setup: 1.37s
scan: 0.43s
total: 1.80s
Removing temporary files...done.
```

### How To Reproduce

```
pip3 install scancode-toolkit==21.3.31
pip3 install click==7.1.2  # fix issue #2521
git clone https://github.com/CocoaPods/CocoaPods
scancode -p --json CocoaPods_fail.json CocoaPods/spec/fixtures/pineapple-lib/PineappleLib.podspec
```

### System configuration

* What OS are you running on? Ubuntu 20.04
* What version of scancode-toolkit was used to generate the scan file? 21.3.31
* What installation method was used to install/run scancode? pip

**Comment by pombredanne** [comment]
@ethan-ic Thank you ++ for the report. The podspec parser is a recent addition that's using https://github.com/gemfileparser/gemfileparser behind the scenes and is in https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/spec.py

https://raw.githubusercontent.com/CocoaPods/CocoaPods/master/spec/fixtures/pineapple-lib/PineappleLib.podspec likely trips some of the code there.
@rpotter12  any hunch of what could be the reason?

**Comment by pombredanne** [comment]
I am pretty sure this is a pathological regex that's taking exponential time.... though this needs digging.

**Comment by rpotter12** [comment]
> @ethan-ic Thank you ++ for the report. The podspec parser is a recent addition that's using https://github.com/gemfileparser/gemfileparser behind the scenes and is in https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/spec.py
> 
> https://raw.githubusercontent.com/CocoaPods/CocoaPods/master/spec/fixtures/pineapple-lib/PineappleLib.podspec likely trips some of the code there.
> @rpotter12 any hunch of what could be the reason?

Hi @pombredanne @ethan-ic 
Thanks for reporting this. I have checked this from the earlier version of this software (v3.2.1rc2). I got to know that this issue is from our earlier version. 

> I am pretty sure this is a pathological regex that's taking exponential time.... though this needs digging.

I tried parsing this file from https://github.com/gemfileparser/gemfileparser. I was able to parse this file from gemfileparser. There is something in our code. We need to dig into  https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/spec.py file. Some regex logic with our code is causing this issue.

I also found that gemfileparser is throwing output 
```
development :
runtime :
dependency :
         Pineapple
         Pineapple
test :
production :
metrics :
```
instead of
```
development :
runtime :
dependency :
         Pineapple/App
         Pineapple/App
test :
production :
metrics :
```

**Comment by chinyeungli** [comment]
Confirmed this is fixed and closing it.
```
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "v32.4.0-13-g30b0952149",
      "options": {
        "input": [
          "/mnt/c/Users/thoma/Desktop/tmp/PineappleLib.podspec"
        ],
        "--json-pp": "-",
        "--package": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2025-07-24T075400.568813",
      "end_timestamp": "2025-07-24T075410.511922",
      "output_format_version": "4.1.0",
      "duration": 9.943128108978271,
      "message": null,
      "errors": [],
      "warnings": [],
      "extra_data": {
        "system_environment": {
          "operating_system": "linux",
          "cpu_architecture": "64",
          "platform": "Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39",
          "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025",
          "python_version": "3.12.3 (main, Jun 18 2025, 17:59:45) [GCC 13.3.0]"
        },
        "spdx_license_list_version": "3.27",
        "files_count": 1
      }
    }
  ],
  "packages": [
    {
      "type": "cocoapods",
      "namespace": null,
      "name": "PineappleLib",
      "version": "1.0",
      "qualifiers": {},
      "subpath": null,
      "primary_language": "Objective-C",
      "description": "Pineapples For Summer.\nAll the Pineapples",
      "release_date": null,
      "parties": [
        {
          "type": "person",
          "role": "author",
          "name": "Pineapple Corp",
          "email": null,
          "url": null
        },
        {
          "type": "person",
          "role": "author",
          "name": "  Monkey Boy ",
          "email": "monkey@pineapple-corp.local",
          "url": null
        }
      ],
      "keywords": [],
      "homepage_url": "http://pineapple-corp.local/pineapple-lib.html",
      "download_url": null,
      "size": null,
      "sha1": null,
      "md5": null,
      "sha256": null,
      "sha512": null,
      "bug_tracking_url": "http://pineapple-corp.local/pineapple-lib/issues/",
      "code_view_url": "http://pineapple-corp.local/pineapple-lib/tree/1.0",
      "vcs_url": "http://pineapple-corp.local/pineapple-lib.git",
      "copyright": null,
      "holder": null,
      "declared_license_expression": null,
      "declared_license_expression_spdx": null,
      "license_detections": [],
      "other_license_expression": null,
      "other_license_expression_spdx": null,
      "other_license_detections": [],
      "extracted_license_statement": null,
      "notice_text": null,
      "source_packages": [],
      "is_private": false,
      "is_virtual": false,
      "extra_data": {},
      "repository_homepage_url": "https://cocoapods.org/pods/PineappleLib",
      "repository_download_url": "http://pineapple-corp.local/pineapple-lib/archive/refs/tags/1.0.zip",
      "api_data_url": "https://raw.githubusercontent.com/CocoaPods/Specs/blob/master/Specs/c/1/a/PineappleLib/1.0/PineappleLib.podspec.json",
      "package_uid": "pkg:cocoapods/PineappleLib@1.0?uuid=37f0fb7c-623d-4915-826d-62c1d735c3b6",
      "datafile_paths": [
        "PineappleLib.podspec"
      ],
      "datasource_ids": [
        "cocoapods_podspec"
      ],
      "purl": "pkg:cocoapods/PineappleLib@1.0"
    }
  ],
  "dependencies": [],
  "files": [
    {
      "path": "PineappleLib.podspec",
      "type": "file",
      "package_data": [
        {
          "type": "cocoapods",
          "namespace": null,
          "name": "PineappleLib",
          "version": "1.0",
          "qualifiers": {},
          "subpath": null,
          "primary_language": "Objective-C",
          "description": "Pineapples For Summer.\nAll the Pineapples",
          "release_date": null,
          "parties": [
            {
              "type": "person",
              "role": "author",
              "name": "Pineapple Corp",
              "email": null,
              "url": null
            },
            {
              "type": "person",
              "role": "author",
              "name": "  Monkey Boy ",
              "email": "monkey@pineapple-corp.local",
              "url": null
            }
          ],
          "keywords": [],
          "homepage_url": "http://pineapple-corp.local/pineapple-lib.html",
          "download_url": null,
          "size": null,
          "sha1": null,
          "md5": null,
          "sha256": null,
          "sha512": null,
          "bug_tracking_url": "http://pineapple-corp.local/pineapple-lib/issues/",
          "code_view_url": "http://pineapple-corp.local/pineapple-lib/tree/1.0",
          "vcs_url": "http://pineapple-corp.local/pineapple-lib.git",
          "copyright": null,
          "holder": null,
          "declared_license_expression": null,
          "declared_license_expression_spdx": null,
          "license_detections": [],
          "other_license_expression": null,
          "other_license_expression_spdx": null,
          "other_license_detections": [],
          "extracted_license_statement": null,
          "notice_text": null,
          "source_packages": [],
          "file_references": [],
          "is_private": false,
          "is_virtual": false,
          "extra_data": {},
          "dependencies": [],
          "repository_homepage_url": "https://cocoapods.org/pods/PineappleLib",
          "repository_download_url": "http://pineapple-corp.local/pineapple-lib/archive/refs/tags/1.0.zip",
          "api_data_url": "https://raw.githubusercontent.com/CocoaPods/Specs/blob/master/Specs/c/1/a/PineappleLib/1.0/PineappleLib.podspec.json",
          "datasource_id": "cocoapods_podspec",
          "purl": "pkg:cocoapods/PineappleLib@1.0"
        }
      ],
      "for_packages": [
        "pkg:cocoapods/PineappleLib@1.0?uuid=37f0fb7c-623d-4915-826d-62c1d735c3b6"
      ],
      "scan_errors": []
    }
  ]
}Scanning done.
Summary:        packages with 11 process(es)
Errors count:   0
Scan Speed:     0.84 files/sec.
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s)
Final counts:   1 resource(s): 1 file(s) and 0 directorie(s)
Timings:
  scan_start: 2025-07-24T075400.568813
  scan_end:   2025-07-24T075410.511922
  setup_scan:licenses: 8.74s
  setup: 8.74s
  scan: 1.19s
  total: 9.95s
Removing temporary files...done.
```
