### ISSUE TITLE
ScanCode killed within Docker container

### ISSUE THREAD

**Issue by Maarc** [nexB/scancode-toolkit#2696]
### Description

While analyzing some applications with the dockerized scancode, the scancode process is unexpectedly killed during the scan phase without any generated report:

```
./scancode: line 123:    16 Killed                  "$SCANCODE_ROOT_DIR/bin/scancode" "$@"
```

I have had this issue with different apps that I have been able to analyze without problem with previous versions of ScanCode. I suspect the timeout handling to be a bit too radical.

Any help to get the reports generated would be appreciated!

### How To Reproduce

a) Build the ScanCode docker image following the [official instructions](https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#installation-via-docker) using the "[Source code (zip)](https://github.com/nexB/scancode-toolkit/archive/refs/tags/v21.8.4.zip)" provided with the [v21.8.4 release](https://github.com/nexB/scancode-toolkit/releases/tag/v21.8.4).

b) Download and extract the [source code](https://github.com/hudson/hudson-2.x/archive/refs/heads/master.zip) of "hudson-2.x" as example application.

c) Start the analysis
```
docker run -v /Users/maarc/download/hudson_2_src/:/hudson_2_src scancode-toolkit -l -p -c --html-app /hudson_2_src/index.html /hudson_2_src --verbose -n 10 --timeout 0 --only-findings --ignore /test --ignore /tests --ignore *.jmx --ignore *.sha1 --ignore *.git --ignore *.mvn
```

d) You will get after a while:

```
 Setup plugin: scan:licenses...
 Setup plugin: scan:copyrights...
 Setup plugin: scan:packages...
 Setup plugin: output:html-app...
Collect file inventory...
Scan files for: licenses, copyrights, packages with 10 process(es)...
Scanned: /hudson_2_src/hudson-2.x-master/.hudson
[...]
Scanned: /hudson_2_src/hudson-2.x-master/hudson-core/src/main/resources/hudson/scm/SCM/project-changes.jelly
./scancode: line 123:    16 Killed                  "$SCANCODE_ROOT_DIR/bin/scancode" "$@"
```

### System configuration

* What OS are you running on? (Windows/MacOS/Linux)
MacOS

* What version of scancode-toolkit was used to generate the scan file?
v21.8.4 from the release page

* What installation method was used to install/run scancode? (pip/source download/other)
Built my own Docker container following the official instructions.

**Comment by pombredanne** [comment]
@Maarc thank you for the report. I was not able to reproduce this .... yet based on the ouput it seems that your got "proc killed" by the kernel. How much RAM and CPU do you have? 

With `-n 10` I would expect that you have about 11GB+ free RAM and about 10 cores? 


Also in all cases you would need to guard you patterns from shell expansion with quotes as in `scancode -l -p -c --html-app hudson_2_src-index.html --verbose -n 10 --timeout 0 --only-findings --ignore /test --ignore /tests --ignore "*.jmx" --ignore "*.sha1" --ignore "*.git" --ignore "*.mvn" tmp/huds/hudson-2.x-master/`

**Comment by pombredanne** [comment]
gentle ping

**Comment by rnjudge** [comment]
@pombredanne I am also seeing a "killed" error after a recent scancode upgrade. Was there a significant space requirement change or something? I never had this issue before and working on the same machine. This is a large blocker for Tern at the moment.

```
Running command: sudo /home/rjudge/ternenv/bin/scancode -ilpcu --quiet --timeout 300 -n 4 --json - /home/rjudge/.tern/temp/e63992559353a522e62a73bc137fd023ee97e1226b96947df8e00e73d1a9d627/contents
Killed
```

Increasing the timeout doesn't seem the help. I am running with Scancode 21.8.4

**Comment by Maarc** [comment]
@pombredanne I just updated to the latest version and gave it another try.

With `-n 10` set, I had the same error as previously. I have 16 GBs and 12 cores (`nproc --all`) on my machine. After reducing the threads to 4. It took a while but worked like a charm. 

Thank you very much for your support! This is highly appreciated. I think that we can close this issue. Maybe it would be good to add a hint on the requirement on the `x+1 GB+ free RAM and x cores` while using the `-n x` option.

**Comment by Maarc** [comment]
Meanwhile, I have conducted further tests leveraging the self-built Docker image and `-n 4`. The process does not get killed anymore. At the end of the execution, I got the following error:

```
Removing temporary files...done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 720, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 726, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scancode-toolkit/bin/scancode", line 33, in <module>
    sys.exit(load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')())
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/scancode-toolkit/lib/python3.6/site-packages/commoncode/cliutils.py", line 75, in main
    **extra,
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/scancode-toolkit/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/scancode-toolkit/src/scancode/cli.py", line 473, in scancode
    **kwargs
  File "/scancode-toolkit/src/scancode/cli.py", line 897, in run_scan
    echo_func=echo_func,
  File "/scancode-toolkit/src/scancode/cli.py", line 1127, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "/scancode-toolkit/src/scancode/cli.py", line 1236, in scan_codebase
    scan_timings) = next(scans)
  File "/scancode-toolkit/lib/python3.6/site-packages/click/_termui_impl.py", line 116, in __next__
    return next(iter(self))
  File "/scancode-toolkit/lib/python3.6/site-packages/click/_termui_impl.py", line 328, in generator
    for rv in self.iter:
  File "/scancode-toolkit/src/scancode/pool.py", line 52, in wrap
    return func(self, timeout=timeout or 3600)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 730, in next
    raise TimeoutError
multiprocessing.context.TimeoutError
```
