### ISSUE TITLE
21.8.4 crashes in a Python 3.6.15 venv

### ISSUE THREAD

**Issue by tgodau** [nexB/scancode-toolkit#2699]
### Description

Scancode 21.8.4 crashes, when trying to scan a file.

### How To Reproduce

Checked installed Python version:

    # python -V
    Python 3.6.15

Uninstalled 21.6.7:

    # pip3 uninstall scancode-toolkit
    Found existing installation: scancode-toolkit 21.6.7
    Uninstalling scancode-toolkit-21.6.7:
      Would remove:
        /home/tgodau/venv-scancode/bin/scancode
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/cluecode/*
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/formattedcode/*
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/licensedcode/*
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/packagedcode/*
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/scancode/*
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/scancode_config.py
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/scancode_toolkit-21.6.7.dist-info/*
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/summarycode/*
        /home/tgodau/venv-scancode/lib/python3.6/site-packages/textcode/*
    Proceed (y/n)? y
      Successfully uninstalled scancode-toolkit-21.6.7    

Installed the latest version:

    # pip3 install scancode-toolkit[full]
    Collecting scancode-toolkit[full]
    :
    Successfully installed commoncode-21.8.31 extractcode-21.7.23 parameter-expansion-patched-0.2.1b4 pygmars-0.7.0 scancode-toolkit-21.8.4

Checked the installed Scancode version

    # scancode --version
    ScanCode version 21.8.4

Tried to scan a file:

    # scancode -n 2 -clip ./base64-0.94R/b64.c --json-pp base64-0.94R.json
    Setup plugins...
    Collect file inventory...
    Scan files for: info, licenses, copyrights, packages with 2 process(es)...
    Removing temporary files...done.
    Traceback (most recent call last):
      File "/home/tgodau/venv-scancode/bin/scancode", line 8, in <module>
        sys.exit(scancode())
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/commoncode/cliutils.py", line 75, in main
        **extra,
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 453, in scancode
        **kwargs
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 875, in run_scan
        echo_func=echo_func,
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 1105, in run_scanners
        with_timing=timing, progress_manager=progress_manager)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 1202, in scan_codebase
        scans = progress_manager(scans)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/commoncode/cliutils.py", line 285, in progressmanager
        width=width,
    TypeError: __init__() got an unexpected keyword argument 'update_min_steps'

I got exact the same result as I tried to update Scancode instead of uninstall/install by:

     # pip3 install -U scancode-toolkit

and 

     # pip3 install --no-cache-dir -U scancode-toolkit

### System configuration

Ubuntu 20.04.3 LTS with latest updates running in a HyperV-VM.
Scancode runs in a Python 3.6.15 venv.
This configuration and example runs very well with previous version 21.6.7 (skipped 21.7.30)

**Comment by tgodau** [comment]
After a

    # pip3 install --no-cache-dir -U click
    Collecting click
      Downloading click-8.0.1-py3-none-any.whl (97 kB)
         |████████████████████████████████| 97 kB 54.4 MB/s
    Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in /home/tgodau/venv-scancode/lib/pyth
    on3.6/site-packages (from click) (1.7.0)
    Requirement already satisfied, skipping upgrade: zipp>=0.5 in /home/tgodau/venv-scancode/lib/python3.6/site-packages (from importl
    ib-metadata; python_version < "3.8"->click) (3.1.0)
    Installing collected packages: click
      Attempting uninstall: click
        Found existing installation: click 6.7
        Uninstalling click-6.7:
          Successfully uninstalled click-6.7
    Successfully installed click-8.0.1

scanning seems to start, but the JSON output crashes:

    # scancode -n 2 -clip ./base64-0.94R/b64.c --json-pp base64-0.94R.json
    Setup plugins...
    Collect file inventory...
    Scan files for: info, licenses, copyrights, packages with 2 process(es)...
    [####################] 2
    ERROR: failed to run output plugin: json-pp:
    Traceback (most recent call last):
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/scancode/cli.py", line 1035, in run_codebase_plugins
        plugin.process_codebase(codebase, **kwargs)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/formattedcode/output_json.py", line 77, in process_codebase
        write_results(codebase, output_file=output_json_pp, pretty=True, **kwargs)
      File "/home/tgodau/venv-scancode/lib/python3.6/site-packages/formattedcode/output_json.py", line 102, in write_results
        jsonstreams.Type.OBJECT,
      File "/usr/lib/python3.6/enum.py", line 326, in __getattr__
        raise AttributeError(name) from None
    AttributeError: OBJECT

    Scanning done.
    Summary:        info, licenses, copyrights, packages with 2 process(es)
    Errors count:   0
    Scan Speed:     0.65 files/sec. 13.34 KB/sec.
    Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s)
    Final counts:   1 resource(s): 1 file(s) and 0 directorie(s) for 20.62 KB
    Timings:
      scan_start: 2021-09-10T095522.330665
      scan_end:   2021-09-10T095525.618821
      setup_scan:licenses: 1.74s
      setup: 1.74s
      scan: 1.54s
      total: 3.29s
    Removing temporary files...done.

But now I am stuck.
Unfortunately I am not very familiar with this Python stuff, just a Scancode user...

**Comment by pombredanne** [comment]
@tgodau sorry for this. This is a bit of self-inflicted wound because of a too lax Click version range. Click is a third-party library that we use for command line processing.

**Comment by pombredanne** [comment]
@tgodau Have you tried using the release archive too?

**Comment by tgodau** [comment]
> @tgodau Have you tried using the release archive too?

Not yet, just the pip-stuff.
Good hint, I will try that....

**Comment by DennisClark** [comment]
obsolete, closing
