### ISSUE TITLE
"Some files failed to scan properly" error for some large files

### ISSUE THREAD

**Issue by kiranravindran90** [nexB/scancode-toolkit#2703]
I was running the scan on a batch of Binary files (.bin) and got the error "Some files failed to scan properly". When I saw which were the files, I noticed its failed on Large files (> 450 MB). While the smaller files scanned without any issues.

**Comment by kiranravindran90** [comment]
I was trying out different Timeout options and was able to run most files that doesn't timeout at 3600s. But there is a 5GB file which still doesn't scan. I tried having a timeout of 10800s, still getting an error. Find the error below.
-----------------*********************----------------------
Traceback (most recent call last):
  File "C:\Users\ravindk\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 684, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ravindk\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 690, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ravindk\Downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\Scripts\scancode-script.py", line 33, in <module>
    sys.exit(load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')())
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\lib\site-packages\commoncode\cliutils.py", line 75, in main
    **extra,
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\src\scancode\cli.py", line 453, in scancode
    **kwargs
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\src\scancode\cli.py", line 875, in run_scan
    echo_func=echo_func,
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\src\scancode\cli.py", line 1105, in run_scanners
    with_timing=timing, progress_manager=progress_manager)
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\src\scancode\cli.py", line 1214, in scan_codebase
    scan_timings) = next(scans)
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\lib\site-packages\click\_termui_impl.py", line 116, in __next__
    return next(iter(self))
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\lib\site-packages\click\_termui_impl.py", line 328, in generator
    for rv in self.iter:
  File "c:\users\ravindk\downloads\scancode-toolkit-21.8.4_py36-windows\scancode-toolkit-21.8.4\src\scancode\pool.py", line 52, in wrap
    return func(self, timeout=timeout or 10800)
  File "C:\Users\ravindk\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 694, in next
    raise TimeoutError
multiprocessing.context.TimeoutError
-----------------*********************----------------------

**Comment by pombredanne** [comment]
@kiranravindran90 Thank you for the report. I guess that's unfortunate butr there are no easy way out:
1. either you want to ensure you scan everything and if you have very large files, you would need to have a lot of resources (e.g. RAM)
2. or you could add a `--ignore` to skip this file
3. or do you think we should always skip by default certain files? (that can be risky though)

**Comment by kiranravindran90** [comment]
@pombredanne Thank you for the response. But unfortunately the large file are the important ones for me and wouldn't want to skip it.
Is there any limit to --timeout?
I get this error when I set the --timeout > 3600s

**Comment by pombredanne** [comment]
The timeout can be set to "infinite" with `--timeout 0`  or to a very large value.

See https://github.com/nexB/scancode-toolkit/blob/6d2320ca15a7e19b50ffd151449406a1d41d65cc/src/scancode/cli.py#L1365 

But that's not a great solution.
An alternative would be to consider carefully the type of this .bin file of yours. If this some binary firmware, it does not make sense to scan as-is. Instead it should be first pre-processed to extract the files (and or the strings) and/or split these in a series of smaller files. License and copyright information is unlikely to span all the splits anyway.
