### ISSUE TITLE
 Inconsistent rule text error

### ISSUE THREAD

**Issue by lukas2** [nexB/scancode-toolkit#2794]
I just cloned the repo and ran `sudo docker build -t scancode-toolkit .` as [stated in the documentation](https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#docker-install) and it fails with the following error:

```
Checking and rebuilding the license index...
Traceback (most recent call last):
  File "/scancode-toolkit/bin/scancode", line 33, in <module>
    sys.exit(load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')())
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/scancode-toolkit/lib/python3.6/site-packages/commoncode/cliutils.py", line 75, in main
    **extra,
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 1061, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/scancode-toolkit/lib/python3.6/site-packages/click/core.py", line 2326, in process_value
    value = self.callback(ctx, self, value)
  File "/scancode-toolkit/src/licensedcode/plugin_license.py", line 54, in reindex_licenses
    get_index(check_consistency=True)
  File "/scancode-toolkit/src/licensedcode/cache.py", line 392, in get_index
    return get_cache(check_consistency=check_consistency).index
  File "/scancode-toolkit/src/licensedcode/cache.py", line 320, in get_cache
    populate_cache(check_consistency=check_consistency)
  File "/scancode-toolkit/src/licensedcode/cache.py", line 337, in populate_cache
    tree_base_dir=scancode_src_dir,
  File "/scancode-toolkit/src/licensedcode/cache.py", line 139, in load_or_build
    rules_data_dir=rules_data_dir,
  File "/scancode-toolkit/src/licensedcode/cache.py", line 195, in build_index
    _license_tokens=license_tokens,
  File "/scancode-toolkit/src/licensedcode/index.py", line 230, in __init__
    _license_tokens=_license_tokens,
  File "/scancode-toolkit/src/licensedcode/index.py", line 373, in _add_rules
    for rts in rule.tokens():
  File "/scancode-toolkit/src/licensedcode/models.py", line 1665, in tokens
    text = self.text().strip()
  File "/scancode-toolkit/src/licensedcode/models.py", line 1585, in text
    f'Inconsistent rule text for: {self.identifier}\n'
licensedcode.models.InvalidRule: Inconsistent rule text for: gpl-3.0_with_sencha-app-floss-exception_or_gpl-3.0_with_sencha-dev-floss-exception_or_sencha-commercial_and_public-domain_and_mit_and_mit_1.RULE
file:///scancode-toolkit/src/licensedcode/data/rules/gpl-3.0_with_sencha-app-floss-exception_or_gpl-3.0_with_sencha-dev-floss-exception_or_sencha-commercial_and_public-domain_and_mit_and_mit_1.RULE
The command '/bin/sh -c ./scancode --reindex-licenses' returned a non-zero code: 1
```

**Comment by pombredanne** [comment]
@lukas2 Thanks for the report. That's surprising as the rules compile and tests pass otherwise :|
Which OS and docker version do you run?

**Comment by pombredanne** [comment]
gentle ping

**Comment by silverhook** [comment]
I get a similar bug on KUbuntu 20.04 LTS with:

```fish
/usr/bin/python3 -m pip install scancode-toolkit 
```

```
Building wheels for collected packages: bitarray, ftfy, pefile
  Building wheel for bitarray (setup.py) ... done
  Created wheel for bitarray: filename=bitarray-2.3.5-cp38-cp38-linux_x86_64.whl size=188773 sha256=f1834c9a2a97183892651132f122b40ae6030a9b61138905374be1ecc1a89bf0
  Stored in directory: /home/hook/.cache/pip/wheels/94/69/4b/830f24f80f3064bf446eb37eb441d7c1af74eda281bc2d9d03
  Building wheel for ftfy (setup.py) ... done
  Created wheel for ftfy: filename=ftfy-6.0.3-py3-none-any.whl size=41913 sha256=58d8f37862131e4dcdd4543c22ccf5a7d1ed8fca470ab07844bd349b9f380eee
  Stored in directory: /home/hook/.cache/pip/wheels/7f/40/63/4bf603cec3ecc4a26985405834cb47eb8368bfa59e15dde046
  Building wheel for pefile (setup.py) ... done
  Created wheel for pefile: filename=pefile-2021.9.3-py3-none-any.whl size=68832 sha256=daa6de4c9d0f349c8ac445e219730c0c0d70e232c667423b9d367af7bc4c99f4
  Stored in directory: /home/hook/.cache/pip/wheels/ee/a0/e1/ff2dafe5ae846f536acf0a4cc4a8b8d4ccb3044ab87f3ef174
Successfully built bitarray ftfy pefile
Installing collected packages: wcwidth, typecode-libmagic, text-unidecode, pygmars, pyahocorasick, publicsuffix2, pkginfo, patch, gemfileparser, extractcode-libarchive, extractcode-7z, bitarray, banal, urlpy, saneyaml, pluggy, pefile, parameter-expansion-patched, packageurl-python, normality, lxml, jsonstreams, javaproperties, jaraco.functools, intbitset, ftfy, fasteners, debian-inspector, pymaven-patch, fingerprints, dparse, commoncode, spdx-tools, plugincode, pdfminer.six, typecode, extractcode, scancode-toolkit
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.1
    Uninstalling lxml-4.2.1:
      Successfully uninstalled lxml-4.2.1
ERROR: Could not install packages due to an OSError: [Errno 36] Der Dateiname ist zu lang: '/home/hook/.local/lib/python3.8/site-packages/licensedcode/data/rules/gpl-3.0_with_sencha-app-floss-exception_or_gpl-3.0_with_sencha-dev-floss-exception_or_sencha-commercial_and_public-domain_and_mit_and_mit_1.RULE'
```

Errno 36 translates to “filename too long”.

**Comment by silverhook** [comment]
I also have trouble with that file if I extract the scanode-toolkit release tarball.

**Comment by pombredanne** [comment]
@silverhook are you running some disk encryption such as luks?

**Comment by silverhook** [comment]
encryptfs for the home partition, yes.

**Comment by pombredanne** [comment]
Hey, this has been resolved long ago!
See:
- https://github.com/aboutcode-org/scancode-toolkit/commit/d2f5bda687f6d1a7a7e8e7245a9d61822ed46571
- https://github.com/aboutcode-org/scancode-toolkit/pull/2918
- https://github.com/aboutcode-org/scancode-toolkit/issues/2901
