### ISSUE TITLE
v30.1.0 does not run the spdx plugins on MacOS v11.6

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#2805]
On MacOS v11.6, After creating json output of scan results using the latest scancode.io 30.1.1, I attempted to generate SPDX formatted reports using the plugins in scancode-toolkit-30.1.0, but sctk was unable to load those plugins.  I successfully ran the same process in scancode-toolkit-21.8.4 on the same files in the same MacOS version. 

Here are the errors reported by v30.1.0: 
```
(scancode-toolkit-30.1.0) <myUser>@MacBook-Pro-2 scancode-toolkit-30.1.0 % scancode --from-json /Users/<myUser>/Downloads/miniio.json --spdx-tv /Users/<myUser>/miniio.spdx --spdx-rdf /Users/<myUser>/miniio.spdx.xml
Setup plugins...
Collect file inventory...
ERROR: failed to run output plugin: spdx-rdf:
Traceback (most recent call last):
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/scancode/cli.py", line 1057, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/formattedcode/output_spdx.py", line 151, in process_codebase
    **kwargs
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/formattedcode/output_spdx.py", line 178, in _process_codebase
    as_tagvalue=as_tagvalue,
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/formattedcode/output_spdx.py", line 232, in write_spdx
    _patch_license_list()
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/formattedcode/output_spdx.py", line 73, in _patch_license_list
    licenses = load_licenses(with_deprecated=True)
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/models.py", line 497, in load_licenses
    raise Exception(msg)
Exception: Some License files are orphaned in '/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses'.
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/corporate-accountability-commercial-1.1.LICEN
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/ms-developer-services-agreement-2018-06.LICEN
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/ms-windows-container-base-image-eula-2020.LIC
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/oracle-bcl-javase-platform-javafx-2013.LICENS
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/oracle-bcl-javase-platform-javafx-2017.LICENS
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/oracle-openjdk-classpath-exception-2.0.LICENS

ERROR: failed to run output plugin: spdx-tv:
Traceback (most recent call last):
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/scancode/cli.py", line 1057, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/formattedcode/output_spdx.py", line 126, in process_codebase
    **kwargs
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/formattedcode/output_spdx.py", line 178, in _process_codebase
    as_tagvalue=as_tagvalue,
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/formattedcode/output_spdx.py", line 232, in write_spdx
    _patch_license_list()
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/formattedcode/output_spdx.py", line 73, in _patch_license_list
    licenses = load_licenses(with_deprecated=True)
  File "/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/models.py", line 497, in load_licenses
    raise Exception(msg)
Exception: Some License files are orphaned in '/Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses'.
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/corporate-accountability-commercial-1.1.LICEN
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/ms-developer-services-agreement-2018-06.LICEN
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/ms-windows-container-base-image-eula-2020.LIC
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/oracle-bcl-javase-platform-javafx-2013.LICENS
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/oracle-bcl-javase-platform-javafx-2017.LICENS
file:///Users/<myUser>/scancode-toolkit-30.1.0/lib/python3.6/site-packages/licensedcode/data/licenses/oracle-openjdk-classpath-exception-2.0.LICENS

Scanning done.
```

json-formatted scan resuls file attached for testing
[miniio.json.zip](https://github.com/nexB/scancode-toolkit/files/7916894/miniio.json.zip)

**Comment by DennisClark** [comment]
Problem still exists in scancode-toolkit-v32.3.3

**Comment by DennisClark** [comment]
The RTD documentation no longer contains the misleading statements about various SBOM output formats. Closing.
