### ISSUE TITLE
Cannot install extractcode[full]==21.7.23 because these package versions have conflicting dependencies

### ISSUE THREAD

**Issue by AnalogJ** [nexB/scancode-toolkit#2809]
### Description

I get the following error when attempting to install on Mac (using latest release binaries v30.x) or build a Docker image (from latest develop branch)

```
#10 46.71 ERROR: Cannot install extractcode[full]==21.7.23 because these package versions have conflicting dependencies.
#10 46.71 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
#10 46.71
#10 46.71 The conflict is caused by:
#10 46.71     extractcode[full] 21.7.23 depends on extractcode-7z>=16.5.210525; extra == "full"
#10 46.71     The user requested (constraint) extractcode-7z==16.5.210531
#10 46.71
#10 46.71 To fix this you could try to:
#10 46.71 1. loosen the range of package versions you've specified
#10 46.71 2. remove package versions to allow pip attempt to solve the dependency conflict
#10 46.71
------
```

### How To Reproduce

```
git clone ...
docker build -t scancode-toolkit .
```

**Comment by AnalogJ** [comment]
this seems to be related to M1 macs. I was able to build the image successfully by running:

```
docker buildx build --platform linux/amd64 -t scancode .
```

**Comment by pombredanne** [comment]
@AnalogJ Sorry for this... there is likely a bug on our side and some pip issue too https://github.com/pypa/pip/issues/10824
Also M1 Macs may require to run an X86 Python and run ScanCode in the compatibility mode. We use native code too and this is not yet compiled for ARM.

**Comment by pombredanne** [comment]
We are trying to solve these in the upcoming release. I will ping you as soon as we have a beta and your feedback would me much appreciated!

**Comment by coughlinj** [comment]
@AnalogJ On an M1 mac, and this worked for me, thank you!

**Comment by pombredanne** [comment]
@coughlinj thanks for the report. This helps

**Comment by MarcelBochtler** [comment]
> Also M1 Macs may require to run an X86 Python and run ScanCode in the compatibility mode. We use native code too and this is not yet compiled for ARM.

For me, running ScanCode on my M1 Mac fails using x86_64 bash and python3.8:

```bash
~/bin/scancode-toolkit-30.1.0
❯ arch -x86_64 /opt/local/bin/bash -c "/opt/local/bin/python3.8 -c 'import os; print(os.uname())'"
posix.uname_result(sysname='Darwin', nodename='Marcels-MacBook-Pro.local', release='21.3.0', version='Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000', machine='x86_64')

~/bin/scancode-toolkit-30.1.0
❯ arch -x86_64 /opt/local/bin/bash -c "./scancode --help"
* Configuring ScanCode for first use...
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/marcel/bin/scancode-toolkit-30.1.0/etc/thirdparty/virtualenv.pyz/__main__.py", line 4, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 6, in <module>
    import binascii
ImportError: dynamic module does not define module export function (PyInit_binascii)
```

**Comment by pombredanne** [comment]
This is solved in https://github.com/nexB/scancode-toolkit/pull/3053 and will be released with v31.
Thanks!
