### ISSUE TITLE
Error when running license scan

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#2866]
I've downloaded https://registry.npmjs.com/arm-analysisservices/@azure/arm-analysisservices-2.3.0.tgz, extracted it and scanned it with the latest version of scancode from the develop branch using the command:
`scancode -clipeu --classify --license-clarity-score ~/Desktop/arm-analysisservices-2.3.0/ --json-pp ~/Desktop/arm-analysisservices-2.3.0-clipeu-license-clarity.json`

and I get the following error on 24 Resources:

```
ERROR: for scanner: licenses:
ERROR: Unknown error:
Traceback (most recent call last):
  File "/home/jono/nexb/src/scancode-toolkit-2/src/scancode/interrupt.py", line 91, in interruptible
    return NO_ERROR, func(*(args or ()), **(kwargs or {}))
  File "/home/jono/nexb/src/scancode-toolkit-2/src/scancode/api.py", line 181, in get_licenses
    **kwargs,
  File "/home/jono/nexb/src/scancode-toolkit-2/src/licensedcode/index.py", line 930, in match
    **kwargs,
  File "/home/jono/nexb/src/scancode-toolkit-2/src/licensedcode/index.py", line 996, in match_query
    deadline=deadline,
  File "/home/jono/nexb/src/scancode-toolkit-2/src/licensedcode/index.py", line 668, in get_exact_matches
    merge=False,
  File "/home/jono/nexb/src/scancode-toolkit-2/src/licensedcode/match.py", line 2572, in refine_matches
    matches, discarded = filter_matches_missing_key_phrases(matches)
  File "/home/jono/nexb/src/scancode-toolkit-2/src/licensedcode/match.py", line 2070, in filter_matches_missing_key_phrases
    istopwords_by_pos = match.rule.stopwords_by_pos
AttributeError: stopwords_by_pos
```

I get the same issue when I only use the options `-il`.

**Comment by pombredanne** [comment]
Bummer!
Are you working from a checkout of develop?
If so you should run `scancode --reindex-licenses` after an update

**Comment by JonoYang** [comment]
@pombredanne Running the `--reindex-licenses` option worked. Thanks!
