### ISSUE TITLE
Inconsistent License cache: rebuilding index.

### ISSUE THREAD

**Issue by Gator8** [nexB/scancode-toolkit#3156]
### Description

Recently upgraded to 31.2.1 from 30.1, this has started happening on a much more frequent basis. So much so that I've had to disable these scans until the issue is resolved. Looks like the file scan runs fine, but when it tries to scan licenses, I get this error:

14:53:16   Inconsistent License cache: rebuilding index.
14:53:16   ERROR: Failed to load license cache (the file may be corrupted ?).
14:53:16   Please delete "C:\tools\scancode-toolkit-v31.2.1\venv\lib\site-packages\licensedcode\data\cache\license_index\index_cache" and retry.
14:53:16   If the problem persists, copy this error message and submit a bug report at https://github.com/nexB/scancode-toolkit/issues/
14:53:16   Traceback (most recent call last):
14:53:16     File "C:\tools\scancode-toolkit-v31.2.1\venv\lib\site-packages\licensedcode\cache.py", line 338, in load_cache_file
14:53:16       return pickle.load(lfc)
14:53:16     File "C:\tools\scancode-toolkit-v31.2.1\venv\lib\site-packages\attr\_make.py", line 958, in slots_setstate
14:53:16       def slots_setstate(self, state):
14:53:16   Exception
14:53:16   
14:53:16   The above exception was the direct cause of the following exception:
14:53:16   
14:53:16   Traceback (most recent call last):
14:53:16     File "C:\tools\scancode-toolkit-v31.2.1\venv\lib\site-packages\licensedcode\cache.py", line 84, in load_or_build
14:53:16       return load_cache_file(cache_file)
14:53:16     File "C:\tools\scancode-toolkit-v31.2.1\venv\lib\site-packages\licensedcode\cache.py", line 346, in load_cache_file
14:53:16       raise Exception(msg) from e
14:53:16   Exception: ERROR: Failed to load license cache (the file may be corrupted ?).
14:53:16   Please delete "C:\tools\scancode-toolkit-v31.2.1\venv\lib\site-packages\licensedcode\data\cache\license_index\index_cache" and retry.
14:53:16   If the problem persists, copy this error message and submit a bug report at https://github.com/nexB/scancode-toolkit/issues/

Judging by the timestamp on the left and the fact that it takes 10 minutes to rebuild the cache from the command line, there is never any attempt to rebuild the cache.

### How To Reproduce

I'm not sure how easy it is to reproduce. 

C:\tools\scancode-toolkit-v31.2.1\scancode -clpi -n 8  [BUNCH OF IGNORES] --strip-root --only-findings --verbose --json-pp %1.json --spdx-rdf %2.spdx %3

### System configuration

Windows 10
Scancode 31.2.1
zip file downloaded from github.

**Comment by pombredanne** [comment]
@Gator8 how did you install scancode? Which exact zip file did you use?
The wheel and application comes now with a pre-built index.

**Comment by Gator8** [comment]
![image](https://user-images.githubusercontent.com/7840300/204651351-3a596008-2d41-4504-988e-caf606c51ac4.png)

**Comment by pombredanne** [comment]
@Gator8 Thanks. That's really weird and this should never happen in this case unless there is some filesystem level file corruption.
Is this c:\tools a shared drive somehow?
Can you reproduce this on a fresh scancode zip extract?

**Comment by Gator8** [comment]
the tools dir is not shared, and yes, I was able to reproduce it right after a fresh install on more than one machine.

**Comment by pombredanne** [comment]
@Gator8 Thank you. Where these all on Windows?

**Comment by Gator8** [comment]
Yes. All on Windows (10 and server 2019)

**Comment by pombredanne** [comment]
I think this is related to #3179 ... and some subtle pickling bug in Python.

**Comment by AyanSinhaMahapatra** [comment]
@Gator8 this should be fixed in the new scancode-toolkit 31.2.3 release, please try it out to see if the issue is fixed there?

**Comment by RabeeaEgbareia** [comment]
I'm facing the same issue (installed on mac with docker - scanCode.io)

**Comment by AyanSinhaMahapatra** [comment]
@RabeeaEgbareia can you tell us which scancode-toolkit version you are using btw? Are you using the latest https://github.com/nexB/scancode-toolkit/releases/tag/v31.2.4 which had fixes for this? On the scancode.io side, can you confirm you are using the latest develop from https://github.com/nexB/scancode.io/ which has the updated https://github.com/nexB/scancode.io/blob/main/setup.cfg#L75 scancode-toolkit version 32.2.4?

**Comment by RabeeaEgbareia** [comment]
@AyanSinhaMahapatra 
scancodeio version = 32.0.1
scancode-toolkit[packages]==31.2.4

**Comment by RabeeaEgbareia** [comment]
@AyanSinhaMahapatra 
Is it good enough ?

**Comment by AyanSinhaMahapatra** [comment]
@RabeeaEgbareia yup! We fixed the issue by https://github.com/nexB/scancode-toolkit/pull/3193 for 31.2.4 which was solved. But seems like this has resurfaced again, I'm looking into this.

**Comment by AyanSinhaMahapatra** [comment]
I could not reproduce the issue with a fresh docker install of scancodeio version = 32.0.1, or a fresh pip install of scancode-toolkit 31.2.4 on a ubuntu 20.04 LTS. :thinking: 

@tdruez can you check if this happens on your side in mac?
@pombredanne  FYI ^

**Comment by tdruez** [comment]
@AyanSinhaMahapatra sure, what exactly do you need me to run?

**Comment by AyanSinhaMahapatra** [comment]
@tdruez any scan_codebase/scan_package scan of a small package with licenses to verify if this issue is present (happens in license scans). This with a fresh docker compose install for scancodeio version 32.0.1

Thanks for testing this out :smile:

**Comment by tdruez** [comment]
@AyanSinhaMahapatra no issues to report running ScanCode.io with Docker using the `scan_codebase` or `scan_package` pipelines.

**Comment by RabeeaEgbareia** [comment]
@AyanSinhaMahapatra Is there any progress ? solution ? workaround ?

**Comment by AyanSinhaMahapatra** [comment]
@RabeeaEgbareia on our side we could not reproduce this issue on mac or linux with the scancode.io/toolkit versions you specify here, so there could be some license index corruption issues on your side.

You could either, try using a fresh clone and docker build for scancode.io, or run `scancode --reindex-licenses` on your side (if you're using docker, then add this in the dockerfile after install steps) to reindex and get rid of this issue.

**Comment by tdruez** [comment]
@AyanSinhaMahapatra Note that the message "ERROR: Failed to load license cache (the file may be corrupted ?)." suggest a corruption but in some cases, this error can be raised by something not directly related to the integrity of the cache.

For example, a `scancode.interrupt.TimeoutError` may be raised during a `load_cache_file()` call, and that error message will lead you to the wrong path, as the index is not corrupted.

@RabeeaEgbareia encountering this error could be related to a memory issue while loading the cache (assumption based on his memory issues on the ScanCode.io side at https://github.com/nexB/scancode.io/issues/642#issue-1635767853).

Catching on global `Exception` is too broad, we may want to limit that specific corruption message to `PicklingError`, and propagate any other exceptions without that misleading message.
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/cache.py#L440
