### ISSUE TITLE
ScanCode 31.2.1 fail to scan a large XMI file

### ISSUE THREAD

**Issue by borisbaldassari** [nexB/scancode-toolkit#3175]
### Description

Scanning https://raw.githubusercontent.com/apache/poi/51cdefee23536aa916dd93f229c5cd6301be378c/src/models/poi.xmi with `--copyright --license --info --strip-root -n 4 --timeout 300 --processes 7` results in

```
09:59:43.356 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Scan of RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://github.com/apache/poi.git, revision=, path=), resolvedRevision=51cdefee23536aa916dd93f229c5cd6301be378c) with path scanner 'ScanCode' started.
09:59:43.359 [main] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'scancode --copyright --license --info --strip-root -n 4 --timeout 300 --processes 7 /tmp/ort-DefaultProvenanceDownloader12179513788909952484 --json-pp /tmp/ort-ScanCode727923217993477194/result.json' in '/home/ort'...
Exception in thread "main" java.io.IOException: Running 'scancode --copyright --license --info --strip-root -n 4 --timeout 300 --processes 7 /tmp/ort-DefaultProvenanceDownloader12179513788909952484 --json-pp /tmp/ort-ScanCode727923217993477194/result.json' in '/home/ort' failed with exit code 1:
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights with 7 process(es)...
Scanning done.
Some files failed to scan properly:
Path: ort-DefaultProvenanceDownloader12179513788909952484/src/models/poi.xmi
Summary:        info, licenses, copyrights with 7 process(es)
Errors count:   1
Scan Speed:     2.36 files/sec. 54.30 KB/sec.
Initial counts: 4259 resource(s): 3836 file(s) and 423 directorie(s) 
Final counts:   4258 resource(s): 3836 file(s) and 422 directorie(s) for 86.02 MB
Timings:
  scan_start: 2022-12-15T095944.898917
  scan_end:   2022-12-15T102654.718183
  setup_scan:licenses: 5.10s
  setup: 5.10s
  inventory: 1.09s
  scan: 1622.26s
  output:json-pp: 3.77s
  output: 3.77s
  total: 1633.86s
Removing temporary files...done.

	at org.ossreviewtoolkit.utils.common.ProcessCapture.requireSuccess(ProcessCapture.kt:154)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:74)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.run(CommandLinePathScannerWrapper.kt:32)
```
and exit code 1.

Full log is available at https://foundation.eclipse.org/ci/infra/job/ort/job/Staging/job/staging_run_ort/20/console

### How To Reproduce

See above.

### System configuration

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 31.2.1
* What installation method was used to install/run scancode? pip

**Comment by AyanSinhaMahapatra** [comment]
This is failing just because of the timeout specified:

I could not reproduce at first on my local machine, but a reduced timeout (--timeout 100) was able to reproduce. Showing both scan results here for context:

timeout: 100
```
 scancode --copyright --license --info --strip-root -n 4 --timeout 100 poi.xmi --json-pp poi.xmi.json
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights with 4 process(es)...
[####################] 2
Scanning done.
Some files failed to scan properly:
Path: poi.xmi
Summary:        info, licenses, copyrights with 4 process(es)
Errors count:   1
Scan Speed:     0.01 files/sec. 13.49 KB/sec.
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s)
Final counts:   1 resource(s): 1 file(s) and 0 directorie(s) for 1.32 MB
Timings:
  scan_start: 2022-12-15T141942.039324
  scan_end:   2022-12-15T142123.779232
  setup_scan:licenses: 1.31s
  setup: 1.31s
  scan: 100.42s
  total: 101.74s
Removing temporary files...done.

```

Results:
```
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "31.2.1",
      "options": {
        "input": [
          "poi.xmi"
        ],
        "--copyright": true,
        "--info": true,
        "--json-pp": "poi.xmi.json",
        "--license": true,
        "--processes": "4",
        "--strip-root": true,
        "--timeout": "100.0"
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2022-12-15T141942.039324",
      "end_timestamp": "2022-12-15T142123.779232",
      "output_format_version": "2.0.0",
      "duration": 101.73992133140564,
      "message": null,
      "errors": [
        "Path: poi.xmi"
      ],
      "warnings": [],
      "extra_data": {
        "system_environment": {
          "operating_system": "linux",
          "cpu_architecture": "64",
          "platform": "Linux-5.14.0-1054-oem-x86_64-with-glibc2.29",
          "platform_version": "#61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022",
          "python_version": "3.8.10 (default, Nov 14 2022, 12:59:47) \n[GCC 9.4.0]"
        },
        "spdx_license_list_version": "3.17",
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "poi.xmi",
      "type": "file",
      "name": "poi.xmi",
      "base_name": "poi",
      "extension": ".xmi",
      "size": 1387240,
      "date": "2022-12-15",
      "sha1": "75186edee1ac9fb5f3d4dc7112945078607f4819",
      "md5": "5d253d2b9ff5ee52c575a2be9410a073",
      "sha256": "63de228373b12a39e65884e5b0e31e1b9becd99191d424a514db015d97d7c8d8",
      "mime_type": "text/xml",
      "file_type": "XML 1.0 document, ASCII text",
      "programming_language": null,
      "is_binary": false,
      "is_text": true,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "files_count": 0,
      "dirs_count": 0,
      "size_count": 0,
      "scan_errors": [
        "ERROR: for scanner: licenses:\nERROR: Processing interrupted: timeout after 100 seconds."
      ]
    }
  ]
}
```

timeout: 300 

```
scancode --copyright --license --info --strip-root -n 4 --timeout 300 poi.xmi --json-pp poi.xmi.json
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights with 4 process(es)...
[####################] 2
Scanning done.
Summary:        info, licenses, copyrights with 4 process(es)
Errors count:   0
Scan Speed:     0.01 files/sec. 12.30 KB/sec.
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s)
Final counts:   1 resource(s): 1 file(s) and 0 directorie(s) for 1.32 MB
Timings:
  scan_start: 2022-12-15T142529.273333
  scan_end:   2022-12-15T142720.685554
  setup_scan:licenses: 1.30s
  setup: 1.30s
  scan: 110.10s
  total: 111.41s
Removing temporary files...done
```

Results:

```
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "31.2.1",
      "options": {
        "input": [
          "poi.xmi"
        ],
        "--copyright": true,
        "--info": true,
        "--json-pp": "poi.xmi.json",
        "--license": true,
        "--processes": "4",
        "--strip-root": true,
        "--timeout": "300.0"
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2022-12-15T142529.273333",
      "end_timestamp": "2022-12-15T142720.685554",
      "output_format_version": "2.0.0",
      "duration": 111.41223526000977,
      "message": null,
      "errors": [],
      "warnings": [],
      "extra_data": {
        "system_environment": {
          "operating_system": "linux",
          "cpu_architecture": "64",
          "platform": "Linux-5.14.0-1054-oem-x86_64-with-glibc2.29",
          "platform_version": "#61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022",
          "python_version": "3.8.10 (default, Nov 14 2022, 12:59:47) \n[GCC 9.4.0]"
        },
        "spdx_license_list_version": "3.17",
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "poi.xmi",
      "type": "file",
      "name": "poi.xmi",
      "base_name": "poi",
      "extension": ".xmi",
      "size": 1387240,
      "date": "2022-12-15",
      "sha1": "75186edee1ac9fb5f3d4dc7112945078607f4819",
      "md5": "5d253d2b9ff5ee52c575a2be9410a073",
      "sha256": "63de228373b12a39e65884e5b0e31e1b9becd99191d424a514db015d97d7c8d8",
      "mime_type": "text/xml",
      "file_type": "XML 1.0 document, ASCII text",
      "programming_language": null,
      "is_binary": false,
      "is_text": true,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "licenses": [
        {
          "key": "apache-2.0",
          "score": 100.0,
          "name": "Apache License 2.0",
          "short_name": "Apache 2.0",
          "category": "Permissive",
          "is_exception": false,
          "is_unknown": false,
          "owner": "Apache Software Foundation",
          "homepage_url": "http://www.apache.org/licenses/",
          "text_url": "http://www.apache.org/licenses/LICENSE-2.0",
          "reference_url": "https://scancode-licensedb.aboutcode.org/apache-2.0",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/apache-2.0.yml",
          "spdx_license_key": "Apache-2.0",
          "spdx_url": "https://spdx.org/licenses/Apache-2.0",
          "start_line": 4,
          "end_line": 17,
          "matched_rule": {
            "identifier": "apache-2.0_2.RULE",
            "license_expression": "apache-2.0",
            "licenses": [
              "apache-2.0"
            ],
            "referenced_filenames": [
              "NOTICE"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "is_license_intro": false,
            "has_unknown": false,
            "matcher": "2-aho",
            "rule_length": 119,
            "matched_length": 119,
            "match_coverage": 100.0,
            "rule_relevance": 100
          }
        }
      ],
      "license_expressions": [
        "apache-2.0"
      ],
      "percentage_of_license_text": 0.1,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "files_count": 0,
      "dirs_count": 0,
      "size_count": 0,
      "scan_errors": []
    }
  ]
}
```

Another point: you don't need to use both:
- `-n 4`
- `--processes 7`
as they are both the same CLI option, scancode will take only one.

**Comment by AyanSinhaMahapatra** [comment]
This and #3174 is the same issue essentially btw

**Comment by sschuberth** [comment]
> This and #3174 is the same issue essentially btw

Ok, thanks, so we'll try with an increased timeout (or a more powerful machine 😆 ).

**Comment by AyanSinhaMahapatra** [comment]
@sschuberth did you get to try this out?

**Comment by sschuberth** [comment]
No, I'd need to delegate to @borisbaldassari to verify that increasing the timeout helps.
