### ISSUE TITLE
`build_spdx_license_expression` breaks on deprecated licenses

### ISSUE THREAD

**Issue by tdruez** [nexB/scancode-toolkit#3400]
To reproduce:
```
from licensedcode.cache import build_spdx_license_expression
build_spdx_license_expression("broadcom-linking-unmodified")
```

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "lib/python3.10/site-packages/licensedcode/cache.py", line 514, in build_spdx_license_expression
    return parsed.render(template='{symbol.wrapped.spdx_license_key}')
  File "lib/python3.10/site-packages/license_expression/__init__.py", line 1283, in render
    return template.format(symbol=self)
AttributeError: 'LicenseSymbol' object has no attribute 'wrapped'
```

**Comment by pombredanne** [comment]
Thanks! I thought about this... I think we can handle this this way:
1. add a new "replaced_by" attribute to the license model
2. populate this attribute for all the licenses we did deprecate sine the latest major release (say v31)
3. when we create a `Licensing` object for the `license_expression` library (with `get_licensing`) we could either:
 - Use a set of symbols such that we include the deprecated license key and somehow ensure the LicenseSymbol returns the "replaced_by" symbol (but this may not work if a deprecated license is replaced by an expression)
 - Include the deprecated license key in the set of symbols, and IFF this symbols exists in the parsed expression, then we would "subst" substitute the deprecated key by the "replaced by" which can be an expression and not only a license key.

I have no idea how many licenses we did deprecate since V31 though

**Comment by AyanSinhaMahapatra** [comment]
So this is primarily because we don't parse this on the license-expression side:
See https://github.com/nexB/license-expression/blob/2d32a86a77ffe6a1d74b1839f98a5f4f51ae3b23/src/license_expression/__init__.py#L855

Deprecated license keys are present in both:
* the LicenseDB, like https://scancode-licensedb.aboutcode.org/agpl-3.0-bacula.html 
* and the index.json we have in license-expression https://github.com/nexB/license-expression/blob/2d32a86a77ffe6a1d74b1839f98a5f4f51ae3b23/src/license_expression/data/scancode-licensedb-index.json#L713

@pombredanne  updating all the deprecated licenses with a new "replaced_by" attribute does make sense in the longer term, but this could take some time to implement properly.
What about implementing a short fix where we don't fail here by also parsing deprecated license keys.
@tdruez what do you think?

Btw, just for reference, the same error is also cause by new licenses that are in a branch and not added yet in the LicenseDB and then to license-expression library.

We should also have specific exceptions in case of failures so we have better verbosity.
