### ISSUE TITLE
Release 30.1.0 can no longer be built due to PyYAML error

### ISSUE THREAD

**Issue by MarcelBochtler** [nexB/scancode-toolkit#3460]
### Description

Since the release of Cython 3.0 ScanCode 30.1.0 can no longer be build.

The error message seems to be related to an issue with PyYAML 5.4.1:
https://github.com/yaml/pyyaml/issues/601
https://github.com/yaml/pyyaml/issues/724

Workarounds are outlined in this comment: https://github.com/yaml/pyyaml/issues/724#issuecomment-1641571578

### How To Reproduce

```
curl -Os https://raw.githubusercontent.com/nexB/scancode-toolkit/v30.1.0/requirements.txt

pip install --no-cache-dir --constraint requirements.txt scancode-toolkit==30.1.0
```

The error message:
```
Collecting pyyaml
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 79.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-9zaykrar/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
```

### System configuration

* What OS are you running on?
Ubuntu 22.04.1 (within Docker)

* What version of scancode-toolkit was used to generate the scan file?
30.1.0

* What installation method was used to install/run scancode? (pip/source download/other)
pip

```
$ python --version
Python 3.10.8
$ pip --version
pip 22.2.2 from /opt/python/versions/3.10.8/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by pombredanne** [comment]
@MarcelBochtler after digging in this I think the issue is Python 3.10
It was released on 2021-10-04, while ScanCode v30.1.0  was released about a week before nn 2021-09-25. We did not run any tests nor had any support for Python 3.10 back then and neither did PyYAML https://pypi.org/project/PyYAML/5.4.1/#files

You should try instead to stick with Python 3.9 with this older ScanCode version.
Otherwise, since there are no pre-built wheel for Python 3.10, the install will try to build them and may face various issues like the one you found.  


Note that ScanCode v30.1.0 is 2252 commits behind the current latest stable which is a huge amount of changes! But I am sure you know this.... any specific reason for using such an old version?

**Comment by pombredanne** [comment]
@MarcelBochtler did this work?

**Comment by DennisClark** [comment]
the current version of SCTK is `scancode-toolkit-v32.3.3`.  Closing.
