### ISSUE TITLE
crash when supplying YAML file to --from-json

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#3596]
### Description

Related to #3595 

When supplying a YAML file to `--from-json` there is a crash.

### How To Reproduce

```
$ ./scancode --from-json /tmp/scancode.yaml --yaml /tmp/scancode2.yaml
Setup plugins...
Collect file inventory...
Removing temporary files...done.
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try the 'scancode --help' option for help on options and arguments.

Error: Invalid value: ERROR: failed to collect codebase at: '/tmp/scancode.yaml'
Traceback (most recent call last):
  File "/home/armijn/git/scancode-toolkit/src/scancode/cli.py", line 844, in run_scan
    codebase = codebase_class(
  File "/home/armijn/git/scancode-toolkit/venv/lib/python3.10/site-packages/commoncode/resource.py", line 1676, in __init__
    scan_data = self._get_scan_data(location)
  File "/home/armijn/git/scancode-toolkit/venv/lib/python3.10/site-packages/commoncode/resource.py", line 1736, in _get_scan_data
    return self._get_scan_data_helper(location)
  File "/home/armijn/git/scancode-toolkit/venv/lib/python3.10/site-packages/commoncode/resource.py", line 1690, in _get_scan_data_helper
    scan_data = json.load(f)
  File "/usr/lib64/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by pombredanne** [comment]
See also:
- [x] https://github.com/nexB/scancode-toolkit/issues/3595
- [x] https://github.com/nexB/scancode-toolkit/issues/3594
- [x] https://github.com/nexB/scancode-toolkit/issues/3593
- [x] https://github.com/nexB/scancode-toolkit/issues/3592
- [ ] https://github.com/nexB/scancode-toolkit/issues/3591
- [x] https://github.com/nexB/scancode-toolkit/issues/3590
- [ ] https://github.com/nexB/scancode-toolkit/issues/3589
- [ ] https://github.com/nexB/scancode-toolkit/issues/3588

**Comment by armijnhemel** [comment]
This seems to work properly now.
