### ISSUE TITLE
Release v1.3.0 can't use --verbose with other option!

### ISSUE THREAD

**Issue by K-Rex** [nexB/scancode-toolkit#37]
1.$./scancode --verbose -c ../gpl/ aaa

Scanning files...
Traceback (most recent call last):
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/bin/scancode", line 9, in <module>
    load_entry_point('scancode-toolkit==1.3.0', 'console_scripts', 'scancode')()
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/src/scancode/cli.py", line 282, in scancode
    for input_file in file_iter(files):
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/src/commoncode/fileutils.py", line 299, in file_iter
    for top, _dirs, files in walk(location, ignored):
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/src/commoncode/fileutils.py", line 265, in walk
    if filetype.is_file(location) :
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/src/commoncode/filetype.py", line 46, in is_file
    return (location and os.path.isfile(location)
  File "/home/rex/qdu_claro/yuki/tools/scancode-toolkit-1.3.0/lib/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, generator found

2.$./scancode --verbose --format html-app ../gpl/ gpl.html

TypeError: coercing to Unicode: need string or buffer, generator found

**Comment by pombredanne** [comment]
The latest develop branch has a fix... Sorry for that bug, that was such a silly mistake!

**Comment by pombredanne** [comment]
@K-Rex Please try using https://github.com/nexB/scancode-toolkit/archive/develop.tar.gz

**Comment by K-Rex** [comment]
It can work!

**Comment by pombredanne** [comment]
@K-Rex thank you for reporting and testing this!
