### ISSUE TITLE
NoneType not handled in add_referenced_license_matches_for_package

### ISSUE THREAD

**Issue by FaberFlorian** [nexB/scancode-toolkit#3969]
### Description

```
ERROR: failed to run scan plugin: packages:
Traceback (most recent call last):
  File "/scancode-toolkit/src/scancode/cli.py", line 1117, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/scancode-toolkit/src/packagedcode/plugin_package.py", line 252, in process_codebase
    modified = list(add_referenced_license_matches_for_package(resource, codebase))
  File "/scancode-toolkit/src/packagedcode/licensing.py", line 144, in add_referenced_license_matches_for_package
    detections_added.extend(referenced_resource.license_detections)
AttributeError: 'NoneType' object has no attribute 'license_detections'
```

### How To Reproduce

Reproducible by scanning lzo 2.10 with scancode v32.3.0. Worked before.

`docker run -v /home/foo/bar/lzo/src:/project -v /home/foo/bar/foss-licenses/licenseData/scancode:/licenses scancode-toolkit:latest -clpieu -n `nproc` --strip-root --json /licenses/lzo_2.10.json /project/`

**Comment by AyanSinhaMahapatra** [comment]
@FaberFlorian thanks for the report, I could reproduce this bug. Will add a fix soon
