### ISSUE TITLE
Document `scancode-license-data` in the console scripts section

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#4024]
### Description

Running `scancode-license-data` that comes with 32.3.0 does not work.

### How To Reproduce

1. Install `scancode-toolkit` version 32.3.0.
2. Run `scancode-license-data` without any arguments.
3. See

```
$ scancode-license-data
Dumping license data to: None
Traceback (most recent call last):
  File "/opt/python/versions/3.11.10/bin/scancode-license-data", line 8, in <module>
    sys.exit(dump_scancode_license_data())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/versions/3.11.10/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/versions/3.11.10/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/python/versions/3.11.10/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/versions/3.11.10/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/versions/3.11.10/lib/python3.11/site-packages/licensedcode/license_db.py", line 227, in dump_scancode_license_data
    scancode_license_data(path=path)
  File "/opt/python/versions/3.11.10/lib/python3.11/site-packages/licensedcode/license_db.py", line 204, in scancode_license_data
    count = generate(build_location=path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/versions/3.11.10/lib/python3.11/site-packages/licensedcode/license_db.py", line 175, in generate
    if not os.path.exists(build_location):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

The same happens on another machine with Python 3.13:

```
Dumping license data to: None
Traceback (most recent call last):
  File "/usr/bin/scancode-license-data", line 8, in <module>
    sys.exit(dump_scancode_license_data())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/licensedcode/license_db.py", line 227, in dump_scancode_license_data
    scancode_license_data(path=path)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/licensedcode/license_db.py", line 204, in scancode_license_data
    count = generate(build_location=path)
  File "/usr/lib/python3.13/site-packages/licensedcode/license_db.py", line 175, in generate
    if not os.path.exists(build_location):
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

### System configuration

* What OS are you running on? Linux
* What version of scancode-toolkit was used to generate the scan file? 32.3.0
* What installation method was used to install/run scancode? Both RPM package on Fedora and `pip install`.

**Comment by AyanSinhaMahapatra** [comment]
@sschuberth please refer to the help text for the command:

```
scancode-license-data --help
Usage: scancode-license-data [OPTIONS]

  Dump scancode license data in various formats, and the licenseDB static
  website at `path`.

Options:
  --path DIR  Dump the license data in this directory in the LicenseDB format
              and exit. Creates the directory if it does not exist.
  -h, --help  Show this message and exit.
```
The code is at https://github.com/aboutcode-org/scancode-toolkit/blob/develop/src/licensedcode/license_db.py#L208 btw, as indicated in the traceback.

I think you are not providing the `--path <path _to_dump_licenses>` option which is causing the issue.
I could do a simple pip install for the latest scancode and this does work allright.

```
python3 -m venv scancode-32.3
source scancode-32.3/bin/activate
pip install scancode-toolkit==32.3.0
scancode-license-data --help
scancode-license-data --path license-data
```

Maybe this confusion was caused by inadequate docs? This should probably be included in https://scancode-toolkit.readthedocs.io/en/stable/cli-reference/other-commands.html which is at https://github.com/aboutcode-org/scancode-toolkit/blob/develop/docs/source/cli-reference/other-commands.rst

If you can confirm this, it would be great. We can then convert the issue to enhance the docs on this.

**Comment by sschuberth** [comment]
I can confirm that both `scancode-license-data --help` and `scancode-license-data --path license-data` work, but my point is that just running `scancode-license-data` (without arguments) should not crash. Instead, it should probably just print the help as well.

**Comment by AyanSinhaMahapatra** [comment]
We could add more documentation as suggested in https://github.com/aboutcode-org/scancode-toolkit/issues/4024#issuecomment-2548200726 and probably print a statement to provide path/nudge towards running the help text if someone does not provide a path.

**Comment by sschuberth** [comment]
As no one reads docs, I indeed recommend to "build-in the docs" by making the tool print something meaningful in this case. Thanks!

**Comment by pombredanne** [comment]
The simplest way is to make the option required with a `required=True` arg at https://github.com/aboutcode-org/scancode-toolkit/blob/c40476ab1dcf91fd92f4b2eb5ee64ca4a6aa1002/src/licensedcode/license_db.py#L212

**Comment by lyr-ast** [comment]
I have created a pull request which handles this issue #4026

**Comment by aayushkdev** [comment]
could you look at my pr and see if its fit for merging #4029

**Comment by chinyeungli** [comment]
@AyanSinhaMahapatra 
I think this can be closed?
```
(venv) PS C:\Users\thoma\vscode\scancode-toolkit> scancode-license-data
Usage: scancode-license-data [OPTIONS]

Error: Missing option '--path'.
(venv) PS C:\Users\thoma\vscode\scancode-toolkit>
```
Not sure if you re-opened it by mistake, or is there something that need to be done?

**Comment by AyanSinhaMahapatra** [comment]
@chinyeungli we are missing a documentation entry to be added for this at https://github.com/aboutcode-org/scancode-toolkit/blob/develop/docs/source/cli-reference/other-commands.rst
