### ISSUE TITLE
json2csv fails

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#444]
```
(scancode-toolkit) C:\Users\CYL\git\scancode-toolkit\etc\scripts>python json2csv.py "C:\Users\CYL\nexB\Projects\abc def\scancode-files\data.json" "C:\Users\CYL\nexB\Projects\abc def\kc-client.csv"
Traceback (most recent call last):
  File "json2csv.py", line 203, in <module>
    cli()
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "json2csv.py", line 199, in cli
    json_scan_to_csv(json_input, csv_output)
  File "json2csv.py", line 69, in json_scan_to_csv
    rows = list(flatten_scan(scan_results))
  File "json2csv.py", line 84, in flatten_scan
    path = scanned_file['path']
KeyError: 'path'
```

**Comment by JonoYang** [comment]
@chinyeungli Use the branch for [#415](https://github.com/nexB/scancode-toolkit/tree/415-legacy-json2csv)

**Comment by chinyeungli** [comment]
okay.. let me try

**Comment by chinyeungli** [comment]
I still get the same error.

```
(scancode-toolkit) C:\Users\CYL\git\scancode-toolkit>git pull
Already up-to-date.

(scancode-toolkit) C:\Users\CYL\git\scancode-toolkit>git branch
  339-upgrade-json2csv.py
  408-update-lic-category
* 415-legacy-json2csv
  develop
  master

(scancode-toolkit) C:\Users\CYL\git\scancode-toolkit>cd etc\scripts

(scancode-toolkit) C:\Users\CYL\git\scancode-toolkit\etc\scripts>python json2csv.py "C:\Users\CYL\nexB\Projects\abc def\scancode-files\data.json" "C:\Users\CYL\nexB\Projects\abc def\data.csv"
Traceback (most recent call last):
  File "json2csv.py", line 203, in <module>
    cli()
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "json2csv.py", line 199, in cli
    json_scan_to_csv(json_input, csv_output)
  File "json2csv.py", line 69, in json_scan_to_csv
    rows = list(flatten_scan(scan_results))
  File "json2csv.py", line 84, in flatten_scan
    path = scanned_file['path']
KeyError: 'path'

(scancode-toolkit) C:\Users\CYL\git\scancode-toolkit\etc\scripts>
```

**Comment by JonoYang** [comment]
The script is called json2csv_legacy.py, so run:

```
python json2csv_legacy.py <input_file> <output_file>
```

**Comment by chinyeungli** [comment]
Thanks.
There is 1 issue.
```
(scancode-toolkit) C:\Users\CYL\git\scancode-toolkit\etc\scripts>python json2csv_legacy.py "C:\Users\CYL\nexB\Projects\abc def\scancode-files\data.json" "C:\Users\CYL\nexB\Projects\abc def\data.csv"
Traceback (most recent call last):
  File "json2csv_legacy.py", line 345, in <module>
    cli()
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "json2csv_legacy.py", line 341, in cli
    json_scan_to_csv(json_input, csv_output, strip=strip)
  File "json2csv_legacy.py", line 122, in json_scan_to_csv
    with open(csv_output, 'wb') as output:
IOError: [Errno 2] No such file or directory: 'C:\Users\CYL\nexB\Projects\abc def\data.csv'
```

However, if I change the output path to `C:\Users\CYL\nexB\Projects\data.csv`. It runs fine.
So, perhaps the current code doesn't support space in the output path?

**Comment by JonoYang** [comment]
I think that may be the case. I will have to look into how paths are handled in the program and also test this script on Windows.

**Comment by JonoYang** [comment]
@chinyeungli For the error above:
```
IOError: [Errno 2] No such file or directory: 'C:\Users\CYL\nexB\Projects\abc def\data.csv'
```
Does the directory "abc def" exist? If you try to create a file for writing at a location where the directory does not exist, in this case "abc def", Python will say that there is no such file or directory.

**Comment by chinyeungli** [comment]
I think it exists. I replaced the original path (sensitive information) with `abc def` for reporting. Perhaps I may be wrong if you checked that it should work if the directory exist 👍

**Comment by JonoYang** [comment]
I have tested json2csv_legacy.py in a Windows 10 VM. There are no issues with saving the output CSV to a directory with a space in it's name. 

There is an issue when you save a file to a directory that does not exist:
```
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Jono\\Desktop\\does not exist\\out.csv'
```

**Comment by pombredanne** [comment]
Closing. feel free to reopen if this still happens.
