### ISSUE TITLE
InvalidDocumentError while scanning with spdx-rdf format

### ISSUE THREAD

**Issue by yashdsaraf** [nexB/scancode-toolkit#692]
**Operating system:** Linux x86_64 (Arch Linux 4.11.6-3)
**Python version:** 2.7.13 (running in virtualenv)
**Command:**
`./scancode -clip -f spdx-rdf samples`
**Stack trace:**
```
Traceback (most recent call last):                                                                                                      
  File "/home/rorschack/Workspace/scancode-toolkit/bin/scancode", line 11, in <module>                                                  
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()                                                               
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 722, in __call__                    
    return self.main(*args, **kwargs)                                                                                                   
  File "/home/rorschack/Workspace/scancode-toolkit/src/scancode/utils.py", line 76, in main                                             
    standalone_mode=standalone_mode, **extra)                                                                                           
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 697, in main                        
    rv = self.invoke(ctx)                                                                                                               
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 895, in invoke                      
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/click/core.py", line 535, in invoke                      
    return callback(*args, **kwargs)                                
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func               
    return f(get_current_context(), *args, **kwargs)                
  File "/home/rorschack/Workspace/scancode-toolkit/src/scancode/cli.py", line 407, in scancode                                          
    save_results(scanners, only_findings, files_count, results, format, options, input, output_file)                                    
  File "/home/rorschack/Workspace/scancode-toolkit/src/scancode/cli.py", line 788, in save_results                                      
    write_formatted_output(scanners, files_count, version, notice, results, format, options, input, output_file, echo_stderr)           
  File "/home/rorschack/Workspace/scancode-toolkit/src/formattedcode/writers.py", line 61, in write_formatted_output                    
    write_spdx(version, notice, scanned_files, format, input, output_file)                                                              
  File "/home/rorschack/Workspace/scancode-toolkit/src/formattedcode/writers.py", line 259, in write_spdx                               
    write_document(doc, str_buffer, validate=True)                  
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/spdx/writers/rdf.py", line 570, in write_document        
    writer.write()                
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/spdx/writers/rdf.py", line 542, in write                 
    files = self.files()          
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/spdx/writers/rdf.py", line 261, in files                 
    return map(self.create_file_node, self.document.files)          
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/spdx/writers/rdf.py", line 233, in create_file_node      
    license_info_nodes = map(self.license_or_special, doc_file.licenses_in_file)                                                        
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/spdx/writers/rdf.py", line 190, in license_or_special    
    return self.create_license_node(lic)                            
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/spdx/writers/rdf.py", line 177, in create_license_node   
    return self.create_license_helper(lic)                          
  File "/home/rorschack/Workspace/scancode-toolkit/lib/python2.7/site-packages/spdx/writers/rdf.py", line 137, in create_license_helper 
    raise InvalidDocumentError('Missing extracted license: {0}'.format(lic.identifier))                                                 
spdx.writers.tagvalue.InvalidDocumentError: Missing extracted license: LGPL-2.1+ 
```

**Comment by pombredanne** [comment]
Fixed and merged in develop. @yashdsaraf Thanks
