### ISSUE TITLE
Infinite loop when scaning a weird POM

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#721]
With http://repo1.maven.org/maven2/com/github/albertoanguita/jacuzzi-database/0.2.1/jacuzzi-database-0.2.1.pom
scanning for packages goes in an infinite loop
Ctrl-C gives this stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    result = (True, func(*args, **kwds))
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/scancode/cli.py", line 640, in _scanit
    success, scan_result = interruptible(scans_runner, timeout=timeout)
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/scancode/interrupt.py", line 84, in interruptible
    return True, func(*(args or ()), **(kwargs or {}))
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/scancode/cli.py", line 718, in scan_one
    scan_details = scan_func(input_file)
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/scancode/api.py", line 239, in get_package_infos
    package = recognize_package(location)
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/packagedcode/recognize.py", line 58, in recognize_package
    return package.recognize(location)
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/packagedcode/maven.py", line 69, in recognize
    return parse(location)
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/packagedcode/maven.py", line 616, in parse
    mavenpom = _get_mavenpom(location, check_is_pom=True)
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/packagedcode/maven.py", line 606, in _get_mavenpom
    pom.resolve()
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/packagedcode/maven.py", line 257, in resolve
    resolved = self._replace_properties(attr_val, properties)
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/packagedcode/maven.py", line 226, in _replace_properties
    return MavenPom._replace_props(text, properties)
  File "//wrk/scancode-toolkit/local/lib/python2.7/site-packages/packagedcode/maven.py", line 215, in _replace_props
    while result and pom.PROPERTY_RE.match(result):
```
basically this causes the loop: `${version}` in the parent and no version in the POM proper and some looping during the properties resolution:
```
    <parent>
        <artifactId>jacuzzi</artifactId>
        <groupId>com.github.albertoanguita</groupId>
        <version>${version}</version>
    </parent>
```

**Comment by pombredanne** [comment]
Here is a list of test cases:
infinite loop:
- http://repo1.maven.org/maven2/org/jvnet/updatecenter2/pkg/2.0.13.1005/pkg-2.0.13.1005.pom
- http://repo1.maven.org/maven2/net/sourceforge/findbugs/coreplugin/1.0.0/coreplugin-1.0.0.pom
- http://repo1.maven.org/maven2/com/github/albertoanguita/jacuzzi-annotations/0.2.1/jacuzzi-annotations-0.2.1.pom
- http://repo1.maven.org/maven2/com/github/albertoanguita/jacuzzi-database/0.2.1/jacuzzi-database-0.2.1.pom
- http://repo1.maven.org/maven2/com/salesforce/argus/argus-webservices/2.7.0/argus-webservices-2.7.0.pom
- http://repo1.maven.org/maven2/com/github/simondan/ojcms/ojcms-beans/0.1-beta/ojcms-beans-0.1-beta.pom

parsing errors
- http://repo1.maven.org/maven2/com/github/vincentrussell/springmvc-rest-docs-maven-plugin/1.0-RC1/springmvc-rest-docs-maven-plugin-1.0-RC1.pom
- http://repo1.maven.org/maven2/maven-javanet-plugin/maven-javanet-plugin/1.7/maven-javanet-plugin-1.7.pom
- http://repo1.maven.org/maven2/io/github/subiyacryolite/jds/3.0.1/jds-3.0.1.pom
- http://repo1.maven.org/maven2/io/github/subiyacryolite/jds/2.17.0718b/jds-2.17.0718b.pom

**Comment by pombredanne** [comment]
Fixed and merged in develop.
