### ISSUE TITLE
pip install scancode-toolkit gives error

### ISSUE THREAD

**Issue by abuhman** [nexB/scancode-toolkit#739]
I ran pip install scancode-toolkit and got this error: 

Exception:
Traceback (most recent call last):
File "/home/anna/Desktop/new_spdx-github/spdx-github/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
status = self.run(options, args)
File "/home/anna/Desktop/new_spdx-github/spdx-github/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
File "/home/anna/Desktop/new_spdx-github/spdx-github/local/lib/python2.7/site-packages/pip/req.py", line 1265, in prepare_files
req_to_install.extras):
File "/home/anna/Desktop/new_spdx-github/spdx-github/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2232, in requires
dm = self._dep_map
File "/home/anna/Desktop/new_spdx-github/spdx-github/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2423, in _dep_map
self.__dep_map = self._compute_dependencies()
File "/home/anna/Desktop/new_spdx-github/spdx-github/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2456, in _compute_dependencies
common = frozenset(reqs_for_extra(None))
File "/home/anna/Desktop/new_spdx-github/spdx-github/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2453, in reqs_for_extra
if req.marker_fn(override={'extra':extra}):
File "/home/anna/Desktop/new_spdx-github/spdx-github/local/lib/python2.7/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
return eval(compiled_marker, environment)
File "<environment marker>", line 1, in <module>
NameError: name 'platform_system' is not defined

Storing debug log for failure in /home/anna/.pip/pip.log

I ran 'pip install scancode-toolkit' from a virtual environment.
I have: 
pip 1.5.4
virtualenv 1.11.4
setuptools 2.2
python 2.7
Ubuntu 14.04

Is it an issue of having too old version for pip or some other thing?  Have I done something wrong in the installation?

I am able to install ScanCode correctly if I do not use pip install.  I download the repository and run the commands to set it up, and use ScanCode's virtual environment.

Thank you.

**Comment by pombredanne** [comment]
Your combo of pip 1.5.4, virtualenv 1.11.4 and setuptools 2.2 is completely out of date... pip current version is 9.x, virtualenv at version 15.x and setuptools is at version 36.x ... :angel: .... so you have really ancient versions and this for sure is unlikely to work with these older versions. Actually several current Python packages are quite unlikely to work with this setup of yours. 

You have two ways to handle this: 
1. do a system update of you installed pip, virtualenv and setuptools (e.. using a sudo pip install --upgrade of each of these)
2. use locally installed versions and do not use the Ubuntu-provided obsolete versions.

**Comment by abuhman** [comment]
Ok thanks I will update these.

**Comment by pombredanne** [comment]
good, the reason why things work otherwise is that ScanCode uses these newer versions and it expects these (its setup.py uses features from them)

**Comment by pombredanne** [comment]
note that if you are in a virtualenv of your own you can also do the pip install --upgrade in there, no sudo needed

**Comment by abuhman** [comment]
ok thanks

**Comment by pombredanne** [comment]
@abuhman When things are OK on your side, please close this ticket

**Comment by abuhman** [comment]
Yes, this is working now that I updated those things.  Thanks, I'll close this.
