### ISSUE TITLE
TypeError: invalid length: 8 when scanning PDF from fop project

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#740]
Using ScanCode version 2.0.1.post135.94d8aaa8, I get

    ERROR: licenses: Traceback (most recent call last):
      File "/workspace/tools/scancode/src/scancode/cli.py", line 730, in scan_one
        scan_details = list(scan_details)
      File "/workspace/tools/scancode/src/scancode/api.py", line 121, in get_licenses
        for match in idx.match(location=location, min_score=min_score):
      File "/workspace/tools/scancode/src/licensedcode/index.py", line 437, in match
        qry = query.build_query(location, query_string, self)
      File "/workspace/tools/scancode/src/licensedcode/query.py", line 107, in build_query
        if not T.contains_text:
      File "/workspace/tools/scancode/src/typecode/contenttype.py", line 429, in contains_text
        elif self.is_pdf and not self.is_pdf_with_text:
      File "/workspace/tools/scancode/src/typecode/contenttype.py", line 413, in is_pdf_with_text
        doc = PDFDocument(parser)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/pdfminer/pdfdocument.py", line 328, in __init__
        self.info.append(dict_value(trailer['Info']))
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/pdfminer/pdftypes.py", line 155, in dict_value
        x = resolve1(x)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/pdfminer/pdftypes.py", line 75, in resolve1
        x = x.resolve(default=default)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/pdfminer/pdftypes.py", line 62, in resolve
        return self.doc.getobj(self.objid)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/pdfminer/pdfdocument.py", line 462, in getobj
        (strmid, index, genno) = xref.get_pos(objid)
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/pdfminer/pdfdocument.py", line 261, in get_pos
        f2 = nunpack(ent[self.fl1:self.fl1+self.fl2])
      File "/workspace/tools/scancode/local/lib/python2.7/site-packages/pdfminer/utils.py", line 175, in nunpack
        raise TypeError('invalid length: %d' % l)
    TypeError: invalid length: 8

when scanning http://svn.apache.org/repos/asf/xmlgraphics/fop/trunk/fop/test/pdf/1.5/test.pdf.

**Comment by armijnhemel** [comment]
This looks like a bug in pdfminer

**Comment by sschuberth** [comment]
Maybe. Are you suggesting me to report it also upstream to [pdfminer](https://github.com/euske/pdfminer)?

In any case, the question is how ScanCode should behave in such cases. I believe it should only report a warning instead of an error, and fall back to treating the PDF like a generic binary file.

**Comment by armijnhemel** [comment]
Oh, the error handling is definitely something that should be improved in ScanCode. But, yeah, probably best to also report it upstream I guesss.

**Comment by sschuberth** [comment]
> But, yeah, probably best to also report it upstream I guesss.

Done. However, given that has been no pdfminer release since 2014 I have doubt this will get fixed upstream.

**Comment by pombredanne** [comment]
@sschuberth Thanks for the report!
@armijnhemel thanks for your input!

About alternative libraries:
-    https://pypi.python.org/pypi/slate and https://pypi.python.org/pypi/PyPDF2 : I tried these in the passt and they had their issues, but are worth revisiting.
-    https://pypi.python.org/pypi/textract : this is a wrapper on the command line `pdftotext`

For now as a simple test, I switched to a maintained fork  of pdfminer called pdfminer.six and pushed this in a branch. It is handling your test PDF alright on Linux at least.

Now, an error was reported by ScanCode but nothing broke beside reporting this error, correct? We could fall back to binary strings extraction on PDF parsing errors, though it would be hard to issue a warning when this happens (at least hard to have a warning issued as part of the `scancode_errors`. A warning could be printed to stderr alright.)
Yet, since PDF content is mostly compressed (except for some header and metadata) a strings extraction would not yield much of anything. So I am not sure that a binary strings fallback would have much value. I need to ponder this a bit.

**Comment by sschuberth** [comment]
If switching to pdfminer.six solves the issue upstream, I'd be fine with not changing the current behavior of ScanCode for now to throw an error :-)

**Comment by pombredanne** [comment]
@sschuberth It sounds like it did solve your error and another older error too.

**Comment by pombredanne** [comment]
Merged in develop!
