### ISSUE TITLE
`npm2aur` NPM package scan error

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#775]
When running the latest `scancode-toolkit` develop branch, an error occurs when scanning a specific npm package: `npm2aur`. 

The source code for this archive is found here: https://registry.npmjs.org/npm2aur/-/npm2aur-0.1.3.tgz

While I have specified `npm2aur`'s version in this ticket as v0.1.3, this error occurs on all other available versions of this package.

Stack tracce: 
```
(scancode-toolkit) [sesser@nexb-lt ~] scancode --diag -p ~/npm2aur/0.1.3/package.json ~/npm2aur-output.json
Scanning files for: packages with 1 process(es)...
Scanning files...
[####################] 1                      
Scanning done.
Some files failed to scan properly:
Path: 0.1.3/package.json
  ERROR: packages: need more than 1 value to unpack
  ERROR: packages: Traceback (most recent call last):
    File "/Users/sesser/code/nexb/scancode-toolkit/src/scancode/cli.py", line 880, in scan_one
      scan_details = scanner(location)
    File "/Users/sesser/code/nexb/scancode-toolkit/src/scancode/api.py", line 253, in get_package_infos
      package = recognize_package(location)
    File "/Users/sesser/code/nexb/scancode-toolkit/src/packagedcode/recognize.py", line 66, in recognize_package
      return package.recognize(location)
    File "/Users/sesser/code/nexb/scancode-toolkit/src/packagedcode/npm.py", line 69, in recognize
      return parse(location)
    File "/Users/sesser/code/nexb/scancode-toolkit/src/packagedcode/npm.py", line 144, in parse
      func(value, package)
    File "/Users/sesser/code/nexb/scancode-toolkit/src/packagedcode/npm.py", line 299, in repository_mapper
      package.vcs_repository = parse_repo_url(repo.get('url'))
    File "/Users/sesser/code/nexb/scancode-toolkit/src/packagedcode/utils.py", line 79, in parse_repo_url
      host, repo = right.split(':', 1)
  ValueError: need more than 1 value to unpack

Scan statistics: 1 files scanned in 0s.
Scan options:    packages with 1 process(es).
Scanning speed:  1.18 files per sec.
Scanning time:   0s.
Indexing time:   0s.
Saving results.
(scancode-toolkit) [sesser@nexb-lt ~] 
```

**Comment by pombredanne** [comment]
This is fixed in develop. Thank!
