### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by meymuthu** [nexB/scancode-toolkit#838]
I am getting an error with Python 86 installed. when running scan code
```
C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop>scancode
Traceback (most recent call last):
  File "C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop\bin\scancode-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages\pkg_resources\__init__.py", line 36, in <module>
    import email.parser
  File "c:\python27\Lib\email\parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "c:\python27\Lib\email\feedparser.py", line 27, in <module>
    from email import message
  File "c:\python27\Lib\email\message.py", line 16, in <module>
    import email.charset
  File "c:\python27\Lib\email\charset.py", line 13, in <module>
    import email.base64mime
  File "c:\python27\Lib\email\base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "c:\python27\Lib\email\utils.py", line 28, in <module>
    import socket
  File "c:\python27\Lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by pombredanne** [comment]
@meymuthu Thanks for the report!
can you give a little more details?

- Which version of ScanCode do you use?
- Where did you get it and how did you install it?
- Which version of Windows do you run? Is this 32 or 64 bits?
- Which Python interpreter did you install, from which download URL and where did you install it?

**Comment by meymuthu** [comment]
Thanks for your help.   
   - Which version of ScanCode do you use? I downloaded scancode from this github https://github.com/nexB/scancode-toolkit
   - Where did you get it and how did you install it?  (same as above - from github and had in windows 10 system) 
   - Which version of Windows do you run? Is this 32 or 64 bits? Windows 64 bit
   - Which Python interpreter did you install, from which download URL and where did you install it?python 2.7.13
Thanks

—


    On Tuesday, November 7, 2017, 5:24:14 AM CST, Philippe Ombredanne <notifications@github.com> wrote:  
 
 
@meymuthu Thanks for the report!
can you give a little more details?
   
   - Which version of ScanCode do you use?
   - Where did you get it and how did you install it?
   - Which version of Windows do you run? Is this 32 or 64 bits?
   - Which Python interpreter did you install, from which download URL and where did you install it?

**Comment by pombredanne** [comment]
So you did a checkout of ScanCode? or you fetched a zip archive? which download link did you use?
And which exact download link did you use for the Python you installed?
Can you run Python and paste here what shows up then?
e.g. something like :
```
Python 2.7.13 (default, Jun 16 2017, 16:03:08) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by pombredanne** [comment]
I need precise details so I can diagnose this ;)

**Comment by meymuthu** [comment]
I downloaded scancode from https://github.com/nexB/scancode-toolkit - Use download Zip option.


Here is my python command
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\umxm9su>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by pombredanne** [comment]
Thanks! And where did you install Python? e.g. which path?

**Comment by pombredanne** [comment]
well could you try this: uninstall Python 2.7.13 32 bits and try instead Python 2.7.14 64 bits from https://www.python.org/ftp/python/2.7.14/python-2.7.14rc1.amd64.msi ?
And then delete the extracted scancode, and extract again and try again?

**Comment by meymuthu** [comment]
thanks, I am getting this error now. 
scancode --format html-app samples samples.html

C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop>scancode --format html-app samples samples.html
Scanning files for: licenses, copyrights, packages with 1 process(es)...
Building license detection index...Traceback (most recent call last):
  File "C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop\bin\scancode-script.py", line 11, in <module>
    load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')()
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\scancode\utils.py", line 74, in main
    standalone_mode=standalone_mode, **extra)
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\scancode\cli.py", line 486, in scancode
    pre_scan_plugins=pre_scan_plugins)
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\scancode\cli.py", line 568, in scan
    get_index(False)
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\licensedcode\cache.py", line 188, in get_index
    _LICENSES_INDEX = get_or_build_index_through_cache()
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\licensedcode\cache.py", line 108, in get_or_build_index_through_cache
    from licensedcode.index import LicenseIndex
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\licensedcode\index.py", line 45, in <module>
    from licensedcode import match
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\licensedcode\match.py", line 37, in <module>
    from licensedcode import query
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\licensedcode\query.py", line 32, in <module>
    import typecode
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\typecode\__init__.py", line 27, in <module>
    from typecode.contenttype import get_type
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\typecode\contenttype.py", line 47, in <module>
    from typecode import magic2
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\typecode\magic2.py", line 215, in <module>
    libmagic = load_lib()
  File "c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\src\typecode\magic2.py", line 197, in load_lib
    root_dir = command.get_base_dirs(bin_dir)[0]
IndexError: list index out of range
C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop>

**Comment by pombredanne** [comment]
This is really mysterious as I never saw any such problem :|
Please try this:
Open a command prompt.
There type these commands exactly (beware these are all case-sensitive commands on purpose):
```
c:
cd c:\apps\scancode-toolkit-develop\scancode-toolkit-develop
configure --clean
configure
scancode --format json-pp samples
```

**Comment by meymuthu** [comment]
while doing configure - I get this message at the end...
ine 11))
Requirement already satisfied: urllib3<1.22,>=1.21.1 in c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages (from requests>=2.7.9->codecov->-r C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop\etc\conf\dev\base.txt (line 11))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages (from requests>=2.7.9->codecov->-r C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop\etc\conf\dev\base.txt (line 11))
Requirement already satisfied: certifi>=2017.4.17 in c:\apps\scancode-toolkit-develop\scancode-toolkit-develop\lib\site-packages (from requests>=2.7.9->codecov->-r C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop\etc\conf\dev\base.txt (line 11))
Installing collected packages: apipkg, py, pytest, execnet, pytest-xdist, bumpversion, coverage, pytest-cov, codecov, xmltodict
Successfully installed apipkg-1.4 bumpversion-0.5.4.dev0 codecov-2.0.9 coverage-4.4.1 execnet-1.4.1 py-1.4.33 pytest-3.1.0 pytest-cov-2.5.1 pytest-xdist-1.16.0 xmltodict-0.11.0
* Configuring ...
Unsupported OS/platform 'win64'.
See https://github.com/nexB/scancode-toolkit/ for supported OS/platforms.
Enter a ticket https://github.com/nexB/scancode-toolkit/issues asking for support of your OS/platform combo.

Failed to execute command:
C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop\bin\python.exe "C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop\etc\conf\base.py". Aborting...

C:\Apps\scancode-toolkit-develop\scancode-toolkit-develop>

**Comment by pombredanne** [comment]
OK, so could you please uninstall Python 64 bits and reinstall Pyth 32 bits and rerun the commands above?

**Comment by pombredanne** [comment]
e.g.
```
c:
cd c:\apps\scancode-toolkit-develop\scancode-toolkit-develop
configure --clean
configure
scancode --format json-pp samples
```

**Comment by meymuthu** [comment]
I do not have python64 - Are you seeing any reference, if so please let me know. I have uninstalled all Python 64 bit and only installed https://www.python.org/ftp/python/2.7.14/python-2.7.14rc1.amd64.msi ?

**Comment by pombredanne** [comment]
ok, can you uninstall this Python (which is Python 64) and reinstall this one instead (32 bits version) https://www.python.org/ftp/python/2.7.14/python-2.7.14.msi ?

**Comment by meymuthu** [comment]
Thanks for your help, that worked.

**Comment by pombredanne** [comment]
Thanks for tracing this. You got me really worried for a sec :)
