### ISSUE TITLE
Improve error reporting when there are duplicate License rules or Licenses

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#986]
This kind of feedback is a tad messy and hard to digest:
```
Setup plugins...
ERROR: failed to setup plugin: scan:licenses:
Traceback (most recent call last):
  File "/tmp/scancode-toolkit-master/src/scancode/cli.py", line 568, in scancode
    plugin.setup(**kwargs)
  File "/tmp/scancode-toolkit-master/src/scancode/plugin_license.py", line 117, in setup
    return_value=False)
  File "/tmp/scancode-toolkit-master/src/licensedcode/cache.py", line 64, in get_index
    _LICENSES_INDEX = get_cached_index(cache_dir, check_consistency)
  File "/tmp/scancode-toolkit-master/src/licensedcode/cache.py", line 144, in get_cached_index
    idx = LicenseIndex(rules)
  File "/tmp/scancode-toolkit-master/src/licensedcode/index.py", line 233, in __init__
    self._add_rules(rules, _ranked_tokens)
  File "/tmp/scancode-toolkit-master/src/licensedcode/index.py", line 386, in _add_rules
    raise AssertionError(msg)
AssertionError: Duplicate rules: 
[u'file:///tmp/scancode-toolkit-master/src/licensedcode/data/rules/gpl-2.0_or_bsd-new23.RULE', u'file:///tmp/scancode-toolkit-master/src/licensedcode/data/rules/bsd-new_or_gpl-2.0_18.RULE']
[u'file:///tmp/scancode-toolkit-master/src/licensedcode/data/rules/mit_template.RULE', u'file:///tmp/scancode-toolkit-master/src/licensedcode/data/rules/mit_128.RULE']
[u'file:///tmp/scancode-toolkit-master/src/licensedcode/data/rules/gpl-2.0_or_bsd-simplified_16.RULE', u'file:///tmp/scancode-toolkit-master/src/licensedcode/data/rules/bsd-simplified_or_gpl-2.0_9.RULE']

```

**Comment by pombredanne** [comment]
The error messages are improved and more actionable and now include file:/// links to the culprit.
