### ISSUE TITLE
Scan error while scanning a JS map file from angular-sanitize

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#996]
In https://codeload.github.com/angular/bower-angular-sanitize/zip/v1.6.1 scanning angular-sanitize.min.js with the latest develop yield this error:
```
$ scancode -l ~/tmp/sani/angular-sanitize.min.js.map --json-pp -  --verbose
 Setup plugin: output:json-pp...
 Setup plugin: scan:licenses...
Collect file inventory...
Scan files for: licenses with 1 process(es)...
Scanned: /tmp/sani/angular-sanitize.min.js.map
Save scan results...
 Save scan results as: json-pp...
{
  "scancode_notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
  "scancode_version": "2.9.0b1.post32.fea65d35a",
  "scancode_options": {
    "input": "/tmp/sani/angular-sanitize.min.js.map",
    "--json-pp": "<stdout>",
    "--license": true,
    "--verbose": true
  },
  "files_count": 1,
  "files": [
    {
      "path": "angular-sanitize.min.js.map",
      "type": "file",
      "licenses": [],
      "scan_errors": [
        "ERROR: for scanner: licenses:\nERROR: Unknown error:\nTraceback (most recent call last):\n  File \"/tmp/scancode-toolkit-master/src/scancode/interrupt.py\", line 91, in interruptible\n    return NO_ERROR, func(*(args or ()), **(kwargs or {}))\n  File \"/tmp/scancode-toolkit-master/src/scancode/api.py\", line 143, in get_licenses\n    for match in idx.match(location=location, min_score=min_score):\n  File \"/tmp/scancode-toolkit-master/src/licensedcode/index.py\", line 426, in match\n    qry = query.build_query(location, query_string, self)\n  File \"/tmp/scancode-toolkit-master/src/licensedcode/query.py\", line 124, in build_query\n    qry = Query(location=location, idx=idx, line_threshold=80)\n  File \"/tmp/scancode-toolkit-master/src/licensedcode/query.py\", line 197, in __init__\n    self.tokenize_and_build_runs(self.tokens_by_line(tokenizer=tokenizer), line_threshold=line_threshold)\n  File \"/tmp/scancode-toolkit-master/src/licensedcode/query.py\", line 320, in tokenize_and_build_runs\n    for tokens in tokens_by_line:\n  File \"/tmp/scancode-toolkit-master/src/licensedcode/query.py\", line 370, in break_long_lines\n    for line in lines:\n  File \"/tmp/scancode-toolkit-master/src/licensedcode/query.py\", line 264, in tokens_by_line\n    for lnum, line  in enumerate(query_lines(self.location, self.query_string), line_start):\n  File \"/tmp/scancode-toolkit-master/src/licensedcode/tokenize.py\", line 60, in query_lines\n    for line in lines:\n  File \"/tmp/scancode-toolkit-master/src/textcode/analysis.py\", line 206, in js_map_sources_lines\n    sources = content['sourcesContent']\nKeyError: u'sourcesContent'\n"
      ]
    }
  ]
}
Scanning done.
Some files failed to scan properly:
Path: angular-sanitize.min.js.map
  ERROR: for scanner: licenses:
  ERROR: Unknown error:
  Traceback (most recent call last):
    File "/tmp/scancode-toolkit-master/src/scancode/interrupt.py", line 91, in interruptible
      return NO_ERROR, func(*(args or ()), **(kwargs or {}))
    File "/tmp/scancode-toolkit-master/src/scancode/api.py", line 143, in get_licenses
      for match in idx.match(location=location, min_score=min_score):
    File "/tmp/scancode-toolkit-master/src/licensedcode/index.py", line 426, in match
      qry = query.build_query(location, query_string, self)
    File "/tmp/scancode-toolkit-master/src/licensedcode/query.py", line 124, in build_query
      qry = Query(location=location, idx=idx, line_threshold=80)
    File "/tmp/scancode-toolkit-master/src/licensedcode/query.py", line 197, in __init__
      self.tokenize_and_build_runs(self.tokens_by_line(tokenizer=tokenizer), line_threshold=line_threshold)
    File "/tmp/scancode-toolkit-master/src/licensedcode/query.py", line 320, in tokenize_and_build_runs
      for tokens in tokens_by_line:
    File "/tmp/scancode-toolkit-master/src/licensedcode/query.py", line 370, in break_long_lines
      for line in lines:
    File "/tmp/scancode-toolkit-master/src/licensedcode/query.py", line 264, in tokens_by_line
      for lnum, line  in enumerate(query_lines(self.location, self.query_string), line_start):
    File "/tmp/scancode-toolkit-master/src/licensedcode/tokenize.py", line 60, in query_lines
      for line in lines:
    File "/tmp/scancode-toolkit-master/src/textcode/analysis.py", line 206, in js_map_sources_lines
      sources = content['sourcesContent']
  KeyError: u'sourcesContent'
Summary:        licenses with 1 process(es)
Errors count:   1
Scan Speed:     0.82 files/sec. 
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s) 
Final counts:   1 resource(s): 1 file(s) and 0 directorie(s) 
Timings:
  setup_scan:licenses: 1.71s
  setup: 1.71s
  scan: 1.22s
  total: 2.94s

```

This map files has symbols and no `sourcesContent` : we should not assume this is always there

**Comment by pombredanne** [comment]
@majurg ping. You pointed this issue to me.

**Comment by pombredanne** [comment]
Fixed in develop

**Comment by pombredanne** [comment]
And confirmed also by @sschuberth
